'\" t
.\"     Title: mkvtoolnix-gui
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-12-27
.\"    Manual: 用户命令
.\"    Source: MKVToolNix 9.7.1
.\"  Language: Chinese
.\"
.TH "MKVTOOLNIX\-GUI" "1" "2016\-12\-27" "MKVToolNix 9\&.7\&.1" "用户命令"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名称"
mkvtoolnix-gui \- \fBmkvmerge\fR(1) 的 GUI，包含章节编辑器和头部字段编辑器
.SH "概要"
.HP \w'\fBmkvtoolnix\-gui\fR\ 'u
\fBmkvtoolnix\-gui\fR [[配置文件名\&.mtxcfg] | [source\-file\&.ext] | [\-\-edit\-chapters\ [章节文件\&.扩展名]] | [\-\-edit\-headers\ [matroska\-文件\&.mkv]]]
.SH "说明"
.PP
\fBmkvtoolnix-gui\fR(1)
是基于
Qt(TM)
的
\fBmkvmerge\fR(1)
GUI
(将来也会支持
\fBmkvinfo\fR(1)
与
\fBmkvextract\fR(1))。通过它可以轻松访问
\fBmkvmerge\fR(1)\*(Aqs 的大多数选项。所有设置项 (如源文件、轨道选项等) 均可以保存／恢复。
.PP
列出扩展名为
\&.mtxcfg
的配置文件名，可让 GUI 在对应工具中加载这些配置文件。其他文件名将根据当前模式，添加为待合并的输入文件、在章节编辑器或头部编辑器中打开。当前模式可通过
\fB\-\-merge\fR、\fB\-\-edit\-chapters\fR
或
\fB\-\-edit\-headers\fR
修改。默认模式为添加文件用于合并。
.PP
注意，若再次启动应用程序时，已经有一个该应用程序的实例在运行，则命令行给出的所有文件都将由已在运行的实例处理。
.PP
\fB\-\-merge\fR
.RS 4
后面的所有文件名都将作为输入文件添加到当前合并任务。这是默认模式。
.RE
.PP
\fB\-\-edit\-chapters\fR
.RS 4
后面的所有文件名都将在章节编辑器中打开。
.RE
.PP
\fB\-\-edit\-headers\fR
.RS 4
后面的所有文件名都将在头部编辑器中打开。
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
显示用法信息并退出。
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
显示版本信息并退出。
.RE
.SH "参阅"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1)
.SH "网络"
.PP
最新版本总可以在
\m[blue]\fBMKVToolNix 主页\fR\m[]\&\s-2\u[1]\d\s+2
找到。
.SH "作者"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
开发者
.RE
.SH "备注"
.IP " 1." 4
MKVToolNix 主页
.RS 4
\%https://mkvtoolnix.download/
.RE
