'\" t
.\"     Title: mkvextract
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-09-11
.\"    Manual: 사용자 명령어
.\"    Source: MKVToolNix 9.4.2
.\"  Language: English
.\"
.TH "MKVEXTRACT" "1" "2016\-09\-11" "MKVToolNix 9\&.4\&.2" "사용자 명령어"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mkvextract \- Matroska(TM) 파일에서 다른 파일로 트랙 추출
.SH "개요"
.HP \w'\fBmkvextract\fR\ 'u
\fBmkvextract\fR {모드} {소스\-파일명} [옵션] [추출\-스펙]
.SH "설명"
.PP
이 프로그램은
Matroska(TM)
파일에서 다른 유용한 형식으로 특정 부분을 추출합니다\&. 첫번째 인수인
\fBmode\fR
는
\fBmkvextract\fR(1)
에게 추출할 것을 알려 줍니다\&. 현재
tracks,
tags,
attachments,
chapters,
CUE sheets,
timecodes
and
cues의 추출을 지원합니다\&. 두 번째 인수는 소스 파일의 이름인데 반드시
Matroska(TM)
파일이어야 합니다\&. 다음의 모든 인수들은 옵션과 추출 사양입니다; 두 가지 모두 선택한 모드에 따라 다릅니다\&.
.SS "공통 옵션"
.PP
다음 옵션은 모든 모드에서 사용 가능하고 이 부분에서 단 한번만 설명합니다\&.
.PP
\fB\-f\fR, \fB\-\-parse\-fully\fR
.RS 4
분석 모드를 \*(Aq전부\*(Aq로 설정합니다\&. 기본 모드는 전체 파일을 분석하지 않지만 소스 파일의 필요한 요소를 찾기 위해 메타 탐색 요소를 사용합니다\&. 이것은 99% 가량의 모든 경우에 충분합니다\&. 그러나 메타 탐색 요소를 포함하지 않거나 손상된 파일에서 사용자는 이 모드를 사용해야 할 지 모릅니다\&. 빠른 스캔은 몇 초밖에 안 걸리지만, 파일 전체 스캔은 이 삼분 걸릴 수 있습니다\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fI문자셋\fR
.RS 4
명령행에 주어진 문자열을 변환할 문자셋을 정합니다\&. 기본값은 현재 시스템 로케일에 따른 문자셋입니다\&.
.RE
.PP
\fB\-\-output\-charset\fR \fI문자셋\fR
.RS 4
출력할 문자열을 변환할 문자셋을 정합니다\&. 기본값은 현재 시스템 로케일에 따른 문자셋입니다\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fI파일명\fR
.RS 4
모든 메시지를 콘솔 화면 대신
\fI파일명\fR
파일에 기록합니다\&. 이것은 출력 방향 전환으로 쉽게 할 수 있지만 이 옵션이 필요한 경우가 있습니다: 터미널이 파일에 출력하기 전에 출력을 재해석할 때\&. 문자셋 설정은
\fB\-\-output\-charset\fR
을 준수합니다\&.
.RE
.PP
\fB\-\-ui\-language\fR \fI코드\fR
.RS 4
언어
\fI코드\fR의 번역을 강제로 사용합니다 (예: 강제 사용할 독일어 번역 코드는 \*(Aqde_DE\*(Aq)\&. \*(Aqlist\*(Aq를
\fI코드\fR로 입력하면
\fBmkvextract\fR(1)
에서 이용 가능한 번역 목록을 출력할 것입니다\&.
.RE
.PP
\fB\-\-debug\fR \fI토픽\fR
.RS 4
특정 기능에 대해 디버깅을 켭니다\&. 이 기능은 개발자에게만 유용합니다\&.
.RE
.PP
\fB\-\-engage\fR \fI기능\fR
.RS 4
실험적인 기능을 켭니다\&. 이용 가능한 기능 목록은
\fBmkvextract \-\-engage list\fR로 요청할 수 있습니다\&. 이 기능들은 보통 상황에서는 사용하면 안 됩니다\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
GUI 모드를 켭니다\&. 이 모드에서는 GUI 동작시 무슨 일이 일어나는지 알려줄 수 있는 특별하게 형식화된 줄을 출력할 것입니다\&. 이 메시지들은 \*(Aq#GUI#message\*(Aq 형식을 따릅니다\&. 이 메시지 뒤에 \*(Aq#GUI#message#key1=value1#key2=value2\&...\*(Aq 형태의 키/값 쌍이 붙을 수 있습니다\&. 메시지나 키값들은 결코 번역되지 않고 항상 영어로 출력됩니다\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
읽어들인 모든 중요한
Matroska(TM)
요소를 자세하게 보여 줍니다\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
사용법에 관한 정보를 표시하고 종료합니다\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
버전 정보를 표시하고 종료합니다\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]
URL을 다운로드하여 새로운 버전이 나왔는지 온라인에서 확인합니다\&.
key=value
스타일의 네 줄이 출력될 것입니다: 정보를 검색하는 주소 (key
version_check_url), 현재 실행 중인 버전 (key
running_version), 가장 최근에 나온 버전 (key
available_version), 다운로드 URL (key
download_url)\&.
.sp
이후에 프로그램은 이용 가능한 새 버전이 없으면 0, 새 버전이 있으면 1, 오류 발생시(업데이트 정보를 가져올 수 없는 경우)는 2의 종료 코드를 가지고 있습니다\&.
.sp
이 옵션은 libcurl을 지원하도록 프로그램을 만든 경우에만 이용 가능합니다\&.
.RE
.PP
\fB@\fR\fI옵션 파일\fR
.RS 4
\fIoptions\-file\fR
파일에서 추가적인 명령행 인수를 읽습니다\&. 공백이 아닌 첫번째 문자가 해쉬 표시(\*(Aq#\*(Aq)인 줄은 주석으로 간주하여 무시합니다\&. 줄의 앞과 끝의 공백은 제거될 것입니다\&. 각 줄에는 반드시 한 개의 옵션을 포함해야 합니다\&.
.sp
예를 들어 \*(Aq#\*(Aq이 붙은 비주석 줄을 시작할 필요가 있는 경우에는 몇몇 확장 문자를 사용할 수 있습니다\&. 규칙은
확장 텍스트에 대한 부분에 기술되어 있습니다\&.
.sp
명령행 \*(Aq\fBmkvextract tracks 소스\&.mkv \-\-raw 1:대상\&.raw\fR\*(Aq은 다음 옵션 파일로 변환될 수 있습니다:
.sp
.if n \{\
.RS 4
.\}
.nf
# 소스\&.mkv에서 트랙 추출
tracks
소스\&.mkv
# 트랙을 원시 데이터로 출력
\-\-raw
1:대상\&.raw
.fi
.if n \{\
.RE
.\}
.RE
.SS "트랙 추출 모드"
.PP
구문:
\fBmkvextract \fR\fB\fBtracks\fR\fR\fB \fR\fB\fI소스파일명\fR\fR\fB \fR\fB[\fI옵션\fR]\fR\fB \fR\fB\fITID1:대상파일명1\fR\fR\fB \fR\fB[\fITID2:대상파일명2\fR \&.\&.\&.]\fR
.PP
다음 명령행 옵션은 \*(Aq트랙\*(Aq 추출 모드에서 각 트랙에 대해 사용할 수 있습니다\&. 이 옵션들은 적용이 되야 하는 트랙 사양(아래 참고) 의 앞쪽에 나타나야 합니다\&.
.PP
\fB\-c\fR \fI문자셋\fR
.RS 4
다음 자막 트랙을 변환할 문자셋을 설정합니다\&. 다음 트랙 ID가 텍스트 자막 트랙을 대상으로 하는 경우에만 유효합니다\&. 기본값은 UTF\-8\&.
.RE
.PP
\fB\-\-blockadd\fR \fI수준\fR
.RS 4
이 수준까지만 BlockAddition을 유지합니다\&. 기본값은 모든 수준을 유지하는 것입니다\&. 이 옵션은 WAVPACK4같은 특정한 코덱에만 효과가 있습니다\&.
.RE
.PP
\fB\-\-cuesheet\fR
.RS 4
\fBmkvextract\fR(1)로
큐시트를 챕터 정보에서 추출하고 다음 트랙의 데이터를 파일명이 트랙의 출력 이름이고 확장자가 \*(Aq\&.cue\*(Aq 인 파일에 태그로 기록합니다\&.
.RE
.PP
\fB\-\-raw\fR
.RS 4
컨테이너에서 원시 데이터를 파일로 추출합니다\&.
\fB\-\-fullraw\fR
플래그와 다르게 이 플래그는
CodecPrivate
요소의 내용이 그 파일에 기록되지 않습니다\&. 이 모드는 모든
CodecIDs와 동작합니다\&. 그 외에
\fBmkvextract\fR(1)가 지원하지 않는
CodecIDs에서도 동작이 됩니다\&. 다만 그 결과로 나오는 파일은 아마도 사용하지 못할 것입니다\&.
.RE
.PP
\fB\-\-fullraw\fR
.RS 4
원시 데이터를 컨테이너에 넣지 않고 단순한 파일로 추출합니다\&.
CodecPrivate
요소의 내용은 만약 트랙이 그런 헤더 요소를 포함하고 있으면 파일에 먼저 기록될 것입니다\&. 이 모드는 모든
CodecIDs과
\fBmkvextract\fR(1)
가 지원하지 않는
CodecIDs에서도 동작하지만 그 결과로 나오는 파일은 아마도 사용하지 못할 것입니다\&.
.RE
.PP
\fITID:출력이름\fR
.RS 4
소스 파일에
\fITID\fR
ID의 트랙이 있으면
\fI출력이름\fR
파일로 추출합니다\&. 이 옵션은 여러 번 사용할 수 있습니다\&. 트랙 ID는
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
옵션으로 나오는 것과 같습니다\&.
.sp
각 출력 이름은 한 번만 사용해야 합니다\&. RealAudio와 RealVideo 트랙은 예외적입니다\&. 다른 트랙들에 같은 이름을 사용하면 해당 트랙들은 같은 파일에 저장이 될 것입니다\&. 예:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tracks input\&.mkv 1:output\-two\-tracks\&.rm 2:output\-two\-tracks\&.rm
.fi
.if n \{\
.RE
.\}
.RE
.SS "태그 추출 모드"
.PP
Syntax:
\fBmkvextract \fR\fB\fBtags\fR\fR\fB \fR\fB\fI소스파일명\fR\fR\fB \fR\fB[\fI옵션\fR]\fR
.PP
추출한 태그는 그 출력의 방향을 바꾸지 않는 한 콘솔에 기록됩니다 (세부 사항은출력 방향 전환에 관한 부분을 보세요)\&.
.SS "첨부 파일 추출 모드"
.PP
Syntax:
\fBmkvextract \fR\fB\fBattachments\fR\fR\fB \fR\fB\fI소스파일명\fR\fR\fB \fR\fB[\fI옵션\fR]\fR\fB \fR\fB\fIAID1:출력이름1\fR\fR\fB \fR\fB[\fIAID2:출력이름2\fR \&.\&.\&.]\fR
.PP
\fIAID\fR:\fI출력이름\fR
.RS 4
소스 파일에 ID
\fIAID\fR의 첨부 파일이 있으면
\fI출력이름\fR
파일로 추출합니다\&.
\fI출력이름\fR이 없으면 소스
Matroska(TM)
파일 안의 첨부 파일명을 대신 사용합니다\&. 이 옵션은 여러 번 사용할 수 있습니다\&. 첨부 파일 ID는
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
옵션으로 나오는 출력과 같습니다\&.
.RE
.SS "챕터 추출 모드"
.PP
Syntax:
\fBmkvextract \fR\fB\fBchapters\fR\fR\fB \fR\fB\fI소스파일명\fR\fR\fB \fR\fB[\fI옵션\fR]\fR
.PP
\fB\-s\fR, \fB\-\-simple\fR
.RS 4
챕터 정보를
OGM
도구에서 사용되는 단순 형식(CHAPTER01=\&.\&.\&. CHAPTER01NAME=\&.\&.\&.)으로 내보냅니다\&. 이 모드에서 몇몇 정보는 폐기되어야만 합니다\&. 기본값은 챕터를
XML
형식으로 출력하는 것입니다\&.
.RE
.PP
\fB\-\-simple\-language\fR \fI언어\fR
.RS 4
If the simple format is enabled then
\fBmkvextract\fR(1)
will only output a single entry for each chapter atom encountered even if a chapter atom contains more than one chapter name\&. By default
\fBmkvextract\fR(1)
will use the first chapter name found for each atom regardless of its language\&.
.sp
Using this option allows the user to determine which chapter names are output if atoms contain more than one chapter name\&. The
\fIlanguage\fR
parameter must be an ISO 639\-1 or ISO 639\-2 code\&.
.RE
.PP
The extracted chapters are written to the console unless the output is redirected (see the section about
output redirection
for details)\&.
.SS "큐시트 추출 모드"
.PP
Syntax:
\fBmkvextract \fR\fB\fBcuesheet\fR\fR\fB \fR\fB\fIsource\-filename\fR\fR\fB \fR\fB[\fIoptions\fR]\fR
.PP
The extracted cue sheet is written to the console unless the output is redirected (see the section about
output redirection
for details)\&.
.SS "타임코드 추출 모드"
.PP
Syntax:
\fBmkvextract \fR\fB\fBtimecodes_v2\fR\fR\fB \fR\fB\fIsource\-filename\fR\fR\fB \fR\fB[\fIoptions\fR]\fR\fB \fR\fB\fITID1:dest\-filename1\fR\fR\fB \fR\fB[\fITID2:dest\-filename2\fR \&.\&.\&.]\fR
.PP
The extracted timecodes are written to the console unless the output is redirected (see the section about
output redirection
for details)\&.
.PP
\fITID:출력이름\fR
.RS 4
Causes extraction of the timecodes for the track with the ID
\fITID\fR
into the file
\fIoutname\fR
if such a track exists in the source file\&. This option can be given multiple times\&. The track IDs are the same as the ones output by
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
option\&.
.sp
예:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract timecodes_v2 input\&.mkv 1:tc\-track1\&.txt 2:tc\-track2\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SS "큐 추출 모드"
.PP
Syntax:
\fBmkvextract \fR\fB\fBcues\fR\fR\fB \fR\fB\fIsource\-filename\fR\fR\fB \fR\fB[\fIoptions\fR]\fR\fB \fR\fB\fITID1:dest\-filename1\fR\fR\fB \fR\fB[\fITID2:dest\-filename2\fR \&.\&.\&.]\fR
.PP
\fITID:dest\-filename\fR
.RS 4
Causes extraction of the cues for the track with the ID
\fITID\fR
into the file
\fIoutname\fR
if such a track exists in the source file\&. This option can be given multiple times\&. The track IDs are the same as the ones output by
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
option and not the numbers contained in the
CueTrack
element\&.
.RE
.PP
The format output is a simple text format: one line per
CuePoint
element with
key=value
pairs\&. If an optional element is not present in a
CuePoint
(e\&.g\&.
CueDuration) then a dash will be output as the value\&.
.PP
예:
.sp
.if n \{\
.RS 4
.\}
.nf
timecode=00:00:13\&.305000000 duration=\- cluster_position=757741 relative_position=11
.fi
.if n \{\
.RE
.\}
.PP
가능한 키:
.PP
타임코드
.RS 4
The cue point\*(Aqs timecode with nanosecond precision\&. The format is
HH:MM:SS\&.nnnnnnnnn\&. This element is always set\&.
.RE
.PP
지속 시간
.RS 4
The cue point\*(Aqs duration with nanosecond precision\&. The format is
HH:MM:SS\&.nnnnnnnnn\&.
.RE
.PP
클러스터_위치
.RS 4
The absolute position in bytes inside the
Matroska(TM)
file where the cluster containing the referenced element starts\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Inside the
Matroska(TM)
file the
CueClusterPosition
is relative to the segment\*(Aqs data start offset\&. The value output by
\fBmkvextract\fR(1)\*(Aqs cue extraction mode, however, contains that offset already and is an absolute offset from the beginning of the file\&.
.sp .5v
.RE
.RE
.PP
상대적인_위치
.RS 4
The relative position in bytes inside the cluster where the
BlockGroup
or
SimpleBlock
element the cue point refers to starts\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Inside the
Matroska(TM)
file the
CueRelativePosition
is relative to the cluster\*(Aqs data start offset\&. The value output by
\fBmkvextract\fR(1)\*(Aqs cue extraction mode, however, is relative to the cluster\*(Aqs ID\&. The absolute position inside the file can be calculated by adding
cluster_position
and
relative_position\&.
.sp .5v
.RE
.RE
.PP
예:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract cues input\&.mkv 1:cues\-track1\&.txt 2:cues\-track2\&.txt
.fi
.if n \{\
.RE
.\}
.SH "출력 방향 변경"
.PP
Several extraction modes cause
\fBmkvextract\fR(1)
to write the extracted data to the console\&. There are generally two ways of writing this data into a file: one provided by the shell and one provided by
\fBmkvextract\fR(1)
itself\&.
.PP
The shell\*(Aqs builtin redirection mechanism is used by appending \*(Aq> output\-filename\&.ext\*(Aq to the command line\&. Example:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tags source\&.mkv > tags\&.xml
.fi
.if n \{\
.RE
.\}
.PP
\fBmkvextract\fR(1)\*(Aqs own redirection is invoked with the
\fB\-\-redirect\-output\fR
option\&. Example:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tags source\&.mkv \-\-redirect\-output tags\&.xml
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
On Windows you should probably use the
\fB\-\-redirect\-output\fR
option because
\fBcmd\&.exe\fR
sometimes interpretes special characters before they\*(Aqre written into the output file resulting in broken output\&.
.sp .5v
.RE
.SH "TEXT FILES AND CHARACTER SET CONVERSIONS"
.PP
For an in\-depth discussion about how all tools in the MKVToolNix suite handle character set conversions, input/output encoding, command line encoding and console encoding please see the identically\-named section in the
\fBmkvmerge\fR(1)
man page\&.
.SH "출력 파일 형식"
.PP
The decision about the output format is based on the track type, not on the extension used for the output file name\&. The following track types are supported at the moment:
.PP
V_MPEG4/ISO/AVC
.RS 4
H\&.264
/
AVC
video tracks are written to
H\&.264
elementary streams which can be processed further with e\&.g\&.
MP4Box(TM)
from the
GPAC(TM)
package\&.
.RE
.PP
V_MS/VFW/FOURCC
.RS 4
Fixed
FPS
video tracks with this
CodecID
are written to
AVI
files\&.
.RE
.PP
V_REAL/*
.RS 4
RealVideo(TM)
tracks are written to
RealMedia(TM)
files\&.
.RE
.PP
V_THEORA
.RS 4
Theora(TM)
streams will be written within an
Ogg(TM)
container
.RE
.PP
V_VP8, V_VP9
.RS 4
VP8
/
VP9
tracks are written to
IVF
files\&.
.RE
.PP
A_MPEG/L2
.RS 4
MPEG\-1 Audio Layer II streams will be extracted to raw
MP2
files\&.
.RE
.PP
A_MPEG/L3, A_AC3
.RS 4
These will be extracted to raw
MP3
and
AC\-3
files\&.
.RE
.PP
A_PCM/INT/LIT
.RS 4
Raw
PCM
data will be written to a
WAV
file\&.
.RE
.PP
A_AAC/MPEG2/*, A_AAC/MPEG4/*, A_AAC
.RS 4
All
AAC
files will be written into an
AAC
file with
ADTS
headers before each packet\&. The
ADTS
headers will not contain the deprecated emphasis field\&.
.RE
.PP
A_VORBIS
.RS 4
Vorbis audio will be written into an
OggVorbis(TM)
file\&.
.RE
.PP
A_REAL/*
.RS 4
RealAudio(TM)
tracks are written to
RealMedia(TM)
files\&.
.RE
.PP
A_TTA1
.RS 4
TrueAudio(TM)
tracks are written to
TTA
files\&. Please note that due to
Matroska(TM)\*(Aqs limited timecode precision the extracted file\*(Aqs header will be different regarding two fields:
\fIdata_length\fR
(the total number of samples in the file) and the
CRC\&.
.RE
.PP
A_ALAC
.RS 4
ALAC
tracks are written to
CAF
files\&.
.RE
.PP
A_FLAC
.RS 4
FLAC
tracks are written to raw
FLAC
files\&.
.RE
.PP
A_WAVPACK4
.RS 4
WavPack(TM)
tracks are written to
WV
files\&.
.RE
.PP
A_OPUS
.RS 4
Opus(TM)
tracks are written to
OggOpus(TM)
files\&.
.RE
.PP
S_TEXT/UTF8
.RS 4
Simple text subtitles will be written as
SRT
files\&.
.RE
.PP
S_TEXT/SSA, S_TEXT/ASS
.RS 4
SSA
and
ASS
text subtitles will be written as
SSA/ASS
files respectively\&.
.RE
.PP
S_KATE
.RS 4
Kate(TM)
streams will be written within an
Ogg(TM)
container\&.
.RE
.PP
S_VOBSUB
.RS 4
VobSub(TM)
subtitles will be written as
SUB
files along with the respective index files, as
IDX
files\&.
.RE
.PP
S_TEXT/USF
.RS 4
USF
text subtitles will be written as
USF
files\&.
.RE
.PP
S_HDMV/PGS
.RS 4
PGS
subtitles will be written as
SUP
files\&.
.RE
.PP
태그
.RS 4
Tags are converted to a
XML
format\&. This format is the same that
\fBmkvmerge\fR(1)
supports for reading tags\&.
.RE
.PP
첨부 파일
.RS 4
Attachments are written to they output file as they are\&. No conversion whatsoever is done\&.
.RE
.PP
챕터
.RS 4
Chapters are converted to a
XML
format\&. This format is the same that
\fBmkvmerge\fR(1)
supports for reading chapters\&. Alternatively a stripped\-down version can be output in the simple
OGM
style format\&.
.RE
.PP
타임코드
.RS 4
Timecodes are first sorted and then output as a timecode v2 format compliant file ready to be fed to
\fBmkvmerge\fR(1)\&. The extraction to other formats (v1, v3 and v4) is not supported\&.
.RE
.SH "종료 코드"
.PP
\fBmkvextract\fR(1)
exits with one of three exit codes:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- This exit codes means that extraction has completed successfully\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- In this case
\fBmkvextract\fR(1)
has output at least one warning, but extraction did continue\&. A warning is prefixed with the text \*(AqWarning:\*(Aq\&. Depending on the issues involved the resulting files might be ok or not\&. The user is urged to check both the warning and the resulting files\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- This exit code is used after an error occurred\&.
\fBmkvextract\fR(1)
aborts right after outputting the error message\&. Error messages range from wrong command line arguments over read/write errors to broken files\&.
.RE
.SH "ESCAPING SPECIAL CHARS IN TEXT"
.PP
There are a few places in which special characters in text must or should be escaped\&. The rules for escaping are simple: each character that needs escaping is replaced with a backslash followed by another character\&.
.PP
The rules are: \*(Aq \*(Aq (a space) becomes \*(Aq\es\*(Aq, \*(Aq"\*(Aq (double quotes) becomes \*(Aq\e2\*(Aq, \*(Aq:\*(Aq becomes \*(Aq\ec\*(Aq, \*(Aq#\*(Aq becomes \*(Aq\eh\*(Aq and \*(Aq\e\*(Aq (a single backslash) itself becomes \*(Aq\e\e\*(Aq\&.
.SH "ENVIRONMENT VARIABLES"
.PP
\fBmkvextract\fR(1)
uses the default variables that determine the system\*(Aqs locale (e\&.g\&.
\fILANG\fR
and the
\fILC_*\fR
family)\&. Additional variables:
.PP
\fIMKVEXTRACT_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR and its short form \fIMTX_DEBUG\fR
.RS 4
The content is treated as if it had been passed via the
\fB\-\-debug\fR
option\&.
.RE
.PP
\fIMKVEXTRACT_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR and its short form \fIMTX_ENGAGE\fR
.RS 4
The content is treated as if it had been passed via the
\fB\-\-engage\fR
option\&.
.RE
.PP
\fIMKVEXTRACT_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR and its short form \fIMTX_OPTIONS\fR
.RS 4
The content is split on white space\&. The resulting partial strings are treated as if it had been passed as command line options\&. If you need to pass special characters (e\&.g\&. spaces) then you have to escape them (see
the section about escaping special characters in text)\&.
.RE
.SH "더 보기"
.PP
\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
The latest version can always be found at
\m[blue]\fBthe MKVToolNix homepage\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTHOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
개발자
.RE
.SH "NOTES"
.IP " 1." 4
the MKVToolNix homepage
.RS 4
\%https://mkvtoolnix.download/
.RE
