'\" t
.\"     Title: mkvinfo
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-12-27
.\"    Manual: 사용자 명령어
.\"    Source: MKVToolNix 9.7.1
.\"  Language: English
.\"
.TH "MKVINFO" "1" "2016\-12\-27" "MKVToolNix 9\&.7\&.1" "사용자 명령어"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mkvinfo \- Print information about elements in Matroska(TM) files
.SH "개요"
.HP \w'\fBmkvinfo\fR\ 'u
\fBmkvinfo\fR [options] {source\-filename}
.SH "설명"
.PP
This program lists all elements contained in a
Matroska(TM)\&. The output can be limited to a list of tracks in the file including information about the codecs used\&.
.PP
\fB\-g\fR, \fB\-\-gui\fR
.RS 4
Start the
GUI\&. This option is only available if mkvinfo was compiled with
GUI
support\&.
.RE
.PP
\fB\-c\fR, \fB\-\-checksums\fR
.RS 4
Calculates and display the
\fBAdler32\fR
checksum for each frame\&. Useful for debugging only\&.
.RE
.PP
\fB\-s\fR, \fB\-\-summary\fR
.RS 4
Only show a terse summary of what
\fBmkvinfo\fR(1)
finds and not each element\&.
.RE
.PP
\fB\-t\fR, \fB\-\-track\-info\fR
.RS 4
Show statistics for each track in verbose mode\&. Also sets verbosity to 1 if it was at level 0 before\&.
.RE
.PP
\fB\-x\fR, \fB\-\-hexdump\fR
.RS 4
각 프레임의 처음 16바이트를 16진수 덤프로 표시합니다\&.
.RE
.PP
\fB\-X\fR, \fB\-\-full\-hexdump\fR
.RS 4
각 프레임의 모든 바이트를 16진수 덤프로 표시합니다\&.
.RE
.PP
\fB\-z\fR, \fB\-\-size\fR
.RS 4
헤더를 포함한 각 요소의 크기를 표시합니다\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fI문자셋\fR
.RS 4
명령행에 주어진 문자열을 변환할 문자셋을 정합니다\&. 기본값은 현재 시스템 로케일에 따른 문자셋입니다\&.
.RE
.PP
\fB\-\-output\-charset\fR \fI문자셋\fR
.RS 4
출력할 문자열을 변환할 문자셋을 정합니다\&. 기본값은 현재 시스템 로케일에 따른 문자셋입니다\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fI파일명\fR
.RS 4
Writes all messages to the file
\fIfile\-name\fR
instead of to the console\&. While this can be done easily with output redirection there are cases in which this option is needed: when the terminal reinterprets the output before writing it to a file\&. The character set set with
\fB\-\-output\-charset\fR
is honored\&.
.RE
.PP
\fB\-\-ui\-language\fR \fI코드\fR
.RS 4
언어
\fI코드\fR의 번역을 강제로 사용합니다 (예: 강제 사용할 독일어 번역 코드는 \*(Aqde_DE\*(Aq)\&. \*(Aqlist\*(Aq를
\fI코드\fR로 입력하면
\fBmkvextract\fR(1)
에서 이용 가능한 번역 목록을 출력할 것입니다\&.
.RE
.PP
\fB\-\-debug\fR \fI토픽\fR
.RS 4
특정 기능에 대해 디버깅을 켭니다\&. 이 기능은 개발자에게만 유용합니다\&.
.RE
.PP
\fB\-\-engage\fR \fI기능\fR
.RS 4
Turn on experimental features\&. A list of available features can be requested with
\fBmkvinfo \-\-engage list\fR\&. These features are not meant to be used in normal situations\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
GUI 모드를 켭니다\&. 이 모드에서는 GUI 동작시 무슨 일이 일어나는지 알려줄 수 있는 특별하게 형식화된 줄을 출력할 것입니다\&. 이 메시지들은 \*(Aq#GUI#message\*(Aq 형식을 따릅니다\&. 이 메시지 뒤에 \*(Aq#GUI#message#key1=value1#key2=value2\&...\*(Aq 형태의 키/값 쌍이 붙을 수 있습니다\&. 메시지나 키값들은 결코 번역되지 않고 항상 영어로 출력됩니다\&.
.sp
This switch has nothing to do with the
\fB\-\-gui\fR
parameter which causes mkvinfo to display its own GUI\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Be more verbose\&. See the section about
verbosity levels
for a description which information will be output at which level\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
사용법에 관한 정보를 표시하고 종료합니다\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
버전 정보를 표시하고 종료합니다\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]
URL을 다운로드하여 새로운 버전이 나왔는지 온라인에서 확인합니다\&.
key=value
스타일의 네 줄이 출력될 것입니다: 정보를 검색하는 주소 (key
version_check_url), 현재 실행 중인 버전 (key
running_version), 가장 최근에 나온 버전 (key
available_version), 다운로드 URL (key
download_url)\&.
.sp
이후에 프로그램은 이용 가능한 새 버전이 없으면 0, 새 버전이 있으면 1, 오류 발생시(업데이트 정보를 가져올 수 없는 경우)는 2의 종료 코드를 가지고 있습니다\&.
.sp
이 옵션은 libcurl을 지원하도록 프로그램을 만든 경우에만 이용 가능합니다\&.
.RE
.PP
\fB@\fR\fIoptions\-file\&.json\fR
.RS 4
Reads additional command line arguments from the file
\fIoptions\-file\fR\&. For a full explanation on the supported formats for such files see the section called "Option files" in the
\fBmkvmerge\fR(1)
man page\&.
.RE
.SH "VERBOSITY LEVELS"
.PP
The
\fB\-v\fR
option can be used to increase
\fBmkvinfo\fR(1)\*(Aqs verbosity level and print more information about the current file\&.
.PP
At level 0
\fBmkvinfo\fR(1)
will print only the track headers it finds and their types\&.
\fBmkvinfo\fR(1)
will exit as soon as the headers are parsed completely (more technical: as soon as the first cluster is encountered)\&. In this level the seek head entries and the cues will not be displayed \-\- even if they\*(Aqre located in front of the track information\&.
.PP
At level 1
\fBmkvinfo\fR(1)
will also print all
Matroska(TM)
elements encountered for the complete file but the seek head entries and the cue entries\&. If the summary mode is enabled then
\fBmkvinfo\fR(1)
will output the frame position as well\&.
.PP
At level 2
\fBmkvinfo\fR(1)
will also print the seek head entries, the cue entries and the file position at which each
Matroska(TM)
element can be found at\&.
.PP
At level 3 and above
\fBmkvinfo\fR(1)
will print some information that is not directly connected to a
Matroska(TM)
element\&. All other elements only print stuff about the elements that were just found\&. Level 3 adds meta information to ease debugging (read: it\*(Aqs intended for developers only)\&. All lines written by level 3 are enclosed in square brackets to make filtering them out easy\&.
.SH "TEXT FILES AND CHARACTER SET CONVERSIONS"
.PP
For an in\-depth discussion about how all tools in the MKVToolNix suite handle character set conversions, input/output encoding, command line encoding and console encoding please see the identically\-named section in the
\fBmkvmerge\fR(1)
man page\&.
.SH "종료 코드"
.PP
\fBmkvinfo\fR(1)
exits with one of three exit codes:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- This exit codes means that the run has completed successfully\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- In this case
\fBmkvinfo\fR(1)
has output at least one warning, but the run did continue\&. A warning is prefixed with the text \*(AqWarning:\*(Aq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- This exit code is used after an error occurred\&.
\fBmkvinfo\fR(1)
aborts right after outputting the error message\&. Error messages range from wrong command line arguments over read/write errors to broken files\&.
.RE
.SH "ESCAPING SPECIAL CHARS IN TEXT"
.PP
There are a few places in which special characters in text must or should be escaped\&. The rules for escaping are simple: each character that needs escaping is replaced with a backslash followed by another character\&.
.PP
The rules are: \*(Aq \*(Aq (a space) becomes \*(Aq\es\*(Aq, \*(Aq"\*(Aq (double quotes) becomes \*(Aq\e2\*(Aq, \*(Aq:\*(Aq becomes \*(Aq\ec\*(Aq, \*(Aq#\*(Aq becomes \*(Aq\eh\*(Aq and \*(Aq\e\*(Aq (a single backslash) itself becomes \*(Aq\e\e\*(Aq\&.
.SH "ENVIRONMENT VARIABLES"
.PP
\fBmkvinfo\fR(1)
uses the default variables that determine the system\*(Aqs locale (e\&.g\&.
\fILANG\fR
and the
\fILC_*\fR
family)\&. Additional variables:
.PP
\fIMKVINFO_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR and its short form \fIMTX_DEBUG\fR
.RS 4
The content is treated as if it had been passed via the
\fB\-\-debug\fR
option\&.
.RE
.PP
\fIMKVINFO_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR and its short form \fIMTX_ENGAGE\fR
.RS 4
The content is treated as if it had been passed via the
\fB\-\-engage\fR
option\&.
.RE
.PP
\fIMKVINFO_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR and its short form \fIMTX_OPTIONS\fR
.RS 4
The content is split on white space\&. The resulting partial strings are treated as if it had been passed as command line options\&. If you need to pass special characters (e\&.g\&. spaces) then you have to escape them (see
the section about escaping special characters in text)\&.
.RE
.SH "더 보기"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvpropedit\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
The latest version can always be found at
\m[blue]\fBthe MKVToolNix homepage\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTHOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
개발자
.RE
.SH "NOTES"
.IP " 1." 4
the MKVToolNix homepage
.RS 4
\%https://mkvtoolnix.download/
.RE
