'\" t
.\"     Title: mkvtoolnix-gui
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-10-16
.\"    Manual: Komendy użytkownika
.\"    Source: MKVToolNix 9.5.0
.\"  Language: Polish
.\"
.TH "MKVTOOLNIX\-GUI" "1" "2016\-10\-16" "MKVToolNix 9\&.5\&.0" "Komendy użytkownika"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAZWA"
mkvtoolnix-gui \- Interfejs graficzny dla \fBmkvmerge\fR(1) zawierający edytor rozdzia\(/l\('ow i edytor nag\(/l\('owk\('ow
.SH "SZABLON LINII KOMEND"
.HP \w'\fBmkvtoolnix\-gui\fR\ 'u
\fBmkvtoolnix\-gui\fR [[plik\-konfiguracyjny\&.mtxcfg] | [plik\-źr\('od\(/lowy\&.xyz] | [\-\-edit\-chapters\ [plik\-rozdzia\(/l\('ow\&.xyz]] | [\-\-edit\-headers\ [plik\-matroski\&.mkv]]]
.SH "OPIS"
.PP
\fBmkvtoolnix-gui\fR(1)
jest opartym o
biblioteki Qt(TM)
graficznym interfejsem
dla
\fBmkvmerge\fR(1)
(w przysz\(/lości także dla
\fBmkvinfo\fR(1)
i
\fBmkvextract\fR(1))\&. Oferuje on \(/latwy dostęp do większości funkcji
\fBmkvmerge\fR(1)\&. Wszystkie ustawienia (np\&. pliki źr\('od\(/lowe, opcje ścieżek itp) mogą być zapisane i wczytane\&.
.PP
Użycie pliku konfiguracyjnego z rozszerzeniem
\&.mtxcfg
powoduje, że interfejs graficzny otwiera plik konfiguracyjny w odpowiednim narzędziu\&. Jakikolwiek plik z innym rozszerzeniem jest traktowany jako plik wejściowy, jest otwierany w edytorze rozdzia\(/l\('ow lub edytorze nag\(/l\('owk\('ow zależnie od ustawionego trybu\&. Tryb może być zmieniony opcją
\fB\-\-merge\fR,
\fB\-\-edit\-chapters\fR
lub
\fB\-\-edit\-headers\fR\&. Domyślny tryb to dodawanie plik\('ow celem muksowania\&.
.PP
Zauważ, że jeśli już program dzia\(/la, a będzie on jeszcze raz ponownie uruchomiony, to wszystkie nazwy plik\('ow w linii komend zostaną przejęte przez już dzia\(/lającą instancję programu\&.
.PP
\fB\-\-merge\fR
.RS 4
Wszystkie następujące nazwy plik\('ow zostaną dodane jako pliki wejściowe to obecnego zadania muksowania\&. To jest tryb domyślny\&.
.RE
.PP
\fB\-\-edit\-chapters\fR
.RS 4
Wszystkie następujące nazwy plik\('ow zostaną otwarte w edytorze rozdzia\(/l\('ow\&.
.RE
.PP
\fB\-\-edit\-headers\fR
.RS 4
Wszystkie następujące nazwy plik\('ow zostaną otwarte w edytorze nag\(/l\('owk\('ow\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Pokazuje informacje o sposobie użycia opcji i zamyka się\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Pokazuje informację o wersji i zamyka się\&.
.RE
.SH "ZOBACZ TAKŻE"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1)
.SH "STRONA WWW"
.PP
The latest version can always be found at
\m[blue]\fBthe MKVToolNix homepage\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Autor
.RE
.SH "PRZYPISY"
.IP " 1." 4
the MKVToolNix homepage
.RS 4
\%https://mkvtoolnix.download/
.RE
