'\" t
.\"     Title: mkvtoolnix-gui
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-12-27
.\"    Manual: Benutzerbefehle
.\"    Source: MKVToolNix 9.7.0
.\"  Language: German
.\"
.TH "MKVTOOLNIX\-GUI" "1" "2016\-12\-27" "MKVToolNix 9\&.7\&.0" "Benutzerbefehle"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mkvtoolnix-gui \- eine grafische Benutzeroberfl\(:ache f\(:ur \fBmkvmerge\fR(1) einschlie\(sslich eines Editors f\(:ur Kapitel und Kopfdaten
.SH "\(:UBERSICHT"
.HP \w'\fBmkvtoolnix\-gui\fR\ 'u
\fBmkvtoolnix\-gui\fR [[Konfigurationsdateiname\&.mtxcfg] | [Quelldatei\&.ext] | [\-\-edit\-chapters\ [Kapiteldatei\&.ext]] | [\-\-edit\-headers\ [Matroska\-Datei\&.mkv]]]
.SH "BESCHREIBUNG"
.PP
\fBmkvtoolnix-gui\fR(1)
ist eine auf
Qt(TM)
basierende graphische Benutzeroberfl\(:ache f\(:ur
\fBmkvmerge\fR(1)
(und wird sich dahin weiterentwickeln, auch
\fBmkvinfo\fR(1)
und
\fBmkvextract\fR(1)
abzudecken)\&. Es bietet einen einfachen Zugang zu den meisten Optionen von
\fBmkvmerge\fR(1)\&. Alle Einstellungen (z\&.B\&. Quelldateien, Spuroptionen etc\&.) k\(:onnen gespeichert und wiederhergestellt werden\&.
.PP
Das Auff\(:uhren von Konfigurationsdateinamen mit der Endung
\&.mtxcfg
sorgt daf\(:ur, dass die GUI diese Konfigurationsdateien im dazugeh\(:origen Werkzeug l\(:adt\&. Jeglicher anderer Dateiname wird abh\(:angig vom aktuellen Modus als Quelldatei zum Muxen hinzugef\(:ugt, im Kapiteleditor oder im Kopfdateneditor ge\(:offnet\&. Der aktuelle Modus kann mit
\fB\-\-merge\fR,
\fB\-\-edit\-chapters\fR
oder
\fB\-\-edit\-headers\fR
ge\(:andert werden\&. Der Standardmodus ist das Hinzuf\(:ugen zum Muxen\&.
.PP
Beachten Sie, dass, wenn bereits eine Instanz der Anwendung l\(:auft und eine zweite Instanz mit angegebenen Dateinamen gestartet wird, die Dateinamen in der bereits laufenden, ersten Instanz behandelt werden\&.
.PP
\fB\-\-merge\fR
.RS 4
Alle folgenden Dateinamen werden als Quelldateien zum aktuellen Mux\-Job hinzugef\(:ugt\&. Dies ist der Standardmodus\&.
.RE
.PP
\fB\-\-edit\-chapters\fR
.RS 4
Alle folgenden Dateinamen werden im Kapiteleditor ge\(:offnet\&.
.RE
.PP
\fB\-\-edit\-headers\fR
.RS 4
Alle folgenden Dateinamen werden im Kopfdateneditor ge\(:offnet\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
zeigt Benutzungsinformationen und beendet sich\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
zeigt Versionsinformationen und beendet sich\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1)
.SH "WWW"
.PP
Die neuste Version kann immer auf
\m[blue]\fBder MKVToolNix\-Homepage\fR\m[]\&\s-2\u[1]\d\s+2
gefunden werden\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Entwickler
.RE
.SH "FU\(ssNOTEN"
.IP " 1." 4
der MKVToolNix-Homepage
.RS 4
\%https://mkvtoolnix.download/
.RE
