'\" t
.\"     Title: mkvextract
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-07-14
.\"    Manual: Comandos de usuario
.\"    Source: MKVToolNix 9.3.1
.\"  Language: Spanish
.\"
.TH "MKVEXTRACT" "1" "2016\-07\-14" "MKVToolNix 9\&.3\&.1" "Comandos de usuario"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOMBRE"
mkvextract \- extrae las pistas de los archivos Matroska(TM) a otros archivos
.SH "SINOPSIS"
.HP \w'\fBmkvextract\fR\ 'u
\fBmkvextract\fR {modo} {nombre\-archivo} [opciones] [especificaciones\-extracci\('on]
.SH "DESCRIPCI\('ON"
.PP
Este programa extrae ciertas partes de un archivo
Matroska(TM)
a otros formatos de utilidad\&. El primer argumento,
\fBmodo\fR, le dice a
\fBmkvextract\fR(1)
qu\('e debe extraer\&. Actualmente es posible extraer
pistas,
etiquetas,
adjuntos,
cap\('itulos,
CUE sheets,
c\('odigos de tiempo (timecodes)
e
\('indices (cues)\&. El segundo argumento es el nombre del archivo origen\&. \('Este debe ser un archivo
Matroska(TM)\&. El resto de argumentos son opciones y especificaciones de extracci\('on; ambos son dependientes del modo seleccionado\&.
.SS "Opciones comunes"
.PP
Las siguientes opciones est\('an disponibles en todos los modos y s\('olo se describir\('an en esta secci\('on\&.
.PP
\fB\-f\fR, \fB\-\-parse\-fully\fR
.RS 4
Establece el modo de an\('alisis a \*(Aqcompleto\*(Aq\&. El modo predeterminado no analiza el archivo entero pues usa la b\('usqueda de elementos de metadatos para localizar los elementos necesarios de un archivo origen\&. En un 99% de todos los casos es suficiente\&. Pero para archivos que no contienen elementos de metadatos o que est\('an da\(~nados, el usuario deber\('ia usar este modo\&. Un an\('alisis completo de un archivo puede requerir bastantes minutos mientras que un an\('alisis r\('apido s\('olo lleva unos segundos\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fIconjunto\-caracteres\fR
.RS 4
Establece el conjunto de caracteres a convertir las cadenas de texto dadas desde la l\('inea de comandos\&. Por defecto, se ajusta al conjunto de caracteres dado por la configuraci\('on local del sistema\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIconjunto\-caracteres\fR
.RS 4
Establece el conjunto de caracteres para convertir las cadenas de texto que ser\('an usadas en el archivo de salida\&. Por defecto, se ajusta al conjunto de caracteres dado por la configuraci\('on local del sistema\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fInombre\-archivo\fR
.RS 4
Escribe todos los mensajes al archivo
\fInombre\-archivo\fR
en vez de en la consola\&. Aunque esto se puede hacer f\('acilmente con la opci\('on de redirecci\('on hay casos en los que es necesaria esta opci\('on: cuando el terminal reinterpreta la salida antes de escribirlo al archivo\&. El conjunto de caracteres establecido con
\fB\-\-output\-charset\fR
se respeta\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIc\('odigo\fR
.RS 4
Forces the translations for the language
\fIcode\fR
to be used (e\&.g\&. \*(Aqde_DE\*(Aq for the German translations)\&. Entering \*(Aqlist\*(Aq as the
\fIcode\fR
will cause the program to output a list of available translations\&.
.RE
.PP
\fB\-\-debug\fR \fItopic\fR
.RS 4
Habilita la depuraci\('on para una caracter\('istica concreta\&. Esta opci\('on s\('olo es \('util para desarrolladores\&.
.RE
.PP
\fB\-\-engage\fR \fIcaracter\('istica\fR
.RS 4
Habilita caracter\('isticas experimentales\&. Una lista de caracter\('isticas disponibles puede ser solicitada con la instrucci\('on
\fBmkvextract \-\-engage list\fR\&. Estas caracter\('isticas no est\('an indicadas para ser usadas en situaciones normales\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
Habilita el modo GUI\&. En este modo las l\('ineas especialmente formateadas pueden ser generadas para decirle a un control de la GUI lo que est\('a pasando\&. Estos mensajes se rigen bajo el formato \*(Aq#GUI#mensaje\*(Aq\&. El mensaje puede ser continuado por pares de valores/claves como en \*(Aq#GUI#mensaje#clave1=valor1#clave2=valor2\&...\*(Aq\&. Ni los mensajes ni las claves pueden ser traducidas y siempre se generan en ingl\('es\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Habilita el modo detallado y muestra todos los elementos
Matroska(TM)
importantes que pueden ser le\('idos\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Muestra informaci\('on de uso y sale\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Muestra la informaci\('on de la versi\('on y sale\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Comprueba online si hay nuevas versiones al descargar el archivo ubicado en la URL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Cuatro l\('ineas ser\('an generadas del tipo
clave=valor: la URL desde donde se obtuvo la informaci\('on (clave
version_check_url), la versi\('on actual (clave
running_version), la \('ultima versi\('on disponible (clave
available_version) y la URL de descarga (clave
download_url)\&.
.sp
Despu\('es el programa sale con un c\('odigo de salida 0 si ninguna versi\('on nueva est\('a disponible, con 1 si hay disponible una versi\('on m\('as actual y con 2 si ocurre alg\('un error (p\&.e\&. si la informaci\('on de la actualizaci\('on no puede ser obtenida)\&.
.sp
Esta opci\('on s\('olo est\('a disponible si el programa fue creado con compatibilidad para libcurl\&.
.RE
.PP
\fB@\fR\fIarchivo\-opciones\fR
.RS 4
Lee argumentos adicionales de la l\('inea de comandos desde el archivo
\fIarchivo\-opciones\fR\&. Las l\('ineas que tengan en el primer car\('acter una almohadilla (\*(Aq#\*(Aq) ser\('an tratados como comentarios y se ignorar\('an\&. Espacios en blanco al inicio y final de la l\('inea ser\('an descartados\&. Cada l\('inea debe contener exactamente una opci\('on\&.
.sp
Diversos caracteres pueden ser interpretados como de escape, p\&.e\&. si necesitas que una l\('inea, que comience con una almohadilla \*(Aq#\*(Aq, no sea interpretada como un comentario\&. Las normas se describen en
la secci\('on sobre caracteres de escape en texto\&.
.sp
La l\('inea de comandos \*(Aq\fBmkvextract tracks archivo\&.mkv \-\-raw 1:destino\&.raw\fR\*(Aq se puede convertir a un archivo de opciones del modo que se indica a continuaci\('on:
.sp
.if n \{\
.RS 4
.\}
.nf
# Extrae una pista del archivo\&.mkv
tracks
archivo\&.mkv
# Genera la pista del tipo raw
\-\-raw
1:destino\&.raw
.fi
.if n \{\
.RE
.\}
.RE
.SS "Modo de extracci\('on de pista"
.PP
Sintaxis:
\fBmkvextract \fR\fB\fBtracks\fR\fR\fB \fR\fB\fInombre\-archivo\fR\fR\fB \fR\fB[\fIopciones\fR]\fR\fB \fR\fB\fITID1:dest\-nombre1\fR\fR\fB \fR\fB[\fITID2:dest\-nombre2\fR \&.\&.\&.]\fR
.PP
Las siguientes opciones de l\('inea de comandos est\('an disponibles para cada pista en el modo de extracci\('on de pistas (\*(Aqtracks\*(Aq)\&. Tienen que aparecer delante de la especificaci\('on de pista a las que se deben aplicar (ver abajo)\&.
.PP
\fB\-c\fR \fIconjunto\-caracteres\fR
.RS 4
Establece el conjunto de caracteres para convertir el texto de la siguiente pista de subt\('itulo\&. S\('olo es v\('alido si el ID de la siguiente pista corresponde a un subt\('itulo\&. Por defecto usa UTF\-8\&.
.RE
.PP
\fB\-\-blockadd\fR \fInivel\fR
.RS 4
Conserva el BlockAdditions s\('olo hasta este nivel\&. Por defecto conserva todos los niveles\&. Esta opci\('on s\('olo afecta a ciertos tipos de c\('odecs como WAVPACK4\&.
.RE
.PP
\fB\-\-cuesheet\fR
.RS 4
Provoca que
\fBmkvextract\fR(1)
extraiga un
CUE
sheet desde la informaci\('on de cap\('itulos y etiquetas para la siguiente pista, a un archivo cuyo nombre es el del archivo de salida junto con la extensi\('on \*(Aq\&.cue\*(Aq\&.
.RE
.PP
\fB\-\-raw\fR
.RS 4
Extrae los datos en bruto (raw) a un archivo sin contenedor\&. A diferencia de
\fB\-\-fullraw\fR
esta opci\('on no provoca que el contenido del elemento
CodecPrivate
se escriba en el archivo\&. Este modo funciona s\('olo con todos los
CodecIDs, incluso con los que
\fBmkvextract\fR(1)
no sea compatible pero los archivos resultantes podr\('ian ser inutilizables\&.
.RE
.PP
\fB\-\-fullraw\fR
.RS 4
Extrae los datos en bruto (raw) a un archivo sin contenedor\&. El contenido del elemento
CodecPrivate
se escribir\('a en el primer archivo si la pista contiene ese elemento en el encabezado\&. Este modo funciona s\('olo con todos los
CodecIDs, incluso con los que
\fBmkvextract\fR(1)
no sea compatible pero los archivos resultantes podr\('ian ser inutilizables\&.
.RE
.PP
\fITID:nombre\-salida\fR
.RS 4
Provoca la extracci\('on de la pista con el ID
\fITID\fR
a un archivo con el
\fInombre\-salida\fR
si dicha pista existe en el archivo fuente\&. Esta opci\('on puede ser usada m\('ultiples veces\&. Los IDs de la pista son los mismos que muestra
\fBmkvmerge\fR(1)
con la opci\('on
\fB\-\-identify\fR\&.
.sp
Cada nombre de salida s\('olo debe ser usado una vez\&. La \('unica excepci\('on son las pistas RealAudio y RealVideo\&. Si usas el mismo nombre para pistas diferentes entonces estas pistas ser\('an almacenadas en el mismo archivo\&. Ejemplo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvextract tracks entrada\&.mkv 1:salida\-dos\-pistas\&.rm 2:salida\-dos\-pistas\&.rm
.fi
.if n \{\
.RE
.\}
.RE
.SS "Modo de extracci\('on de etiquetas"
.PP
Sintaxis:
\fBmkvextract \fR\fB\fBtags\fR\fR\fB \fR\fB\fInombre\-archivo\fR\fR\fB \fR\fB[\fIopciones\fR]\fR
.PP
Las etiquetas extra\('idas se escriben a la consola a menos que la salida sea redirigida (vea la secci\('on a cerca de
redirecci\('on de salida
para m\('as detalles)\&.
.SS "Modo de extracci\('on de adjuntos"
.PP
Sintaxis:
\fBmkvextract \fR\fB\fBattachments\fR\fR\fB \fR\fB\fInombre\-archivo\fR\fR\fB \fR\fB[\fIopciones\fR]\fR\fB \fR\fB\fIAID1:salida1\fR\fR\fB \fR\fB[\fIAID2:salida2\fR \&.\&.\&.]\fR
.PP
\fIAID\fR:\fInombre\-salida\fR
.RS 4
Provoca la extracci\('on del adjunto con el ID
\fIAID\fR
a un archivo con el
\fInombre\-salida\fR
si dicho adjunto existe en el archivo fuente\&. Si el
\fInombre\-salida\fR
se deja vac\('io entonces ser\('a usado el nombre del adjunto en el archivo
Matroska(TM)\&. Esta opci\('on puede ser usada m\('ultiples veces\&. Los IDs de los adjuntos son los mismos que muestra
\fBmkvmerge\fR(1)
con la opci\('on
\fB\-\-identify\fR\&.
.RE
.SS "Modo de extracci\('on de capitulos"
.PP
Sintaxis:
\fBmkvextract \fR\fB\fBchapters\fR\fR\fB \fR\fB\fInombre\-archivo\fR\fR\fB \fR\fB[\fIopciones\fR]\fR
.PP
\fB\-s\fR, \fB\-\-simple\fR
.RS 4
Exporta la informaci\('on de cap\('itulos en un formato simple usado en las herramientas de
OGM
(CAPITULO01=\&.\&.\&., CAPITULO01NOMBRE=\&.\&.\&.)\&. En este modo alguna informaci\('on ser\('a descartada\&. Por defecto la salida de los cap\('itulos est\('an en formato XML\&.
.RE
.PP
\fB\-\-simple\-language\fR \fIidioma\fR
.RS 4
Si se habilita el formato simple entonces
\fBmkvextract\fR(1)
s\('olo generar\('a una \('unica entrada de cada cap\('itulo atom encontrado incluso si un cap\('itulo atom contiene m\('as de un nombre de cap\('itulos\&. Por defecto
\fBmkvextract\fR(1)
usar\('a el primer nombre de cap\('itulos que encuentre para cada atom, independientemente de su idioma\&.
.sp
Usar esta opci\('on permite al usuario determinar que nombres de cap\('itulos se generan si los atoms contienen m\('as de un nombre de cap\('itulos\&. El par\('ametro
\fIlanguage\fR
debe ser un c\('odigo ISO 639\-1 o ISO 639\-2\&.
.RE
.PP
Los cap\('itulos extra\('idos se escriben en la consola a menos que la salida sea redirigida (vea la secci\('on sobre
redirecci\('on de salida
para m\('as detalles)\&.
.SS "Modo de extracci\('on de Cue sheet"
.PP
Sintaxis:
\fBmkvextract \fR\fB\fBcuesheet\fR\fR\fB \fR\fB\fInombre\-archivo\fR\fR\fB \fR\fB[\fIopciones\fR]\fR
.PP
El cue sheet extra\('ido se escriben en la consola a menos que la salida sea redirigida (vea la secci\('on sobre
redirecci\('on de salida
para m\('as detalles)\&.
.SS "Modo de extracci\('on de c\('odigos de tiempo"
.PP
Sintaxis:
\fBmkvextract \fR\fB\fBtimecodes_v2\fR\fR\fB \fR\fB\fInombre\-archivo\fR\fR\fB \fR\fB[\fIopciones\fR]\fR\fB \fR\fB\fITID1:nombrearchivo\-dest1\fR\fR\fB \fR\fB[\fITID2:nombrearchivo\-dest2\fR \&.\&.\&.]\fR
.PP
Los c\('odigos de tiempo se escriben en la consola a menos que la salida sea redirigida (vea la secci\('on sobre
redirecci\('on de salida
para m\('as detalles)\&.
.PP
\fITID:nombre\-salida\fR
.RS 4
Provoca la extracci\('on de los timecodes para la pista con el ID
\fITID\fR
a un archivo con el
\fInombre\-salida\fR
si dicha pista existe en el archivo origen\&. Esta opci\('on puede ser usada m\('ultiples veces\&. Los IDs de la pista son los mismos que muestra
\fBmkvmerge\fR(1)
con la opci\('on
\fB\-\-identify\fR\&.
.sp
Ejemplo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvextract timecodes_v2 entrada\&.mkv 1:tc\-pista1\&.txt 2:tc\-pista2\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SS "Modo de extracci\('on de Cues"
.PP
Sintaxis:
\fBmkvextract \fR\fB\fBcues\fR\fR\fB \fR\fB\fInombre\-archivo\fR\fR\fB \fR\fB[\fIopciones\fR]\fR\fB \fR\fB\fITID1:nombrearchivo\-dest1\fR\fR\fB \fR\fB[\fITID2:nombrearchivo\-dest2\fR \&.\&.\&.]\fR
.PP
\fITID:nombrearchivo\-dest\fR
.RS 4
Provoca la extracci\('on de los cues (\('indices) para la pista con el ID
\fITID\fR
a un archivo con el
\fInombre\-salida\fR
si dicha pista existe en el archivo origen\&. Esta opci\('on puede ser usada m\('ultiples veces\&. Los IDs de la pista son los mismos que muestra
\fBmkvmerge\fR(1)
con la opci\('on
\fB\-\-identify\fR
y no los n\('umeros contenidos en el elemento
CueTrack\&.
.RE
.PP
El formato de salida es un simple formato de texto: una l\('inea por cada elemento
CuePoint
con
clave=valor\&. Si un elemento opcional no existe en un
CuePoint
(p\&.e\&.
CueDuration) entonces un gui\('on ser\('a devuelto como valor\&.
.PP
Ejemplo:
.sp
.if n \{\
.RS 4
.\}
.nf
timecode=00:00:13\&.305000000 duration=\- cluster_position=757741 relative_position=11
.fi
.if n \{\
.RE
.\}
.PP
Las claves posibles son:
.PP
timecode
.RS 4
El c\('odigo de tiempo del cue point con precisi\('on de nanosegundos\&. El formato es
HH:MM:SS\&.nnnnnnnnn\&. Este elemento siempre se establece\&.
.RE
.PP
duration
.RS 4
La duraci\('on del cue point con precisi\('on de nanosegundos\&. El formato es
HH:MM:SS\&.nnnnnnnnn\&.
.RE
.PP
cluster_position
.RS 4
La posici\('on absoluta en bytes dentro del archivo
Matroska(TM)
en d\('onde comienza el cl\('uster que contiene el elemento de referencia\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNota\fR
.ps -1
.br
Dentro del archivo
Matroska(TM)
el
CueClusterPosition
se refiere a la compensaci\('on (offset) de los datos de inicio del segmento\&. El valor de salida es dado por el modo de extracci\('on de cue de
\fBmkvextract\fR(1), sin embargo ya contiene esa compensaci\('on y que es absoluta a partir del inicio del archivo\&.
.sp .5v
.RE
.RE
.PP
relative_position
.RS 4
La posici\('on relativa en bytes dentro del cl\('uster en donde el elemento
BlockGroup
o
SimpleBlock
es el cue point que se refiere al inicio\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNota\fR
.ps -1
.br
Dentro del archivo
Matroska(TM)
el
CueRelativePosition
se refiere a la compensaci\('on de los datos de inicio del cl\('uster\&. El valor de salida es dado por el modo de extracci\('on de cue de
\fBmkvextract\fR(1), sin embargo es relativo al ID del cl\('uster\&. La posici\('on absoluta dentro del archivo puede ser calculada por a\(~nadir
cluster_position
y
relative_position\&.
.sp .5v
.RE
.RE
.PP
Ejemplo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvextract cues entrada\&.mkv 1:cues\-pista1\&.txt 2:cues\-pista2\&.txt
.fi
.if n \{\
.RE
.\}
.SH "REDIRECCI\('ON DE SALIDA"
.PP
Varios modos de extracci\('on provocan que
\fBmkvextract\fR(1)
escriba la informaci\('on extra\('ida a la consola\&. Por lo general, hay dos maneras de escribir esta informaci\('on a un archivo: uno proporcionado por el shell y otro por
\fBmkvextract\fR(1)\&.
.PP
El mecanismo de redirecci\('on de orden interna del shell se utiliza a\(~nadiendo \*(Aq> nombresalida\&.ext\*(Aq a la l\('inea de comandos\&. Ejemplo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvextract tags archivo\&.mkv > etiquetas\&.xml
.fi
.if n \{\
.RE
.\}
.PP
La redirecci\('on de
\fBmkvextract\fR(1)
es invocada con la opci\('on
\fB\-\-redirect\-output\fR\&. Ejemplo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvextract tags archivo\&.mkv \-\-redirect\-output etiquetas\&.xml
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNota\fR
.ps -1
.br
.PP
En Windows es posible que necesite usar la opci\('on
\fB\-\-redirect\-output\fR
porque
\fBcmd\&.exe\fR
a veces interpreta los caracteres especiales antes de que se escriban en el archivo de salida provocando una salida incorrecta\&.
.sp .5v
.RE
.SH "CONVERSI\('ON DE ARCHIVOS DE TEXTO Y CONJUNTO DE CARACTERES"
.PP
Para una discusi\('on en profundidad sobre como la suite de MkvToolNix manipula las conversiones de caracteres, la codificaci\('on entrada/salida y la codificaci\('on de la l\('inea de comandos y consola, por favor consulte la secci\('on llamada de igual manera en la pagina del manual para
\fBmkvmerge\fR(1)\&.
.SH "FORMATOS DE SALIDA"
.PP
La decisi\('on sobre el tipo de formato se basa en el tipo de pista y no en la extensi\('on usada en el nombre del archivo de salida\&. Por ahora, los siguientes tipos de pista son compatibles:
.PP
V_MPEG4/ISO/AVC
.RS 4
Las pistas de video
H\&.264
/
AVC
se escriben en secuencias elementales
H\&.264
que pueden ser procesadas posteriormente, por ejemplo con
MP4Box(TM)
del paquete
GPAC(TM)\&.
.RE
.PP
V_MS/VFW/FOURCC
.RS 4
Las pistas de video con
FPS
fijadas con este
CodecID
se escriben en los archivos
AVI\&.
.RE
.PP
V_REAL/*
.RS 4
Las pistas
RealVideo(TM)
se escriben en archivos
RealMedia(TM)\&.
.RE
.PP
V_THEORA
.RS 4
Las secuencias
Theora(TM)
se escribir\('an en un contenedor
Ogg(TM)\&.
.RE
.PP
V_VP8, V_VP9
.RS 4
Las pistas
VP8
/
VP9
se escriben en archivos
IVF\&.
.RE
.PP
A_MPEG/L2
.RS 4
Las secuencias de audio MPEG\-1 Layer II ser\('an extra\('idas a archivos en bruto
MP2\&.
.RE
.PP
A_MPEG/L3, A_AC3
.RS 4
Estos ser\('an extra\('idos a archivos en bruto
MP3
y
AC\-3\&.
.RE
.PP
A_PCM/INT/LIT
.RS 4
La informaci\('on en bruto
PCM
se escribir\('a en un archivo
WAV\&.
.RE
.PP
A_AAC/MPEG2/*, A_AAC/MPEG4/*, A_AAC
.RS 4
Todos los archivos
AAC
se escribir\('an en un archivo
AAC
con encabezados
ADTS
antes de cada paquete\&. Los encabezados
ADTS
no contendr\('an el obsoleto campo de \('enfasis\&.
.RE
.PP
A_VORBIS
.RS 4
El audio Vorbis se escribir\('a en un archivo
OggVorbis(TM)\&.
.RE
.PP
A_REAL/*
.RS 4
Las pistas
RealAudio(TM)
se escriben en archivos
RealMedia(TM)\&.
.RE
.PP
A_TTA1
.RS 4
Las pistas
TrueAudio(TM)
se escriben en archivos
TTA\&. Por favor, tenga en cuenta que debido a la precisi\('on limitada de los c\('odigos de tiempo de
Matroska(TM), el encabezado del archivo extra\('ido ser\('a diferente con respecto a dos campos:
\fIdata_length\fR
(el n\('umero total de muestras en el archivo) y el
CRC\&.
.RE
.PP
A_ALAC
.RS 4
Las pistas
ALAC
se escriben en archivos
CAF\&.
.RE
.PP
A_FLAC
.RS 4
Las pistas
FLAC
se escriben en archivos en bruto
FLAC\&.
.RE
.PP
A_WAVPACK4
.RS 4
Las pistas
WavPack(TM)
se escriben en archivos
WV\&.
.RE
.PP
A_OPUS
.RS 4
Las pistas
Opus(TM)
se escribe en archivos
OggOpus(TM)\&.
.RE
.PP
S_TEXT/UTF8
.RS 4
Los subt\('itulos de texto simple se escribir\('an como archivos
SRT\&.
.RE
.PP
S_TEXT/SSA, S_TEXT/ASS
.RS 4
Los subt\('itulos de texto
SSA
y
ASS
se escribir\('an como archivos
SSA/ASS, respectivamente\&.
.RE
.PP
S_KATE
.RS 4
Las secuencias
Kate(TM)
se escribir\('an dentro de un contenedor
Ogg(TM)\&.
.RE
.PP
S_VOBSUB
.RS 4
Los subt\('itulos
VobSub(TM)
se escribir\('an como archivos
SUB
junto con sus respectivos archivos de \('indice
IDX\&.
.RE
.PP
S_TEXT/USF
.RS 4
Los subt\('itulos de texto
USF
se escribir\('an como archivos
USF\&.
.RE
.PP
S_HDMV/PGS
.RS 4
Los subt\('itulos
PGS
se escribir\('an como archivos
SUP\&.
.RE
.PP
Tags
.RS 4
Las etiquetas se convierten a formato
XML\&. Este formato es el mismo que
\fBmkvmerge\fR(1)
admite para leer etiquetas\&.
.RE
.PP
Attachments
.RS 4
Los adjuntos se escriben en el archivo de salida tal y como est\('an\&. No se realiza ning\('un tipo de conversi\('on\&.
.RE
.PP
Chapters
.RS 4
Los cap\('itulos se convierten a formato
XML\&. Este formato es el mismo que
\fBmkvmerge\fR(1)
admite para leer cap\('itulos\&. Alternativamente, una versi\('on reducida puede ser generada a un simple formato de estilo
OGM\&.
.RE
.PP
Timecodes
.RS 4
Los c\('odigos de tiempo se ordenan de principio a fin, y entonces se genera un archivo compatible con el formato timecode v2 preparado para ser proporcionado a
\fBmkvmerge\fR(1)\&. La extracci\('on a otros formatos (v1, v3 y v4) no son compatibles\&.
.RE
.SH "C\('ODIGOS DE SALIDA"
.PP
\fBmkvextract\fR(1)
finaliza con uno de estos tres c\('odigos de salida:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- Este c\('odigo de salida significa que la extracci\('on se ha realizado correctamente\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- En este caso
\fBmkvextract\fR(1)
genera una salida con al menos una advertencia, pero la extracci\('on continu\('o\&. Una advertencia es prefijada con el texto \*(AqAdvertencia:\*(Aq\&. Dependiendo de los fallos involucrados los archivos creados ser\('an correctos o no\&. El usuario es instado a que revise tanto las advertencias como los archivos creados\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- Este c\('odigo de salida es usado despu\('es de que ocurra un error\&.
\fBmkvextract\fR(1)
aborta el proceso justo despu\('es de mostrar el mensaje de error\&. El rango de los mensajes de error va desde los argumentos de la l\('inea de comandos, por delante de los errores de lectura/escritura, hasta los archivos err\('oneos\&.
.RE
.SH "CARACTERES ESPECIALES DE ESCAPE EN EL TEXTO"
.PP
Hay pocos sitios en los que los caracteres especiales en el texto puedan o deban ser escapados\&. Las reglas del escape son simples: cada car\('acter que necesite ser escapado es reemplazado con una barra invertida seguida de otro car\('acter\&.
.PP
Las reglas son: \*(Aq \*(Aq (un espacio) se convierte a \*(Aq\es\*(Aq, \*(Aq"\*(Aq (doble comillas) ser\('ia \*(Aq\e2\*(Aq, \*(Aq:\*(Aq se convierte a \*(Aq\ec\*(Aq, \*(Aq#\*(Aq se reemplazada como \*(Aq\eh\*(Aq y \*(Aq\e\*(Aq (una barra invertida) se expresar\('ia como \*(Aq\e\e\*(Aq\&.
.SH "VARIABLES DE ENTORNO"
.PP
\fBmkvextract\fR(1)
usa las variables predefinidas que se determinan en la configuraci\('on local del sistema (p\&.e\&.
\fILANG\fR
y la familia
\fILC_*\fR)\&. Variables adicionales:
.PP
\fIMKVEXTRACT_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR y su forma abreviada\fIMTX_DEBUG\fR
.RS 4
El contenido se trata como si se hubiese pasado a trav\('es de la opci\('on
\fB\-\-debug\fR\&.
.RE
.PP
\fIMKVEXTRACT_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR y su forma abreviada \fIMTX_ENGAGE\fR
.RS 4
El contenido se trata como si se hubiese pasado a trav\('es de la opci\('on
\fB\-\-engage\fR\&.
.RE
.PP
\fIMKVEXTRACT_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR y su forma abreviada \fIMTX_OPTIONS\fR
.RS 4
El contenido es dividido en espacios en blanco\&. Las cadenas de texto parciales resultantes son tratadas como si hubiesen sido pasadas como opciones a la l\('inea de comandos\&. Si necesitas pasar caracteres especiales (p\&.e\&. espacios) entonces tienes que escaparlos (vea
la secci\('on caracteres especiales de escape en el texto)\&.
.RE
.SH "VEA TAMBI\('EN"
.PP
\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
La \('ultima versi\('on se puede encontrar siempre en
\m[blue]\fBla p\('agina de MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desarrollador
.RE
.SH "NOTAS"
.IP " 1." 4
la p\('agina de MKVToolNix
.RS 4
\%https://mkvtoolnix.download/
.RE
