'\" t
.\"     Title: mkvinfo
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-11-29
.\"    Manual: Comandos de usuario
.\"    Source: MKVToolNix 9.6.0
.\"  Language: Spanish
.\"
.TH "MKVINFO" "1" "2016\-11\-29" "MKVToolNix 9\&.6\&.0" "Comandos de usuario"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOMBRE"
mkvinfo \- Imprime la informaci\('on respecto a los elementos de los archivos Matroska(TM)
.SH "SINOPSIS"
.HP \w'\fBmkvinfo\fR\ 'u
\fBmkvinfo\fR [opciones] {nombre\-archivo}
.SH "DESCRIPCI\('ON"
.PP
Este programa muestra una lista de todos los elementos contenidos en un archivo
Matroska(TM)\&. La salida puede ser limitada a una lista de pistas en un archivo incluyendo informaci\('on acerca de los c\('odecs usados\&.
.PP
\fB\-g\fR, \fB\-\-gui\fR
.RS 4
Inicia la
GUI\&. Esta opci\('on s\('olo est\('a disponible si mkvinfo fue compilado con compatibilidad para
GUI\&.
.RE
.PP
\fB\-c\fR, \fB\-\-checksums\fR
.RS 4
Calcula y muestra el checksum
\fBAdler32\fR
para cada fotograma\&. \('Util s\('olo para depuraci\('on\&.
.RE
.PP
\fB\-s\fR, \fB\-\-summary\fR
.RS 4
S\('olo muestra un breve resumen de lo que
\fBmkvinfo\fR(1)
encuentra y no de cada elemento\&.
.RE
.PP
\fB\-t\fR, \fB\-\-track\-info\fR
.RS 4
Muestra la estad\('istica de cada pista en el modo detallado\&. Tambi\('en establece la verbosidad a 1 si antes era 0\&.
.RE
.PP
\fB\-x\fR, \fB\-\-hexdump\fR
.RS 4
Muestra los primeros 16 bytes de cada fotograma como un dump (volcado) hexadecimal\&.
.RE
.PP
\fB\-X\fR, \fB\-\-full\-hexdump\fR
.RS 4
Muestra todos los bytes de cada fotograma como un dump (volcado) hexadecimal\&.
.RE
.PP
\fB\-z\fR, \fB\-\-size\fR
.RS 4
Muestra el tama\(~no de cada elemento incluyendo su encabezado\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fIconjunto\-caracteres\fR
.RS 4
Establece el conjunto de caracteres a convertir las cadenas de texto dadas desde la l\('inea de comandos\&. Por defecto, se ajusta al conjunto de caracteres dado por la configuraci\('on local del sistema\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIconjunto\-caracteres\fR
.RS 4
Establece el conjunto de caracteres para convertir las cadenas de texto que ser\('an usadas en el archivo de salida\&. Por defecto, se ajusta al conjunto de caracteres dado por la configuraci\('on local del sistema\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fInombre\-archivo\fR
.RS 4
Escribe todos los mensajes al archivo
\fInombre\-archivo\fR
en vez de en la consola\&. Mientras esto puede ser realizado f\('acilmente con una redirecci\('on de salida hay casos en el que esta opci\('on es necesaria: cuando el terminal reinterpreta la salida antes la escribe a un archivo\&. El conjunto de caracteres establecidos con
\fB\-\-output\-charset\fR
se respeta\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIc\('odigo\fR
.RS 4
Fuerza la traducci\('on al
\fIc\('odigo\fR
de idioma que ser\('a usado (p\&.e\&. \*(Aqde_DE\*(Aq para la traducci\('on al Alem\('an)\&. Introduciendo \*(Aqlist\*(Aq como
\fIc\('odigo\fR
provocar\('a que el programa muestre una lista de las traducciones disponibles\&.
.RE
.PP
\fB\-\-debug\fR \fItopic\fR
.RS 4
Habilita la depuraci\('on para una caracter\('istica concreta\&. Esta opci\('on s\('olo es \('util para desarrolladores\&.
.RE
.PP
\fB\-\-engage\fR \fIcaracter\('istica\fR
.RS 4
Activa caracter\('isticas experimentales\&. Una lista de caracter\('isticas disponibles pueden ser solicitada con
\fBmkvinfo \-\-engage list\fR\&. Estas caracter\('isticas no est\('an destinadas para ser utilizadas en situaciones normales\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
Habilita el modo GUI\&. En este modo las l\('ineas especialmente formateadas pueden ser generadas para decirle a un control de la GUI lo que est\('a pasando\&. Estos mensajes se rigen bajo el formato \*(Aq#GUI#mensaje\*(Aq\&. El mensaje puede ser continuado por pares de valores/claves como en \*(Aq#GUI#mensaje#clave1=valor1#clave2=valor2\&...\*(Aq\&. Ni los mensajes ni las claves pueden ser traducidas y siempre se generan en ingl\('es\&.
.sp
Este comando no tiene nada que ver con el par\('ametro
\fB\-\-gui\fR
el cual provoca que mkvinfo muestre su propia GUI\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Ser m\('as detallado\&. Mire la secci\('on acerca de
niveles de detalle
para una descripci\('on de que informaci\('on ser\('a generada en cada nivel\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Muestra informaci\('on de uso y sale\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Muestra la informaci\('on de la versi\('on y sale\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Comprueba online si hay nuevas versiones al descargar el archivo ubicado en la URL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Cuatro l\('ineas ser\('an generadas del tipo
clave=valor: la URL desde donde se obtuvo la informaci\('on (clave
version_check_url), la versi\('on actual (clave
running_version), la \('ultima versi\('on disponible (clave
available_version) y la URL de descarga (clave
download_url)\&.
.sp
Despu\('es el programa sale con un c\('odigo de salida 0 si ninguna versi\('on nueva est\('a disponible, con 1 si hay disponible una versi\('on m\('as actual y con 2 si ocurre alg\('un error (p\&.e\&. si la informaci\('on de la actualizaci\('on no puede ser obtenida)\&.
.sp
Esta opci\('on s\('olo est\('a disponible si el programa fue creado con compatibilidad para libcurl\&.
.RE
.PP
\fB@\fR\fIarchivo\-opciones\fR
.RS 4
Lee argumentos adicionales de la l\('inea de comandos desde el archivo
\fIarchivo\-opciones\fR\&. Las l\('ineas que tengan en el primer car\('acter una almohadilla (\*(Aq#\*(Aq) ser\('an tratados como comentarios y se ignorar\('an\&. Espacios en blanco al inicio y final de la l\('inea ser\('an descartados\&. Cada l\('inea debe contener exactamente una opci\('on\&.
.sp
Diversos caracteres pueden ser interpretados como de escape, p\&.e\&. si necesitas que una l\('inea, que comience con una almohadilla \*(Aq#\*(Aq, no sea interpretada como un comentario\&. Las normas est\('an descritas en
la secci\('on sobre caracteres de escape en texto\&.
.sp
La l\('inea de comandos \*(Aq\fBmkvinfo \-v \-v entrada\&.mkv \-\-redirect\-output info\&.txt\fR\*(Aq podr\('ia ser convertida en el siguiente archivo de opciones:
.sp
.if n \{\
.RS 4
.\}
.nf
# Ser m\('as detallado
\-v
\-v
# Analiza entrada\&.mkv
entrada\&.mkv
# y escribe la salida en info\&.txt
\-\-redirect\-output
info\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SH "NIVELES DE DETALLE"
.PP
La opci\('on
\fB\-v\fR
puede ser usada para incrementar el nivel de verbosidad
\fBmkvinfo\fR(1)
e imprimir m\('as informaci\('on sobre al archivo actual\&.
.PP
En el nivel 0
\fBmkvinfo\fR(1)
imprimir\('a s\('olo los encabezados de la pista que encuentra y sus tipos\&.
\fBmkvinfo\fR(1)
saldr\('a tan pronto como los encabezados sean analizados completamente (m\('as t\('ecnico: tan pronto como el primer cl\('uster sea encontrado)\&. En este nivel, la b\('usqueda de entradas del encabezado y los \('indices no ser\('a mostrados \-\- incluso si ellos est\('an localizados al principio de la informaci\('on de la pista\&.
.PP
En el nivel 1
\fBmkvinfo\fR(1)
tambi\('en imprimir\('a todos los elementos encontrados
Matroska(TM)
en todo el archivo al buscar las entradas del encabezado y del \('indice\&. Si el modo resumen est\('a habilitado entonces
\fBmkvinfo\fR(1)
tambi\('en generar\('a la posici\('on del fotograma\&.
.PP
En el nivel 2
\fBmkvinfo\fR(1)
tambi\('en imprimir\('a las entradas buscadas del encabezado, las del \('indice y la posici\('on en el archivo en el que cada elemento
Matroska(TM)
pudo ser encontrado\&.
.PP
En el nivel 3 y superiores
\fBmkvinfo\fR(1)
imprimir\('a algo de informaci\('on que no est\('a directamente relacionada al elemento
Matroska(TM)\&. El resto de elementos s\('olo imprimir\('a datos sobre los elementos que fueron encontrados\&. El nivel 3 a\(~nade meta informaci\('on para facilitar la depuraci\('on (leer: est\('a indicado para desarrolladores)\&. Todas las l\('ineas escritas por el nivel 3 est\('an cerradas entre corchetes para facilitar el filtrado\&.
.SH "CONVERSI\('ON DE ARCHIVOS DE TEXTO Y CONJUNTO DE CARACTERES"
.PP
Para una discusi\('on en profundidad sobre como la suite de MkvToolNix manipula las conversiones de caracteres, la codificaci\('on entrada/salida y la codificaci\('on de la l\('inea de comandos y consola, por favor consulte la secci\('on llamada de igual manera en la pagina del manual para
\fBmkvmerge\fR(1)\&.
.SH "C\('ODIGOS DE SALIDA"
.PP
\fBmkvinfo\fR(1)
finaliza con uno de estos tres c\('odigos de salida:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- Este c\('odigo de salida significa que la extracci\('on se ha realizado correctamente\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- En este caso
\fBmkvinfo\fR(1)
genera una salida con al menos una advertencia, pero la extracci\('on continu\('o\&. Una advertencia es prefijada con el texto \*(AqAdvertencia:\*(Aq\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- Este c\('odigo de salida es usado despu\('es de que ocurra un error\&.
\fBmkvinfo\fR(1)
aborta el proceso justo despu\('es de mostrar el mensaje de error\&. El rango de los mensajes de error va desde los argumentos de la l\('inea de comandos, por delante de los errores de lectura/escritura, hasta los archivos err\('oneos\&.
.RE
.SH "CARACTERES ESPECIALES DE ESCAPE EN EL TEXTO"
.PP
Hay pocos sitios en los que los caracteres especiales en el texto puedan o deban ser escapados\&. Las reglas del escape son simples: cada car\('acter que necesite ser escapado es reemplazado con una barra invertida seguida de otro car\('acter\&.
.PP
Las reglas son: \*(Aq \*(Aq (un espacio) se convierte a \*(Aq\es\*(Aq, \*(Aq"\*(Aq (doble comillas) ser\('ia \*(Aq\e2\*(Aq, \*(Aq:\*(Aq se convierte a \*(Aq\ec\*(Aq, \*(Aq#\*(Aq se reemplazada como \*(Aq\eh\*(Aq y \*(Aq\e\*(Aq (una barra invertida) se expresar\('ia como \*(Aq\e\e\*(Aq\&.
.SH "VARIABLES DE ENTORNO"
.PP
\fBmkvinfo\fR(1)
usa las variables predefinidas que se determinan en la configuraci\('on local del sistema (p\&.e\&.
\fILANG\fR
y la familia
\fILC_*\fR)\&. Variables adicionales:
.PP
\fIMKVINFO_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR y su forma abreviada \fIMTX_DEBUG\fR
.RS 4
El contenido se trata como si se hubiese pasado a trav\('es de la opci\('on
\fB\-\-debug\fR\&.
.RE
.PP
\fIMKVINFO_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR y su forma abreviada \fIMTX_ENGAGE\fR
.RS 4
El contenido se trata como si se hubiese pasado a trav\('es de la opci\('on
\fB\-\-engage\fR\&.
.RE
.PP
\fIMKVINFO_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR y su forma abreviada \fIMTX_OPTIONS\fR
.RS 4
El contenido es dividido en espacios en blanco\&. Las cadenas de texto parciales resultantes son tratadas como si hubiesen sido pasadas como opciones a la l\('inea de comandos\&. Si necesitas pasar caracteres especiales (p\&.e\&. espacios) entonces tienes que escaparlos (mire
la secci\('on caracteres especiales de escape en el texto)\&.
.RE
.SH "VEA TAMBI\('EN"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvpropedit\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
La \('ultima versi\('on se puede encontrar siempre en
\m[blue]\fBla p\('agina de MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desarrollador
.RE
.SH "NOTAS"
.IP " 1." 4
la p\('agina de MKVToolNix
.RS 4
\%https://mkvtoolnix.download/
.RE
