'\" t
.\"     Title: mkvpropedit
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-07-13
.\"    Manual: Comandos de usuario
.\"    Source: MKVToolNix 9.3.0
.\"  Language: Spanish
.\"
.TH "MKVPROPEDIT" "1" "2016\-07\-13" "MKVToolNix 9\&.3\&.0" "Comandos de usuario"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOMBRE"
mkvpropedit \- Modifica las propiedades existentes en archivos Matroska(TM) sin multiplexar
.SH "SINOPSIS"
.HP \w'\fBmkvpropedit\fR\ 'u
\fBmkvpropedit\fR [opciones] {archivo\-origen} {acciones}
.SH "DESCRIPCI\('ON"
.PP
Este programa analiza un archivo
Matroska(TM)
y modifica alguna de sus propiedades\&. Entonces escribe estas modificaciones en el archivo existente\&. Entre las propiedades que pueden ser modificadas est\('an los elementos de la informaci\('on del segmento (p\&.e\&. el t\('itulo) y los encabezados de pista (p\&.e\&. el c\('odigo del idioma, el flag de \*(Aqpista predefinida\*(Aq o el nombre)\&.
.PP
Opciones:
.PP
\fB\-l\fR, \fB\-\-list\-property\-names\fR
.RS 4
Enumera todos los conocidos y editables nombres, su tipo (texto, entero, booleano, etc\&.\&.\&.) y una peque\(~na descripci\('on\&. El programa despu\('es sale\&. Por lo tanto, el par\('ametro
\fInombre\-archivo\fR
no tiene que ser suministrado\&.
.RE
.PP
\fB\-p\fR, \fB\-\-parse\-mode\fR \fImodo\fR
.RS 4
Establece el modo de an\('alisis\&. El par\('ametro \*(Aq\fImodo\fR\*(Aq puede ser \*(Aqfast\*(Aq (que es el predeterminado) o \*(Aqfull\*(Aq\&. El modo \*(Aqfast\*(Aq no analiza el archivo entero pero usa los elementos de meta b\('usqueda para localizar los elementos necesarios del archivo original\&. En el 99% de los casos es suficiente\&. Sin embargo, para archivos que no contienen elementos de meta b\('usqueda o que est\('an da\(~nados, el usuario deber\('ia de usar el modo de an\('alisis \*(Aqfull\*(Aq\&. Un an\('alisis completo de un archivo puede llevar bastantes minutos mientras que un an\('alisis r\('apido s\('olo lleva unos segundos\&.
.RE
.PP
Acciones que tienen que ver con las propiedades de informaci\('on de la pista y segmento:
.PP
\fB\-e\fR, \fB\-\-edit\fR \fIselector\fR
.RS 4
Establece la secci\('on del archivo
Matroska(TM)
(informaci\('on del segmento o ciertos encabezados de pista) sobre la que se centrar\('an todas las acciones:
add,
set
y
delete\&. Esta opci\('on puede ser m\('ultiples veces de manera que puede ser modificado m\('as de un elemento a la vez\&.
.sp
Por defecto,
\fBmkvpropedit\fR(1)
editar\('a la secci\('on de informaci\('on del segmento\&.
.sp
Mire la secci\('on sobre
selectores de edici\('on
para una completa descripci\('on de la sintaxis\&.
.RE
.PP
\fB\-a\fR, \fB\-\-add\fR \fIname\fR=\fIvalor\fR
.RS 4
A\(~nade una propiedad
\fIname\fR
con el contenido de
\fIvalor\fR\&. Esta propiedad ser\('a a\(~nadida incluso si dicha propiedad ya existe\&. Tenga en cuenta que la mayor\('ia de propiedades son \('unicas y s\('olo existe una instancia de ellas\&.
.RE
.PP
\fB\-s\fR, \fB\-\-set\fR \fIname\fR=\fIvalor\fR
.RS 4
Establece todas las instancias de la propiedad
\fIname\fR
con el contenido
\fIvalor\fR\&. Si no existe dicha propiedad entonces ser\('a a\(~nadida\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR \fInombre\fR
.RS 4
Borra todas las instancias de la propiedad
\fIname\fR\&. Tenga en cuenta que algunas propiedades son necesarias y no pueden ser eliminadas\&.
.RE
.PP
Acciones que tienen que ver con las etiquetas y cap\('itulos:
.PP
\fB\-t\fR, \fB\-\-tags\fR \fIselector\fR:\fInombre\fR
.RS 4
Reemplaza o a\(~nade las etiquetas del archivo llamado
nombre
o las elimina si
nombre
est\('a vac\('io\&.
\fBmkvpropedit\fR(1)
lee el mismo formato de etiquetas XML que
\fBmkvmerge\fR(1)
tambi\('en puede leer\&.
.sp
El
\fIselector\fR
debe ser una de estas palabras:
\fBall\fR,
\fBglobal\fR
o
\fBtrack\fR\&. Para
\fBall\fR,
\fBmkvpropedit\fR(1)
reemplazar\('a o eliminar\('a todas las etiquetas del archivo\&. Con
\fBglobal\fR
s\('olo las etiquetas globales ser\('an reemplazadas o eliminadas\&. Por ejemplo:
mkvpropedit "nombre\-archivo\&.mkv" \-\-tags global:etiquetas\&.xml
mkvpropedit "nombre\-archivo\&.mkv" \-\-tags global:
.sp
Con
\fBtrack\fR,
\fBmkvpropedit\fR(1)
reemplazar\('a las etiquetas de la pista especificada\&. Adem\('as, las etiquetas le\('idas desde
nombre
ser\('an asignadas a la misma pista\&. La pista se especifica de la misma manera que con los
selectores de edici\('on
(mire abajo)\&. Por ejemplo:
mkvpropedit "nombre\-archivo\&.mkv" \-\-tags track:a1:nuevas\-etiquetas\-audio\&.xml\&.
.RE
.PP
\fB\-\-add\-track\-statistics\-tags\fR
.RS 4
Calcula las estad\('isticas de todas las pistas en un archivo y a\(~nade nuevas etiquetas de estad\('istica para ellas\&. Si el archivo ya contiene dichas etiquetas entonces ser\('an actualizadas\&.
.RE
.PP
\fB\-\-delete\-track\-statistics\-tags\fR
.RS 4
Elimina las etiquetas de estad\('istica de todas las pistas de un archivo\&. Si el archivo no contiene etiquetas de estad\('istica, entonces no habr\('a ninguna modificaci\('on\&.
.RE
.PP
\fB\-c\fR, \fB\-\-chapters\fR \fInombre\fR
.RS 4
Reemplaza o a\(~nade los cap\('itulos del archivo llamado
nombre
o las elimina si
nombre
est\('a vac\('io\&.
\fBmkvpropedit\fR(1)
lee el mismo formato de cap\('itulos simple y XML que
\fBmkvmerge\fR(1)
tambi\('en puede leer\&.
.RE
.PP
Acciones para manipular adjuntos:
.PP
\fB\-\-add\-attachment\fR \fInombre\-archivo\fR
.RS 4
A\(~nade un nuevo adjunto a
\fInombre\-archivo\fR\&.
.sp
Si la opci\('on
\fB\-\-attachment\-name\fR
es usada antes de esta opci\('on entonces su valor es usado como el nuevo nombre del adjunto\&. Por el contrario, se deriva del
\fInombre\-archivo\fR\&.
.sp
Si la opci\('on
\fB\-\-attachment\-mime\-type\fR
es usada antes de esta opci\('on entonces su valor es usado como el nuevo tipo MIME del adjunto\&. Por el contrario, es auto\-detectado a partir del contenido del
\fInombre\-archivo\fR\&.
.sp
Si la opci\('on
\fB\-\-attachment\-description\fR
es usada antes de esta opci\('on entonces su valor es usado como la nueva descripci\('on del adjunto\&. Por el contrario, ninguna descripci\('on ser\('a establecida\&.
.sp
Si la opci\('on
\fB\-\-attachment\-uid\fR
se usa delante de esta opci\('on entonces su valor se usar\('a como el nuevo UID del adjunto\&. De lo contrario, un UID aleatorio se generar\('a autom\('aticamente\&.
.RE
.PP
\fB\-\-replace\-attachment\fR \fIselector\fR:\fInombrearchivo\fR
.RS 4
Reemplaza uno o m\('as adjuntos que coincidan con el
\fIselector\fR
del archivo
\fInombre\-archivo\fR\&. Si m\('as de un adjunto existente coincide con el
\fIselector\fR
entonces todo su contenido ser\('a reemplazado por el contenido del
\fInombre\-archivo\fR\&.
.sp
El
\fIselector\fR
puede tener una de estas cuatro formas: ID, UID, Name y MIME type\&. Est\('an explicadas m\('as abajo en la secci\('on
selectores de adjuntos\&.
.sp
Si la opci\('on
\fB\-\-attachment\-name\fR
se usa delante de esta opci\('on entonces su valor se establece como el nuevo nombre para cada adjunto modificado\&. De lo contrario, los nombres no se modificar\('an\&.
.sp
Si la opci\('on
\fB\-\-attachment\-mime\-type\fR
se usa delante de esta opci\('on entonces su valor se establece como el nuevo tipo MIME para cada adjunto modificado\&. De lo contrario, los tipo MIMES no se modificar\('an\&.
.sp
Si la opci\('on
\fB\-\-attachment\-description\fR
se usa delante de esta opci\('on entonces su valor se establece como la nueva descripci\('on de cada adjunto modificado\&. De lo contrario, las descripciones no se modificar\('an\&.
.sp
Si la opci\('on
\fB\-\-attachment\-uid\fR
se usa delante de esta opci\('on entonces su valor se establece como el nuevo UID para cada adjunto modificado\&. De lo contrario, los UIDs no se modificar\('an\&.
.RE
.PP
\fB\-\-update\-attachment\fR \fIselector\fR
.RS 4
Establece las propiedades de uno o m\('as adjuntos que coincidan con el
\fIselector\fR\&. Si m\('as de un adjunto coincide con el
\fIselector\fR, entonces todas sus propiedades ser\('an actualizadas\&.
.sp
El
\fIselector\fR
puede tener una de estas cuatro formas: ID, UID, Name y MIME type\&. Est\('an explicadas m\('as abajo en la secci\('on
selectores de adjuntos\&.
.sp
Si la opci\('on
\fB\-\-attachment\-name\fR
se usa delante de esta opci\('on entonces su valor se establece como el nuevo nombre para cada adjunto modificado\&. De lo contrario, los nombres no se modificar\('an\&.
.sp
Si la opci\('on
\fB\-\-attachment\-mime\-type\fR
se usa delante de esta opci\('on entonces su valor se establece como el nuevo tipo MIME para cada adjunto modificado\&. De lo contrario, los tipo MIMES no se modificar\('an\&.
.sp
Si la opci\('on
\fB\-\-attachment\-description\fR
se usa delante de esta opci\('on entonces su valor se establece como la nueva descripci\('on de cada adjunto modificado\&. De lo contrario, las descripciones no se modificar\('an\&.
.sp
Si la opci\('on
\fB\-\-attachment\-uid\fR
se usa delante de esta opci\('on entonces su valor se establece como el nuevo UID para cada adjunto modificado\&. De lo contrario, los UIDs no se modificar\('an\&.
.RE
.PP
\fB\-\-delete\-attachment\fR \fIselector\fR
.RS 4
Elimina uno o m\('as adjuntos que coincida con el
\fIselector\fR\&.
.sp
El
\fIselector\fR
puede tener una de estas cuatro formas: ID, UID, Name y MIME type\&. Est\('an explicadas m\('as abajo en la secci\('on
selectores de adjuntos\&.
.RE
.PP
Opciones para acciones sobre adjuntos:
.PP
\fB\-\-attachment\-name\fR \fInombre\fR
.RS 4
Establece el nombre a usar en la operaci\('on
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
\fB\-\-attachment\-mime\-type\fR \fImime\-type\fR
.RS 4
Establece el tipo MIME a usar en la operaci\('on
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
\fB\-\-attachment\-description\fR \fIdescripci\('on\fR
.RS 4
Establece la descripci\('on a usar en la operaci\('on
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
Otras opciones:
.PP
\fB\-\-command\-line\-charset\fR \fIconjunto\-caracteres\fR
.RS 4
Establece el conjunto de caracteres a convertir las cadenas de texto dadas desde la l\('inea de comandos\&. Por defecto, se ajusta al conjunto de caracteres dado por la configuraci\('on local del sistema\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIconjunto\-caracteres\fR
.RS 4
Establece el conjunto de caracteres para convertir las cadenas de texto que ser\('an usadas en el archivo de salida\&. Por defecto, se ajusta al conjunto de caracteres dado por la configuraci\('on local del sistema\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fInombre\-archivo\fR
.RS 4
Escribe todos los mensajes al archivo
\fInombre\-archivo\fR
en vez de en la consola\&. Aunque esto se puede hacer f\('acilmente con la opci\('on de redirecci\('on hay casos en los que es necesaria esta opci\('on: cuando el terminal reinterpreta la salida antes de escribirlo al archivo\&. El conjunto de caracteres establecido con
\fB\-\-output\-charset\fR
se respeta\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIc\('odigo\fR
.RS 4
Forces the translations for the language
\fIcode\fR
to be used (e\&.g\&. \*(Aqde_DE\*(Aq for the German translations)\&. Entering \*(Aqlist\*(Aq as the
\fIcode\fR
will cause the program to output a list of available translations\&.
.RE
.PP
\fB\-\-debug\fR \fItopic\fR
.RS 4
Habilita la depuraci\('on para una caracter\('istica concreta\&. Esta opci\('on s\('olo es \('util para desarrolladores\&.
.RE
.PP
\fB\-\-engage\fR \fIcaracter\('istica\fR
.RS 4
Habilita caracter\('isticas experimentales\&. Una lista de caracter\('isticas disponibles puede ser solicitada con la instrucci\('on
\fBmkvpropedit \-\-engage list\fR\&. Estas caracter\('isticas no est\('an indicadas para ser usadas en situaciones normales\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
Habilita el modo GUI\&. En este modo las l\('ineas especialmente formateadas pueden ser generadas para decirle a un control de la GUI lo que est\('a pasando\&. Estos mensajes se rigen bajo el formato \*(Aq#GUI#mensaje\*(Aq\&. El mensaje puede ser continuado por pares de valores/claves como en \*(Aq#GUI#mensaje#clave1=valor1#clave2=valor2\&...\*(Aq\&. Ni los mensajes ni las claves pueden ser traducidas y siempre se generan en ingl\('es\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Habilita el modo detallado y muestra todos los elementos
Matroska(TM)
importantes que pueden ser le\('idos\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Muestra informaci\('on de uso y sale\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Muestra la informaci\('on de la versi\('on y sale\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Comprueba online si hay nuevas versiones al descargar el archivo ubicado en la URL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Cuatro l\('ineas ser\('an generadas del tipo
clave=valor: la URL desde donde se obtuvo la informaci\('on (clave
version_check_url), la versi\('on actual (clave
running_version), la \('ultima versi\('on disponible (clave
available_version) y la URL de descarga (clave
download_url)\&.
.sp
Despu\('es el programa sale con un c\('odigo de salida 0 si ninguna versi\('on nueva est\('a disponible, con 1 si hay disponible una versi\('on m\('as actual y con 2 si ocurre alg\('un error (p\&.e\&. si la informaci\('on de la actualizaci\('on no puede ser obtenida)\&.
.sp
Esta opci\('on s\('olo est\('a disponible si el programa fue creado con compatibilidad para libcurl\&.
.RE
.PP
\fB@\fR\fIarchivo\-opciones\fR
.RS 4
Lee argumentos adicionales de la l\('inea de comandos desde el archivo
\fIarchivo\-opciones\fR\&. Las l\('ineas que tengan en el primer car\('acter una almohadilla (\*(Aq#\*(Aq) ser\('an tratados como comentarios y se ignorar\('an\&. Espacios en blanco al inicio y final de la l\('inea ser\('an descartados\&. Cada l\('inea debe contener exactamente una opci\('on\&.
.sp
Diversos caracteres pueden ser interpretados como de escape, p\&.e\&. si necesitas que una l\('inea, que comience con una almohadilla \*(Aq#\*(Aq, no sea interpretada como un comentario\&. Las normas est\('an descritas en
la secci\('on sobre caracteres de escape en texto\&.
.sp
La l\('inea de comandos \*(Aq\fBmkvpropedit archivo\&.mkv \-\-edit track:a2 \-\-set name=Comentarios\fR\*(Aq puede ser convertida en un archivo de opciones del modo que se indica a continuaci\('on:
.sp
.if n \{\
.RS 4
.\}
.nf
# Modifica nombre\&.mkv
nombre\&.mkv
# Edita la segunda pista de audio
\-\-edit
track:a2
# y establece el t\('itulo como \*(AqComentarios\*(Aq 
\-\-set
name=Comments
.fi
.if n \{\
.RE
.\}
.RE
.SH "SELECTORES DE EDICI\('ON"
.PP
La opci\('on
\fB\-\-edit\fR
establece la secci\('on del archivo
Matroska(TM)
(informaci\('on del segmento o ciertos encabezados de pista) sobre la que se centrar\('an todas las acciones:
add,
set
y
delete\&. Esto es v\('alido hasta que se encuentra el siguiente par\('ametro
\fB\-\-edit\fR\&. El argumento para esta opci\('on se llama el selector de edici\('on\&.
.PP
Por defecto,
\fBmkvpropedit\fR(1)
editar\('a la secci\('on de informaci\('on del segmento\&.
.SS "Informaci\('on del segmento"
.PP
La informaci\('on del segmento puede ser seleccionada con una de estas tres palabras: \*(Aqinfo\*(Aq, \*(Aqsegment_info\*(Aq o \*(Aqsegmentinfo\*(Aq\&. Contiene propiedades como el t\('itulo o el
UID
del segmento \&.
.SS "Encabezados de pista"
.PP
Los encabezados de la pista pueden ser seleccionados con un selector ligeramente m\('as complejo\&. Todas las variantes comienzan con \*(Aqtrack:\*(Aq\&. Las propiedades del encabezado de pista incluye elementos como el c\('odigo de idioma, el flag de \*(Aqpista predefinida\*(Aq o el nombre de la pista\&.
.PP
\fBtrack:\fR\fIn\fR
.RS 4
Si el par\('ametro
\fIn\fR
es un n\('umero entonces la pista con n\('umero
\fIn\fR
ser\('a seleccionada\&. El orden de pista es el mismo que se genera con la opci\('on
\fB\-\-identify\fR
de
\fBmkvmerge\fR(1)\&.
.sp
La numeraci\('on empieza en 1\&.
.RE
.PP
\fBtrack:\fR\fIt\fR\fIn\fR
.RS 4
Si el par\('ametro empieza con el car\('acter
\fIt\fR
seguido por
\fIn\fR
entonces la pista con n\('umero
\fIn\fR
de un tipo espec\('ifico de pista ser\('a seleccionada\&. El par\('ametro del tipo de pista
\fIt\fR
debe ser uno de estos cuatro caracteres: \*(Aqa\*(Aq para una pista de audio, \*(Aqb\*(Aq para un pista de bot\('on, \*(Aqs\*(Aq para una pista de subt\('itulo y \*(Aqv\*(Aq para una pista de video\&. El orden de pista es el mismo que se genera con la opci\('on
\fB\-\-identify\fR
de
\fBmkvmerge\fR(1)\&.
.sp
La numeraci\('on empieza en 1\&.
.RE
.PP
\fBtrack:\fR=\fIuid\fR
.RS 4
Si el par\('ametro empieza con un \*(Aq=\*(Aq seguido por un n\('umero de
\fIuid\fR
entonces ser\('a seleccionada la pista cuyo
UID
coincida con este
\fIuid\fR\&. Los
UIDs
de pista puede ser obtenido con
\fBmkvinfo\fR(1)\&.
.RE
.PP
\fBtrack:\fR@\fIn\('umero\fR
.RS 4
Si el par\('ametro empieza con un \*(Aq@\*(Aq seguido por un
\fIn\('umero\fR
entonces ser\('a seleccionada la pista cuyo n\('umero de elemento coincida con este
\fIn\('umero\fR\&. El n\('umero de pista puede ser obtenido con
\fBmkvinfo\fR(1)\&.
.RE
.SS "Notas"
.PP
Debido a la naturaleza de los selectores de edici\('on de pista es posible que actualmente algunos selectores coincidan con los mismos encabezados de pista\&. En muchos casos, todas las acciones para estos selectores de edici\('on ser\('an combinados y ejecutados en el orden en el que fueron dadas en la l\('inea de comandos\&.
.SH "SELECTORES DE ADJUNTOS"
.PP
Un selector de adjuntos se utiliza con las dos acciones
\fB\-\-replace\-attachment\fR
y
\fB\-\-delete\-attachment\fR\&. Puede tener una de las cuatros formas siguientes:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Selecci\('on mediante el ID de adjunto\&. De esta forma el selector es un simple n\('umero, el ID del adjunto tal y como se genera con el comando de identificaci\('on de
\fBmkvmerge\fR(1)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Selecci\('on mediante el UID de adjunto (\('Unico ID)\&. De esta forma el selector es el signo igual
=
acompa\(~nado por un n\('umero, el UID del adjunto tal y como se genera con el comando de identificaci\('on detallado (verbose) de
\fBmkvmerge\fR(1)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Selecci\('on mediante el name (nombre) de adjunto\&. De esta forma el selector es la palabra literal
name:
seguida por el nombre del adjunto\&. Si el selector es usado con
\fB\-\-replace\-attachment\fR
entonces los dos puntos que pudiera contener el nombre deber\('an ser escapados con
\ec\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Selecci\('on mediante el MIME type (tipo MIME)\&. De esta forma el selector es la palabra
mime\-type:
seguida por el tipo MIME del adjunto\&. Si el selector es usado con
\fB\-\-replace\-attachment\fR
entonces los dos puntos que pudiera contener el tipo MIME deber\('an ser escapados con
\ec\&.
.RE
.SH "EJEMPLOS"
.PP
El siguiente ejemplo edita un archivo llamado \*(Aqpel\('icula\&.mkv\*(Aq\&. Establece el t\('itulo del segmento y modifica el c\('odigo de idioma de una pista de audio y subt\('itulo\&. Tenga en cuenta que este ejemplo puede ser acortado al omitir la primera opci\('on
\fB\-\-edit\fR
ya que editar el elemento de informaci\('on del segmento est\('a incluido por defecto para todas las opciones encontradas antes de la primera opci\('on
\fB\-\-edit\fR\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-edit info \-\-set "title=La pel\('icula" \-\-edit track:a1 \-\-set language=spa \-\-edit track:a2 \-\-set language=eng
.fi
.if n \{\
.RE
.\}
.PP
El segundo ejemplo elimina \*(Aqflag de pista predefinida\*(Aq de la primera pista de subt\('itulo y la establece para la segunda\&. Tenga en cuenta que
\fBmkvpropedit\fR(1), a diferencia de
\fBmkvmerge\fR(1), no establece autom\('aticamente a \*(Aq0\*(Aq el valor de \*(Aqflag de pista predefinida\*(Aq cuando otra pista se ha establecido a \*(Aq1\*(Aq\&.
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-edit track:s1 \-\-set flag\-default=0 \-\-edit track:s2 \-\-set flag\-default=1
.fi
.if n \{\
.RE
.\}
.PP
Reemplaza las etiquetas para la segunda pista de subt\('itulos de un archivo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-tags track:s2:nuevas\-etiquetas\-subt\('itulo\&.xml
.fi
.if n \{\
.RE
.\}
.PP
Elimina todas las etiquetas que hay en el archivo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-tags all: 
.fi
.if n \{\
.RE
.\}
.PP
Reemplaza los cap\('itulos en un archivo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-chapters nuevos\-cap\('itulos\&.xml
.fi
.if n \{\
.RE
.\}
.PP
Elimina todos los cap\('itulos del archivo:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-chapters ""
.fi
.if n \{\
.RE
.\}
.PP
A\(~nade un archivo de tipo fuente (Arial\&.ttf) como un adjunto:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-add\-attachment Arial\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
A\(~nade un archivo de tipo fuente (89719823\&.ttf) como un adjunto y proporciona informaci\('on de como es la fuente Arial:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-attachment\-name Arial\&.ttf \-\-attachment\-description "La fuente Arial como TrueType" 
\-\-attachment\-mime\-type application/x\-truetype\-font \-\-add\-attachment 89719823\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Reemplaza el archivo adjunto (Comic\&.ttf) del archivo por otro (Arial\&.ttf):
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-attachment\-name Arial\&.ttf \-\-attachment\-description "La fuente Arial como TrueType"
\-\-replace\-attachment name:Comic\&.ttf:Arial\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Elimina el segundo archivo adjunto:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-delete\-attachment 2
.fi
.if n \{\
.RE
.\}
.PP
Elimina todos las fuentes adjuntas por tipo MIME:
.sp
.if n \{\
.RS 4
.\}
.nf
mkvpropedit pel\('icula\&.mkv \-\-delete\-attachment mime\-type:application/x\-truetype\-font
.fi
.if n \{\
.RE
.\}
.SH "C\('ODIGOS DE SALIDA"
.PP
Mkvpropedit(1) finaliza con uno de estos tres c\('odigos de salida:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- Este c\('odigo de salida significa que la extracci\('on se ha realizado correctamente\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- En este caso
\fBmkvpropedit\fR(1)
genera una salida con al menos una advertencia, pero la extracci\('on continu\('o\&. Una advertencia es prefijada con el texto \*(AqAdvertencia:\*(Aq\&. Dependiendo de los fallos involucrados los archivos creados ser\('an correctos o no\&. El usuario es instado a que revise tanto las advertencias como los archivos creados\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- Este c\('odigo de salida es usado despu\('es de que ocurra un error\&.
\fBmkvpropedit\fR(1)
aborta el proceso justo despu\('es de mostrar el mensaje de error\&. El rango de los mensajes de error va desde los argumentos de la l\('inea de comandos, por delante de los errores de lectura/escritura, hasta los archivos err\('oneos\&.
.RE
.SH "CONVERSI\('ON DE ARCHIVOS DE TEXTO Y CONJUNTO DE CARACTERES"
.PP
Para una discusi\('on en profundidad sobre como la suite de MkvToolNix manipula las conversiones de caracteres, la codificaci\('on entrada/salida y la codificaci\('on de la l\('inea de comandos y consola, por favor consulte la secci\('on llamada de igual manera en la pagina del manual para
\fBmkvmerge\fR(1)\&.
.SH "CARACTERES ESPECIALES DE ESCAPE EN EL TEXTO"
.PP
Hay pocos sitios en los que los caracteres especiales en el texto puedan o deban ser escapados\&. Las reglas del escape son simples: cada car\('acter que necesite ser escapado es reemplazado con una barra invertida seguida de otro car\('acter\&.
.PP
Las reglas son: \*(Aq \*(Aq (un espacio) se convierte a \*(Aq\es\*(Aq, \*(Aq"\*(Aq (doble comillas) ser\('ia \*(Aq\e2\*(Aq, \*(Aq:\*(Aq se convierte a \*(Aq\ec\*(Aq, \*(Aq#\*(Aq se reemplazada como \*(Aq\eh\*(Aq y \*(Aq\e\*(Aq (una barra invertida) se expresar\('ia como \*(Aq\e\e\*(Aq\&.
.SH "VARIABLES DE ENTORNO"
.PP
\fBmkvpropedit\fR(1)
usa las variables predefinidas que se determinan en la configuraci\('on local del sistema (p\&.e\&.
\fILANG\fR
y la familia
\fILC_*\fR)\&. Variables adicionales:
.PP
\fIMKVPROPEDIT_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR y su forma abreviada \fIMTX_DEBUG\fR
.RS 4
El contenido se trata como si se hubiese pasado a trav\('es de la opci\('on
\fB\-\-debug\fR\&.
.RE
.PP
\fIMKVPROPEDIT_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR y su forma abreviada \fIMTX_ENGAGE\fR
.RS 4
El contenido se trata como si se hubiese pasado a trav\('es de la opci\('on
\fB\-\-engage\fR\&.
.RE
.PP
\fIMKVPROPEDIT_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR y su forma abreviada \fIMTX_OPTIONS\fR
.RS 4
El contenido es dividido en espacios en blanco\&. Las cadenas de texto parciales resultantes son tratadas como si hubiesen sido pasadas como opciones a la l\('inea de comandos\&. Si necesitas pasar caracteres especiales (p\&.e\&. espacios) entonces tienes que escaparlos (vea
la secci\('on caracteres especiales de escape en el texto)\&.
.RE
.SH "VEA TAMBI\('EN"
.PP
\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvextract\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
La \('ultima versi\('on se puede encontrar siempre en
\m[blue]\fBla p\('agina de MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desarrollador
.RE
.SH "NOTAS"
.IP " 1." 4
la p\('agina de MKVToolNix
.RS 4
\%https://mkvtoolnix.download/
.RE
