'\" t
.\"     Title: mkvtoolnix-gui
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-07-14
.\"    Manual: Comandos de usuario
.\"    Source: MKVToolNix 9.3.1
.\"  Language: Spanish
.\"
.TH "MKVTOOLNIX\-GUI" "1" "2016\-07\-14" "MKVToolNix 9\&.3\&.1" "Comandos de usuario"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOMBRE"
mkvtoolnix-gui \- una GUI para \fBmkvmerge\fR(1) incluyendo un cap\('itulo y editor de encabezado
.SH "SINOPSIS"
.HP \w'\fBmkvtoolnix\-gui\fR\ 'u
\fBmkvtoolnix\-gui\fR [[archivo\-configuraci\('on\&.mtxcfg] | [archivo\-origen\&.ext] | [\-\-edit\-chapters\ [archivo\-cap\('itulos\&.ext]] | [\-\-edit\-headers\ [archivo\-matroska\&.mkv]]]
.SH "DESCRIPCI\('ON"
.PP
\fBmkvtoolnix-gui\fR(1)
es una
GUI, basada en
Qt(TM), para
\fBmkvmerge\fR(1)
(y evolucionar\('a para abarcar
\fBmkvinfo\fR(1)
y
\fBmkvextract\fR(1))\&. Ofrece un f\('acil acceso a la mayor\('ia de opciones de
\fBmkvmerge\fR(1)\&. Todos los ajustes (p\&.e\&. archivos origen, opciones de pista, etc\&.\&.\&.) pueden ser guardados y cargados\&.
.PP
Los archivos de configuraci\('on con la extensi\('on
\&.mtxcfg
provocan que la GUI los cargue mediante una herramienta adecuada\&. Cualquier archivo de configuraci\('on, se a\(~nade como un archivo para el multiplexado, o se abre en el editor de cap\('itulos o de cabeceras, dependiendo del modo actual\&. El modo actual se puede cambiar con
\fB\-\-merge\fR,
\fB\-\-edit\-chapters\fR
o
\fB\-\-edit\-headers\fR\&. El modo por defecto es a\(~nadir archivos para multiplexar\&.
.PP
Tenga en cuenta que si una instancia de la aplicaci\('on ya se est\('a ejecutando cuando la aplicaci\('on se inicia por segunda vez, todos los nombres de los archivos dados en la l\('inea de comandos ser\('an gestionados por la instancia que se encuentra en ejecuci\('on\&.
.PP
\fB\-\-merge\fR
.RS 4
Los posteriores archivos de configuraci\('on se a\(~nadir\('an como archivos de entrada a la tarea de multiplexado actual\&. Este es el modo por defecto\&.
.RE
.PP
\fB\-\-edit\-chapters\fR
.RS 4
Los posteriores archivos de configuraci\('on ser\('an abiertos en el editor de cap\('itulos\&.
.RE
.PP
\fB\-\-edit\-headers\fR
.RS 4
Los posteriores archivos de configuraci\('on ser\('an abiertos en el editor de cabeceras\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Muestra informaci\('on de uso y sale\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Muestra la informaci\('on de la versi\('on y sale\&.
.RE
.SH "VEA TAMBI\('EN"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1)
.SH "WWW"
.PP
La \('ultima versi\('on se puede encontrar siempre en
\m[blue]\fBla p\('agina de MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desarrollador
.RE
.SH "NOTAS"
.IP " 1." 4
la p\('agina de MKVToolNix
.RS 4
\%https://mkvtoolnix.download/
.RE
