'\" t
.\"     Title: mmg
.\"    Author: Moritz Bunkus <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2015-07-18
.\"    Manual: Comandos de usuario
.\"    Source: MKVToolNix 8.2.0
.\"  Language: Spanish
.\"
.TH "MMG" "1" "2015\-07\-18" "MKVToolNix 8\&.2\&.0" "Comandos de usuario"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOMBRE"
mmg \- una GUI para \fBmkvmerge\fR(1) incluyendo un cap\('itulo y editor de encabezado
.SH "SINOPSIS"
.HP \w'\fBmmg\fR\ 'u
\fBmmg\fR [[\-\-edit\-headers\ {archivo\&.mkv}] | [archivo\-preferencias\&.mmg] | [archivo\&.ext]]
.SH "DESCRIPCI\('ON"
.PP
\fBmmg\fR(1)
es una
GUI
basada en
wxWindows(TM)para
\fBmkvmerge\fR(1)\&. Ofrece un f\('acil acceso a todas las opciones de
\fBmkvmerge\fR(1)\&. Todos los ajustes (p\&.e\&. fuente de archivos, opciones de pista, etc\&.\&.) puede ser guardada y restaurada\&. Se incluye un editor de cap\('itulos que puede leer el formato de cap\('itulos
OGM
y
XML, escribir archivos de cap\('itulos en formato
XML
e incluso leer y escribir archivos de cap\('itulos directamente desde archivos
Matroska(TM)\&. Tambi\('en est\('a incluido un editor de encabezado que puede ser usado para cambiar r\('apidamente las propiedades del archivo
Matroska(TM)
sin necesidad de multiplexar\&.
.PP
\fBmmg\fR(1)
tiene pocas opciones\&. La primera posibilidad es iniciarlo con un nombre de archivo \('unico\&. Si la extensi\('on del archivo es \*(Aq\&.mmg\*(Aq entonces ser\('a tratado como un archivo de preferencias y
\fBmmg\fR(1)
cargar\('a sus ajustes cuando se inicie\&. De lo contrario, el nombre se interpreta como el nombre de un archivo de entrada que ser\('a a\(~nadido\&.
.PP
El segundo modo de operaci\('on se invoca con la opci\('on
\fB\-\-edit\-headers\fR
y un nombre de un archivo\&. Esto permite a
\fBmmg\fR(1)
ejecutar su editor de encabezado y cargar el archivo\&.
.PP
La documentaci\('on integra est\('a disponible en la HTML (doc/mkvmerge\-gui\&.html)\&.
.SH "VEA TAMBI\('EN"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1)
.SH "WWW"
.PP
La \('ultima versi\('on se puede encontrar siempre en
\m[blue]\fBla p\('agina de MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBMoritz Bunkus\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desarrollador
.RE
.SH "NOTAS"
.IP " 1." 4
la p\('agina de MKVToolNix
.RS 4
\%https://www.bunkus.org/videotools/mkvtoolnix/
.RE
