'\" t
.\"     Title: mkvextract
.\"    Author: Bunkus, Moritz <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-12-27
.\"    Manual: Ordres d\*(Aqusuari
.\"    Source: MKVToolNix 9.7.1
.\"  Language: Catalan
.\"
.TH "MKVEXTRACT" "1" "2016\-12\-27" "MKVToolNix 9\&.7\&.1" "Ordres d\*(Aqusuari"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
mkvextract \- Extreu les pistes des de fitxers Matroska(TM) a altres fitxers
.SH "SINOPSIS"
.HP \w'\fBmkvextract\fR\ 'u
\fBmkvextract\fR {mode} {nom_fitxer_origen} [opcions] [especificacions_extracci\('o]
.SH "DESCRIPCI\('O"
.PP
Aquest programa extreu parts espec\('ifiques d\*(Aqun fitxer
Matroska(TM)
a altres formats d\*(Aqutilitat\&. El primer argument,
\fBmode\fR, li indica al
\fBmkvextract\fR(1)
qu\(`e ha d\*(Aqextreure\&. Actualment \('es possible extreure
pistes (tracks),
etiquetes (tags),
adjunts (attachments),
cap\('itols (chapters),
fulls de muntatge (CUE sheets),
codis de temps (timecodes)
i
\('indexs (cues)\&. El segon argument \('es el nom del fitxer d\*(Aqorigen\&. Aquest haur\(`a de ser un fitxer
Matroska(TM)\&. La resta d\*(Aqarguments s\('on opcions i especificacions per a l\*(Aqextracci\('o \-ambdues depenen del mode seleccionat\-\&.
.SS "Opcions comunes"
.PP
Les seg\(:uents opcions estan disponibles en tots els modes i nom\('es es descriuran en aquesta secci\('o\&.
.PP
\fB\-f\fR, \fB\-\-parse\-fully\fR
.RS 4
Defineix el mode d\*(Aqan\(`alisi a \(Fofull\(Fc (Completa)\&. El mode per omissi\('o no analitzar\(`a tot el fitxer ja que empra la meta de cerca dels elements per a localitzar els elements requerits d\*(Aqun fitxer d\*(Aqorigen\&. En el 99% dels casos n\*(Aqhi ha prou\&. Per\(`o per a fitxers que no contenen elements meta de cerca o que estan malmesos, l\*(Aqusuari hauria d\*(Aqemprar aquest mode\&. L\*(Aqan\(`alisi completa d\*(Aqun fitxer pot requerir for\(,ca temps, mentre que una an\(`alisi r\(`apida nom\('es porta segons\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Defineix el joc de car\(`acters al qual convertir les cadenes indicades des de la l\('inia d\*(Aqordres\&. Per omissi\('o ser\(`a el joc de car\(`acters donat per la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Defineix el joc de car\(`acters al qual convertir les cadenes de la sortida\&. Per omissi\('o ser\(`a el joc de car\(`acters donat per la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fInom_fitxer\fR
.RS 4
Escriu tots els missatges al
\fInom_fitxer\fR
en lloc de a la consola\&. Si b\('e aix\(`o es pot fer f\(`acilment amb la redirecci\('o de la sortida, hi ha casos en qu\(`e cal aquesta opci\('o: quan el terminal torna a interpretar la sortida abans d\*(Aqescriure\-la a un fitxer\&. Es respectar\(`a el joc de car\(`acters establert amb
\fB\-\-output\-charset\fR\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIcodi\fR
.RS 4
For\(,ca l\*(Aq\('us de les traduccions pel
\fIcodi\fR
d\*(Aqidioma (p\&. ex\&., \(Fode_DE\(Fc per a les traduccions en alemany)\&. Introduint \(Folist\(Fc com a
\fIcodi\fR, es far\(`a que el programa ofereixi a la sortida una llista de les traduccions disponibles\&.
.RE
.PP
\fB\-\-debug\fR \fItema\fR
.RS 4
Activa la depuraci\('o per a una caracter\('istica espec\('ifica\&. Aquesta opci\('o nom\('es \('es \('util pels desenvolupadors\&.
.RE
.PP
\fB\-\-engage\fR \fIcaracter\('istica\fR
.RS 4
Activa les caracter\('istiques experimentals\&. Es pot sol\(mdlicitar una llista de les caracter\('istiques disponibles amb
\fBmkvextract \-\-engage list\fR\&. Aquestes caracter\('istiques no estan destinades a ser emprades en situacions normals\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
Activa el mode IGU\&. En aquest mode, les l\('inies surten amb un format especial que pot explicar\-vos el que est\(`a succeint per tal de controlar la IGU\&. Aquests missatges segueixen el format \(Fo#IGU#missatge\(Fc\&. El missatge pot estar seguit per parells clau/valor com \(Fo#IGU#missatge#clau1=valor1#clau2=valor2\&...\(Fc\&. Ni els missatges ni les claus seran tradu\(:ides, sempre sortiran en angl\(`es\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Ser\(`a detallat i mostrar\(`a tots els elements importants del
Matroska(TM)
a mesura que es llegeixin\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra la informaci\('o d\*(Aq\('us i surt\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Mostra la informaci\('o sobre la versi\('o i surt\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Comprova en l\('inia si hi ha nous llan\(,caments per baixar\-los des de l\*(AqURL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Es generaran quatre l\('inies amb l\*(Aqestil
clau=valor: l\*(AqURL des d\*(Aqon s\*(Aqha obtingut la informaci\('o (clau
version_check_url), la versi\('o actualment en execuci\('o (clau
running_version), la versi\('o de l\*(Aq\('ultim llan\(,cament (clau
available_version) i l\*(AqURL per a la baixada (clau
download_url)\&.
.sp
Despr\('es el programa sortir\(`a amb un codi de sortida de 0 si no hi ha cap llan\(,cament m\('es recent disponible, amb 1 si hi ha disponible una nova versi\('o i amb 2 si s\*(Aqha produ\(:it algun error (p\&. ex\&., si no s\*(Aqha pogut recuperar la informaci\('o sobre l\*(Aqactualitzaci\('o)\&.
.sp
Aquesta opci\('o nom\('es estar\(`a disponible si el programa va ser constru\(:it amb la implementaci\('o per a \(Folibcurl\(Fc\&.
.RE
.PP
\fB@\fR\fIfitxer_d_opcions\&.json\fR
.RS 4
Llegeix els arguments addicionals per a la l\('inia d\*(Aqordres des del fitxer
\fIfitxer_d_opcions\fR\&. Per a m\('es informaci\('o sobre els formats admesos, vegeu la secci\('o anomenada \(FoFitxers d\*(Aqopcions\(Fc a la p\(`agina man del
\fBmkvmerge\fR(1)\&.
.RE
.SS "Mode extracci\('o de la pista"
.PP
Sintaxi:
\fBmkvextract \fR\fB\fBtracks\fR\fR\fB \fR\fB\fInom_fitxer_origen\fR\fR\fB \fR\fB[\fIopcions\fR]\fR\fB \fR\fB\fITID1:nom_fitxer_destinaci\('o_1\fR\fR\fB \fR\fB[\fITID2:nom_fitxer_destinaci\('o_2\fR \(Fo\&.\&.\&.\(Fc]\fR
.PP
Hi ha disponibles les seg\(:uents opcions de l\('inia d\*(Aqordres per a cada pista en el mode d\*(Aqextracci\('o \(Fotracks\(Fc (pistes)\&. Hauran d\*(Aqapar\(`eixer al davant de l\*(Aqespecificaci\('o de la pista on s\*(Aqhagin d\*(Aqaplicar (veure a sota)\&.
.PP
\fB\-c\fR \fIjoc_de_car\(`acters\fR
.RS 4
Defineix el joc de car\(`acters per a convertir el text de la seg\(:uent pista de subt\('itols\&. Nom\('es ser\(`a v\(`alida si l\*(Aqobjectiu de l\*(AqID es correspon amb una pista de subt\('itols de text\&. Per omissi\('o s\*(Aqempra UTF\-8\&.
.RE
.PP
\fB\-\-blockadd\fR \fInivell\fR
.RS 4
Nom\('es mant\('e \(FoBlockAdditions\(Fc fins aquest nivell\&. Per omissi\('o ho mant\('e en tots els nivells\&. Aquesta opci\('o nom\('es afectar\(`a certs tipus de c\(`odecs com WAVPACK4\&.
.RE
.PP
\fB\-\-cuesheet\fR
.RS 4
Fa que el
\fBmkvextract\fR(1)
extregui un full de muntatge (CUE
sheet) des de la informaci\('o dels cap\('itols i les dades de les etiquetes per a la seg\(:uent pista a dins d\*(Aqun fitxer el nom del qual ser\(`a el nom de sortida de la pista amb un prefix \(Fo\&.cue\(Fc\&.
.RE
.PP
\fB\-\-raw\fR
.RS 4
Extreu les dades en RAW a un fitxer sense contenidor\&. A difer\(`encia de l\*(Aqetiqueta
\fB\-\-fullraw\fR, aquesta etiqueta no causa que el contingut de l\*(Aqelement
CodecPrivate
s\*(Aqescrigui al fitxer\&. Aquest mode funciona amb tots els
CodecID, fins i tot amb els que el
\fBmkvextract\fR(1)
no permet, per\(`o els fitxers resultants podrien no ser usables\&.
.RE
.PP
\fB\-\-fullraw\fR
.RS 4
Extreu les dades en RAW a un fitxer sense contenidor\&. El contingut de l\*(Aqelement
CodecPrivate
s\*(Aqescriur\(`a en el primer fitxer si la pista cont\('e aquest element a la cap\(,calera\&. Aquest mode funciona amb tots els
CodecID, fins i tot amb els que el
\fBmkvextract\fR(1)
no permet, per\(`o els fitxers resultants podrien no ser usables\&.
.RE
.PP
\fITID:nom_sortida\fR
.RS 4
Causa l\*(Aqextracci\('o de la pista amb l\*(AqID
\fITID\fR
al fitxer
\fInom_sortida\fR, si aquesta pista existeix al fitxer d\*(Aqorigen\&. Aquesta opci\('o es pot emprar m\('ultiples vegades\&. Els ID de les pistes s\('on els mateixos que mostra el
\fBmkvmerge\fR(1)
amb l\*(Aqopci\('o
\fB\-\-identify\fR\&.
.sp
Cada nom de sortida nom\('es s\*(Aqha d\*(Aqemprar una vegada\&. L\*(Aq\('unica excepci\('o s\('on les pistes RealAudio i RealVideo\&. Si empreu el mateix nom per a pistes diferents, llavors aquestes seran emmagatzemades en el mateix fitxer\&. Exemple:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tracks entrada\&.mkv 1:sortida_dos_pistes\&.rm 2:sortida_dos_pistes\&.rm
.fi
.if n \{\
.RE
.\}
.RE
.SS "Mode extracci\('o de les etiquetes"
.PP
Sintaxi:
\fBmkvextract \fR\fB\fBtags\fR\fR\fB \fR\fB\fInom_fitxer_origen\fR\fR\fB \fR\fB[\fIopcions\fR]\fR
.PP
Les etiquetes extretes s\*(Aqescriuran a la consola a menys que la sortida sigui redirigida (per a m\('es detalls, vegeu la secci\('o sobre
la redirecci\('o de la sortida)\&.
.SS "Mode extracci\('o dels adjunts"
.PP
Sintaxi:
\fBmkvextract \fR\fB\fBattachments\fR\fR\fB \fR\fB\fInom_fitxer_origen\fR\fR\fB \fR\fB[\fIopcions\fR]\fR\fB \fR\fB\fIAID1:nom_sortida_1\fR\fR\fB \fR\fB[\fIAID2:nom_sortida_2\fR \(Fo\&.\&.\&.\(Fc]\fR
.PP
\fIAID\fR:\fInom_sortida\fR
.RS 4
Causa l\*(Aqextracci\('o de l\*(Aqadjunt amb l\*(AqID
\fIAID\fR
al fitxer
\fInom_sortida\fR, si aquest adjunt existeix al fitxer d\*(Aqorigen\&. Si es deixa buit el
\fInom_sortida\fR, llavors s\*(Aqemprar\(`a el nom de l\*(Aqadjunt al fitxer
Matroska(TM)
d\*(Aqorigen\&. Aquesta opci\('o es pot emprar m\('ultiples vegades\&. Els ID dels adjunts s\('on els mateixos que mostra el
\fBmkvmerge\fR(1)
amb l\*(Aqopci\('o
\fB\-\-identify\fR\&.
.RE
.SS "Mode extracci\('o dels cap\('itols"
.PP
Sintaxi:
\fBmkvextract \fR\fB\fBchapters\fR\fR\fB \fR\fB\fInom_fitxer_origen\fR\fR\fB \fR\fB[\fIopcions\fR]\fR
.PP
\fB\-s\fR, \fB\-\-simple\fR
.RS 4
Exporta la informaci\('o dels cap\('itols en un format simple, emprat en les eines
OGM
(CHAPTER01=\(Fo\&.\&.\&.\(Fc, CHAPTER01NAME=\(Fo\&.\&.\&.\(Fc)\&. En aquest mode es descartar\(`a alguna informaci\('o\&. Per omissi\('o la sortida dels cap\('itols ser\(`a en el format
XML\&.
.RE
.PP
\fB\-\-simple\-language\fR \fIidioma\fR
.RS 4
Si el format simple est\(`a habilitat, llavors el
\fBmkvextract\fR(1)
simplement mostrar\(`a una \('unica entrada per a cada \(`atom de cap\('itol trobat, fins i tot si un \(`atom de cap\('itol cont\('e m\('es d\*(Aqun nom de cap\('itol\&. Per omissi\('o, el
\fBmkvextract\fR(1)
emprar\(`a el primer nom de cap\('itol trobat per a cada \(`atom, independentment del seu idioma\&.
.sp
L\*(Aq\('us d\*(Aqaquesta opci\('o permet a l\*(Aqusuari determinar quins s\('on els noms dels cap\('itols de sortida si els \(`atoms contenen m\('es d\*(Aqun nom de cap\('itol\&. El par\(`ametre
\fIlanguage\fR
ha de ser un codi ISO 639\-1 o ISO 639\-2\&.
.RE
.PP
Els cap\('itols extrets s\*(Aqescriuran a la consola a menys que la sortida sigui redirigida (per a m\('es detalls, vegeu la secci\('o sobre
la redirecci\('o de la sortida)\&.
.SS "Mode extracci\('o del full de muntatge"
.PP
Sintaxi:
\fBmkvextract \fR\fB\fBcuesheet\fR\fR\fB \fR\fB\fInom_fitxer_origen\fR\fR\fB \fR\fB[\fIopcions\fR]\fR
.PP
Els fulls de muntatge extrets s\*(Aqescriuran a la consola a menys que la sortida sigui redirigida (per a m\('es detalls, vegeu la secci\('o sobre
la redirecci\('o de la sortida)\&.
.SS "Mode extracci\('o del codi de temps"
.PP
Sintaxi:
\fBmkvextract \fR\fB\fBtimecodes_v2\fR\fR\fB \fR\fB\fInom_fitxer_origen\fR\fR\fB \fR\fB[\fIopcions\fR]\fR\fB \fR\fB\fITID1:nom_fitxer_destinaci\('o_1\fR\fR\fB \fR\fB[\fITID2:nom_fitxer_destinaci\('o_2\fR \(Fo\&.\&.\&.\(Fc]\fR
.PP
Els codis de temps extrets s\*(Aqescriuran a la consola a menys que la sortida sigui redirigida (per a m\('es detalls, vegeu la secci\('o sobre
la redirecci\('o de la sortida)\&.
.PP
\fITID:nom_sortida\fR
.RS 4
Causa l\*(Aqextracci\('o dels codis de temps per a la pista amb l\*(AqID
\fITID\fR
al fitxer
\fInom_sortida\fR, si aquesta pista existeix al fitxer d\*(Aqorigen\&. Aquesta opci\('o es pot emprar m\('ultiples vegades\&. Els ID de les pistes s\('on els mateixos que mostra el
\fBmkvmerge\fR(1)
amb l\*(Aqopci\('o
\fB\-\-identify\fR\&.
.sp
Exemple:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract timecodes_v2 entrada\&.mkv 1:ct_pista_1\&.txt 2:ct_pista_2\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SS "Mode extracci\('o dels \('indexs"
.PP
Sintaxi:
\fBmkvextract \fR\fB\fBcues\fR\fR\fB \fR\fB\fInom_fitxer_origen\fR\fR\fB \fR\fB[\fIopcions\fR]\fR\fB \fR\fB\fITID1:nom_fitxer_destinaci\('o_1\fR\fR\fB \fR\fB[\fITID2:nom_fitxer_destinaci\('o_2\fR \(Fo\&.\&.\&.\(Fc]\fR
.PP
\fITID:nom_fitxer_destinaci\('o\fR
.RS 4
Causa l\*(Aqextracci\('o dels \('indexs per a la pista amb l\*(AqID
\fITID\fR
al fitxer
\fInom_sortida\fR, si aquesta pista existeix al fitxer d\*(Aqorigen\&. Aquesta opci\('o es pot emprar m\('ultiples vegades\&. Els ID de les pistes s\('on els mateixos que mostra el
\fBmkvmerge\fR(1)
amb l\*(Aqopci\('o
\fB\-\-identify\fR
i no els n\('umeros continguts en l\*(Aqelement
CueTrack\&.
.RE
.PP
El format de la sortida \('es un simple format de text: una l\('inia per a cada element
CuePoint
amb un parell
clau=valor\&. Si un element opcional no \('es present en un
CuePoint
(p\&. ex\&.,
CueDuration), llavors es retornar\(`a un gui\('o com a valor\&.
.PP
Exemple:
.sp
.if n \{\
.RS 4
.\}
.nf
timecode=00:00:13\&.305000000 duration=\- cluster_position=757741 relative_position=11
.fi
.if n \{\
.RE
.\}
.PP
Les claus possibles s\('on:
.PP
timecode
.RS 4
El codi de temps del punt de l\*(Aq\('index amb una precisi\('o de nanosegons\&. El format \('es
HH:MM:SS\&.nnnnnnnnn\&. Aquest element s\*(Aqestablir\(`a sempre\&.
.RE
.PP
duration
.RS 4
La durada del punt de l\*(Aq\('index amb una precisi\('o de nanosegons\&. El format \('es
HH:MM:SS\&.nnnnnnnnn\&.
.RE
.PP
cluster_position
.RS 4
La posici\('o absoluta en bytes dins del fitxer
Matroska(TM), on comen\(,ca el cl\('uster que cont\('e l\*(Aqelement de refer\(`encia\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNota\fR
.ps -1
.br
Dins del fitxer
Matroska(TM), el
CueClusterPosition
es refereix a la compensaci\('o a l\*(Aqinici de les dades del segment\&. El valor de la sortida \('es donat pel mode d\*(Aqextracci\('o de l\*(Aq\('index del
\fBmkvextract\fR(1), per\(`o ja cont\('e aquesta compensaci\('o, la qual \('es absoluta a partir del comen\(,cament del fitxer\&.
.sp .5v
.RE
.RE
.PP
relative_position
.RS 4
La posici\('o relativa en bytes dins del cl\('uster on l\*(Aqelement
BlockGroup
o
SimpleBlock
\('es el punt de l\*(Aq\('index al qual es refereix al comen\(,cament\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNota\fR
.ps -1
.br
Dins del fitxer
Matroska(TM), el
CueRelativePosition
es refereix a la compensaci\('o a l\*(Aqinici de les dades del cl\('uster\&. El valor de sortida ser\(`a donat pel mode d\*(Aqextracci\('o de l\*(Aq\('index del
\fBmkvextract\fR(1), per\(`o \('es relatiu a l\*(AqID del cl\('uster\&. La posici\('o absoluta dins del fitxer es pot calcular afegint
cluster_position
i
relative_position\&.
.sp .5v
.RE
.RE
.PP
Exemple:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract cues entrada\&.mkv 1:\('index_pista_1\&.txt 2:\('index_pista_2\&.txt
.fi
.if n \{\
.RE
.\}
.SH "REDIRECCI\('O DE LA SORTIDA"
.PP
Diversos modes d\*(Aqextracci\('o provoquen que el
\fBmkvextract\fR(1)
escrigui la informaci\('o extreta a la consola\&. En general, hi ha dos modes d\*(Aqescriure aquesta informaci\('o a un fitxer: un proporcionat per l\*(Aqint\(`erpret d\*(Aqordres i un altre pel
\fBmkvextract\fR(1)\&.
.PP
El mecanisme de redirecci\('o intern de l\*(Aqint\(`erpret d\*(Aqordres \('es emprat amb \(Fo> nom_fitxer_sortida\&.ext\(Fc a la l\('inia d\*(Aqordres\&. Exemple:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tags origen\&.mkv > etiquetes\&.xml
.fi
.if n \{\
.RE
.\}
.PP
La redirecci\('o del
\fBmkvextract\fR(1)
\('es invocada amb l\*(Aqopci\('o
\fB\-\-redirect\-output\fR\&. Exemple:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvextract tags origen\&.mkv \-\-redirect\-output etiquetes\&.xml
.fi
.if n \{\
.RE
.\}
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNota\fR
.ps -1
.br
.PP
En Windows possiblement necessitareu emprar l\*(Aqopci\('o
\fB\-\-redirect\-output\fR, perqu\(`e
\fBcmd\&.exe\fR
a vegades interpreta els car\(`acters especials abans que s\*(Aqescriguin al fitxer de sortida, resultant en una sortida malmesa\&.
.sp .5v
.RE
.SH "CONVERSI\('O PER A FITXERS DE TEXT I JOCS DE CAR\(`ACTERS"
.PP
Per a un debat en profunditat sobre com manipula la suite MKVToolNix les conversions entre els jocs de car\(`acters, codifica l\*(Aqentrada/sortida, codifica la l\('inia d\*(Aqordres i codifica a la consola, si us plau, vegeu la secci\('o anomenada de la mateixa manera a la p\(`agina man del
\fBmkvmerge\fR(1)\&.
.SH "FORMATS PELS FITXERS DE SORTIDA"
.PP
La decisi\('o sobre el format de la sortida es basa en el tipus de pista, i no en l\*(Aqextensi\('o usada en el nom del fitxer de sortida\&. Per ara, s\*(Aqadmeten els seg\(:uents tipus de pista:
.PP
V_MPEG4/ISO/AVC
.RS 4
Les pistes de v\('ideo
H\&.264
/
AVC
s\*(Aqescriuran en fluxos elementals
H\&.264
que posteriorment es poden processar, p\&. ex\&., amb
MP4Box(TM)
del paquet
GPAC(TM)\&.
.RE
.PP
V_MS/VFW/FOURCC
.RS 4
Les pistes de v\('ideo amb
FPS
fixos amb aquest
CodecID
s\*(Aqescriuran en fitxers
AVI\&.
.RE
.PP
V_REAL/*
.RS 4
Les pistes
RealVideo(TM)
s\*(Aqescriuran en fitxers
RealMedia(TM)\&.
.RE
.PP
V_THEORA
.RS 4
Els fluxos
Theora(TM)
s\*(Aqescriuran dins d\*(Aqun contenidor
Ogg(TM)\&.
.RE
.PP
V_VP8, V_VP9
.RS 4
Les pistes
VP8
/
VP9
s\*(Aqescriuran en fitxers
IVF\&.
.RE
.PP
A_MPEG/L2
.RS 4
Els fluxos d\*(Aq\(`audio MPEG\-1 nivell II s\*(Aqextrauran a fitxers
MP2
en RAW\&.
.RE
.PP
A_MPEG/L3, A_AC3
.RS 4
Aquests s\*(Aqextreuen a fitxers
MP3
i
AC\-3
en RAW\&.
.RE
.PP
A_PCM/INT/LIT
.RS 4
Les dades
PCM
en RAW s\*(Aqescriuran en un fitxer
WAV\&.
.RE
.PP
A_AAC/MPEG2/*, A_AAC/MPEG4/*, A_AAC
.RS 4
Tots els fitxers
AAC
s\*(Aqescriuran en un fitxer
AAC
amb cap\(,caleres
ADTS
abans de cada paquet\&. Les cap\(,caleres
ADTS
no contindran l\*(Aqobsolet camp d\*(Aq\(`emfasi\&.
.RE
.PP
A_VORBIS
.RS 4
L\*(Aq\(`audio Vorbis s\*(Aqescriur\(`a en un fitxer
OggVorbis(TM)\&.
.RE
.PP
A_REAL/*
.RS 4
Les pistes
RealAudio(TM)
s\*(Aqescriuran en fitxers
RealMedia(TM)\&.
.RE
.PP
A_TTA1
.RS 4
Les pistes
TrueAudio(TM)
s\*(Aqescriuran en fitxers
TTA\&. Si us plau, tingueu en compte que a causa de la limitada precisi\('o dels codis de temps del
Matroska(TM), la cap\(,calera extreta del fitxer ser\(`a diferent pel que fa a dos camps:
\fIdata_length\fR
(el nombre total de fluxos en el fitxer) i la
CRC\&.
.RE
.PP
A_ALAC
.RS 4
Les pistes
ALAC
s\*(Aqescriuran en fitxers
CAF\&.
.RE
.PP
A_FLAC
.RS 4
Les pistes
FLAC
s\*(Aqescriuran en fitxers
FLAC
en RAW\&.
.RE
.PP
A_WAVPACK4
.RS 4
Les pistes
WavPack(TM)
s\*(Aqescriuran en fitxers
WV\&.
.RE
.PP
A_OPUS
.RS 4
Les pistes
Opus(TM)
s\*(Aqescriuran en fitxers
OggOpus(TM)\&.
.RE
.PP
S_TEXT/UTF8
.RS 4
Els subt\('itols de text simple s\*(Aqescriuran com a fitxers
SRT\&.
.RE
.PP
S_TEXT/SSA, S_TEXT/ASS
.RS 4
Els subt\('itols de text
SSA
i
ASS
s\*(Aqescriuran com a fitxers
SSA/ASS
respectivament\&.
.RE
.PP
S_KATE
.RS 4
Els fluxos
Kate(TM)
s\*(Aqescriuran dins d\*(Aqun contenidor
Ogg(TM)\&.
.RE
.PP
S_VOBSUB
.RS 4
Els subt\('itols
VobSub(TM)
s\*(Aqescriuran com a fitxers
SUB
juntament amb els fitxers d\*(Aq\('index respectius, com a fitxers
IDX\&.
.RE
.PP
S_TEXT/USF
.RS 4
Els subt\('itols de text
USF
s\*(Aqescriuran com a fitxers
USF\&.
.RE
.PP
S_HDMV/PGS
.RS 4
Els subt\('itols
PGS
s\*(Aqescriuran com a fitxers
SUP\&.
.RE
.PP
Etiquetes
.RS 4
Les etiquetes es convertiran al format
XML\&. Aquest \('es el mateix format que admet el
\fBmkvmerge\fR(1)
per a llegir\-les\&.
.RE
.PP
Adjunts
.RS 4
Els adjunts s\*(Aqescriuran al fitxer de sortida tal com estan\&. No es realitzar\(`a cap tipus de conversi\('o\&.
.RE
.PP
Cap\('itols
.RS 4
Els cap\('itols es convertiran al format
XML\&. Aquest \('es el mateix format que admet el
\fBmkvmerge\fR(1)
per a llegir\-los\&. Altrament, es pot generar una versi\('o redu\(:ida amb un format simple a l\*(Aqestil
OGM\&.
.RE
.PP
Codis de temps
.RS 4
Els codis de temps primer estan ordenats i despr\('es la sortida genera un fitxer compatible amb el format timecode v2 preparat per a ser proporcionat al
\fBmkvmerge\fR(1)\&. L\*(Aqextracci\('o a altres formats (v1, v3 i v4) no \('es admesa\&.
.RE
.SH "CODIS DE SORTIDA"
.PP
El
\fBmkvextract\fR(1)
sortir\(`a amb un d\*(Aqaquests tres codis de sortida:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- Aquest codi de sortida significa que l\*(Aqextracci\('o s\*(Aqha realitzat correctament\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- En aquest cas, el
\fBmkvextract\fR(1)
ha generat una sortida amb almenys un av\('is, per\(`o l\*(Aqextracci\('o ha continuat\&. Un av\('is \('es prefixat amb el text \(FoAv\('is:\(Fc\&. Depenent de les q\(:uestions involucrades, els fitxers resultants seran o no correctes\&. L\*(Aqusuari ser\(`a instat a revisar tant els avisos com els fitxers resultants\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- Aquest codi de sortida s\*(Aqempra despr\('es de produir\-se un error\&. El
\fBmkvextract\fR(1)
interrompr\(`a el proc\('es just despr\('es de mostrar el missatge d\*(Aqerror\&. L\*(Aqinterval dels missatges d\*(Aqerror va des d\*(Aqarguments incorrectes a la l\('inia d\*(Aqordres fins a errors de lectura/escriptura en fitxers malmesos\&.
.RE
.SH "ESCAPAR CAR\(`ACTERS ESPECIALS EN EL TEXT"
.PP
Hi ha pocs llocs en els quals els car\(`acters especials en el text puguin o s\*(Aqhagin d\*(Aqescapar\&. Les regles per a l\*(Aqescapament s\('on simples: cada car\(`acter que necessiti ser escapat ser\(`a substitu\(:it amb una barra invertida seguida d\*(Aqun altre car\(`acter\&.
.PP
Les regles s\('on: \(Fo \(Fc (un espai) ser\(`a \(Fo\es\(Fc, \(Fo"\(Fc (cometes dobles) ser\(`a \(Fo\e2\(Fc, \(Fo:\(Fc ser\(`a \(Fo\ec\(Fc, \(Fo#\(Fc ser\(`a \(Fo\eh\(Fc i \(Fo\e\(Fc (una \('unica barra invertida) ser\(`a \(Fo\e\e\(Fc\&.
.SH "VARIABLES D\*(AQENTORN"
.PP
El
\fBmkvextract\fR(1)
empra les variables per omissi\('o que es determinen a la configuraci\('o regional del sistema (p\&. ex\&.,
\fILANG\fR
i la fam\('ilia
\fILC_*\fR)\&. Variables addicionals:
.PP
\fIMKVEXTRACT_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR i la seva forma abreujada \fIMTX_DEBUG\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-debug\fR\&.
.RE
.PP
\fIMKVEXTRACT_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR i la seva forma abreujada \fIMTX_ENGAGE\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-engage\fR\&.
.RE
.PP
\fIMKVEXTRACT_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR i la seva forma abreujada \fIMTX_OPTIONS\fR
.RS 4
El contingut ser\(`a dividit en espais en blanc\&. Les cadenes parcials resultants seran tractades com si haguessin estat passades com a opcions a la l\('inia d\*(Aqordres\&. Si necessiteu passar car\(`acters especials (p\&. ex\&., espais) llavors els haureu d\*(Aqescapar (vegeu
la secci\('o sobre escapar car\(`acters especials en el text)\&.
.RE
.SH "VEGEU TAMB\('E"
.PP
\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvpropedit\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
Sempre trobareu l\*(Aq\('ultima versi\('o a
\m[blue]\fBla p\(`agina de les MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBBunkus, Moritz\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desenvolupador
.RE
.SH "NOTES"
.IP " 1." 4
la p\(`agina de les MKVToolNix
.RS 4
\%https://mkvtoolnix.download/
.RE
