'\" t
.\"     Title: mkvinfo
.\"    Author: Bunkus, Moritz <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-09-11
.\"    Manual: Ordres d\*(Aqusuari
.\"    Source: MKVToolNix 9.4.2
.\"  Language: Catalan
.\"
.TH "MKVINFO" "1" "2016\-09\-11" "MKVToolNix 9\&.4\&.2" "Ordres d\*(Aqusuari"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
mkvinfo \- Imprimeix la informaci\('o quant als elements en els fitxers Matroska(TM)
.SH "SINOPSIS"
.HP \w'\fBmkvinfo\fR\ 'u
\fBmkvinfo\fR [opcions] {nom_fitxer_origen}
.SH "DESCRIPCI\('O"
.PP
Aquest programa mostra una llista de tots els elements continguts en un fitxer
Matroska(TM)\&. La sortida es pot limitar a una llista de pistes en el fitxer incloent informaci\('o sobre els c\(`odecs emprats\&.
.PP
\fB\-g\fR, \fB\-\-gui\fR
.RS 4
Inicia la
IGU\&. Aquesta opci\('o nom\('es estar\(`a disponible si el \(Fomkvinfo\(Fc va ser compilat amb la implementaci\('o per a la
IGU\&.
.RE
.PP
\fB\-c\fR, \fB\-\-checksums\fR
.RS 4
Calcula i mostra la suma de verificaci\('o
\fBAdler32\fR
per a cada fotograma\&. Nom\('es \('es d\*(Aqutilitat per a la depuraci\('o\&.
.RE
.PP
\fB\-s\fR, \fB\-\-summary\fR
.RS 4
Nom\('es mostra un breu resum del que troba o no el
\fBmkvinfo\fR(1)
per a cada element\&.
.RE
.PP
\fB\-t\fR, \fB\-\-track\-info\fR
.RS 4
Mostra les estad\('istiques per a cada pista en el mode loqua\(,c\&. Tamb\('e estableix la loquacitat a 1 si abans era 0\&.
.RE
.PP
\fB\-x\fR, \fB\-\-hexdump\fR
.RS 4
Mostra els primers 16 bytes de cada fotograma com un bolcat hexadecimal\&.
.RE
.PP
\fB\-X\fR, \fB\-\-full\-hexdump\fR
.RS 4
Mostra tots els bytes de cada fotograma com un bolcat hexadecimal\&.
.RE
.PP
\fB\-z\fR, \fB\-\-size\fR
.RS 4
Mostra la mida de cada element incloent la seva cap\(,calera\&.
.RE
.PP
\fB\-\-command\-line\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Estableix el joc de car\(`acters al qual convertir les cadenes indicades des de la l\('inia d\*(Aqordres\&. Per omissi\('o ser\(`a el joc de car\(`acters donat per la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Estableix el joc de car\(`acters al qual convertir les cadenes de la sortida\&. Per omissi\('o ser\(`a el joc de car\(`acters donat per la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fInom_fitxer\fR
.RS 4
Escriu tots els missatges al
\fInom_fitxer\fR
en lloc de a la consola\&. Si b\('e aix\(`o es pot fer f\(`acilment amb la redirecci\('o de la sortida, hi ha casos en qu\(`e cal aquesta opci\('o: quan el terminal torna a interpretar la sortida abans d\*(Aqescriure\-la a un fitxer\&. Es respectar\(`a el joc de car\(`acters establert amb
\fB\-\-output\-charset\fR\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIcodi\fR
.RS 4
For\(,ca l\*(Aq\('us de les traduccions pel
\fIcodi\fR
d\*(Aqidioma (p\&. ex\&., \(Fode_DE\(Fc per a les traduccions en alemany)\&. Introduint \(Folist\(Fc com a
\fIcodi\fR, es far\(`a que el programa ofereixi a la sortida una llista de les traduccions disponibles\&.
.RE
.PP
\fB\-\-debug\fR \fItema\fR
.RS 4
Activa la depuraci\('o per a una caracter\('istica espec\('ifica\&. Aquesta opci\('o nom\('es \('es \('util pels desenvolupadors\&.
.RE
.PP
\fB\-\-engage\fR \fIcaracter\('istica\fR
.RS 4
Activa les caracter\('istiques experimentals\&. Es pot sol\(mdlicitar una llista de les caracter\('istiques disponibles amb
\fBmkvinfo \-\-engage list\fR\&. Aquestes caracter\('istiques no estan destinades a ser emprades en situacions normals\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
Activa el mode IGU\&. En aquest mode, les l\('inies surten amb un format especial que pot explicar\-vos el que est\(`a succeint per tal de controlar la IGU\&. Aquests missatges segueixen el format \(Fo#IGU#missatge\(Fc\&. El missatge pot estar seguit per parells clau/valor com \(Fo#IGU#missatge#clau1=valor1#clau2=valor2\&...\(Fc\&. Ni els missatges ni les claus seran tradu\(:ides, sempre sortiran en angl\(`es\&.
.sp
Aquest ajustament no t\('e res a veure amb el par\(`ametre
\fB\-\-gui\fR
el qual causa que el mkvinfo mostri la seva pr\(`opia IGU\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Ser m\('es loqua\(,c\&. Vegeu la secci\('o sobre
els nivells de loquacitat
per a una descripci\('o de quina informaci\('o sortir\(`a en cada nivell\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra la informaci\('o d\*(Aq\('us i surt\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Mostra la informaci\('o sobre la versi\('o i surt\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Comprova en l\('inia si hi ha nous llan\(,caments per baixar\-los des de l\*(AqURL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Es generaran quatre l\('inies amb l\*(Aqestil
clau=valor: l\*(AqURL des d\*(Aqon s\*(Aqha obtingut la informaci\('o (clau
version_check_url), la versi\('o actualment en execuci\('o (clau
running_version), la versi\('o de l\*(Aq\('ultim llan\(,cament (clau
available_version) i l\*(AqURL per a la baixada (clau
download_url)\&.
.sp
Despr\('es el programa sortir\(`a amb un codi de sortida de 0 si no hi ha cap llan\(,cament m\('es recent disponible, amb 1 si hi ha disponible una nova versi\('o i amb 2 si s\*(Aqha produ\(:it algun error (p\&. ex\&., si no s\*(Aqha pogut recuperar la informaci\('o sobre l\*(Aqactualitzaci\('o)\&.
.sp
Aquesta opci\('o nom\('es estar\(`a disponible si el programa va ser constru\(:it amb la implementaci\('o per a \(Folibcurl\(Fc\&.
.RE
.PP
\fB@\fR\fIfitxer_opcions\fR
.RS 4
Llegeix arguments addicionals per a la l\('inia d\*(Aqordres des del
\fIfitxer_opcions\fR\&. Les l\('inies que tinguin com a primer car\(`acter un coixinet (#) seran tractades com a comentaris i ignorades\&. Els espais en blanc al comen\(,cament i final de la l\('inia seran descartats\&. Cada l\('inia haur\(`a de contenir exactament una opci\('o\&.
.sp
Es poden escapar diversos car\(`acters, p\&. ex\&., si necessiteu que una l\('inia que comen\(,ca amb un coixinet \(Fo#\(Fc, no sigui interpretada com un comentari\&. Les regles es descriuen a
la secci\('o sobre escapar en el text\&.
.sp
La l\('inia d\*(Aqordres \(Fo\fBmkvinfo \-v \-v entrada\&.mkv \-\-redirect\-output informaci\('o\&.txt\fR\(Fc es pot convertir en el seg\(:uent fitxer d\*(Aqopcions:
.sp
.if n \{\
.RS 4
.\}
.nf
# Ser m\('es loqua\(,c
\-v
\-v
# Analitza entrada\&.mkv
entrada\&.mkv
# i escriu la sortida a informaci\('o\&.txt
\-\-redirect\-output
informaci\('o\&.txt
.fi
.if n \{\
.RE
.\}
.RE
.SH "NIVELLS DE LOQUACITAT"
.PP
L\*(Aqopci\('o
\fB\-v\fR
es pot emprar per incrementar el nivell de loquacitat del
\fBmkvinfo\fR(1)
i imprimir m\('es informaci\('o sobre el fitxer actual\&.
.PP
En el nivell 0, el
\fBmkvinfo\fR(1)
nom\('es imprimir\(`a les cap\(,caleres de la pista que troba i els seus tipus\&. El
\fBmkvinfo\fR(1)
sortir\(`a tan aviat s\*(Aqhagin analitzat completament les cap\(,caleres (m\('es t\(`ecnic: tan aviat com es trobi el primer cl\('uster)\&. En aquest nivell, la cerca d\*(Aqentrades de cap\(,calera i els \('indexs no ser\(`an mostrats \-encara que es trobin al capdavant de la informaci\('o de la pista\-\&.
.PP
En el nivell 1, el
\fBmkvinfo\fR(1)
tamb\('e imprimir\(`a tots els elements
Matroska(TM)
trobats en tot el fitxer mentre es realitzava la cerca d\*(Aqentrades de cap\(,calera i de l\*(Aq\('index\&. Si est\(`a habilitat el mode resum, llavors el
\fBmkvinfo\fR(1)
tamb\('e generar\(`a la posici\('o del fotograma\&.
.PP
En el nivell 2, el
\fBmkvinfo\fR(1)
tamb\('e imprimir\(`a la cerca de les entrades de cap\(,calera, les entrades de l\*(Aq\('index i la posici\('o en el fitxer en la que s\*(Aqha trobat cada element del
Matroska(TM)\&.
.PP
En el nivell 3 i superiors, el
\fBmkvinfo\fR(1)
imprimir\(`a alguna informaci\('o que no est\(`a directament relacionada amb l\*(Aqelement del
Matroska(TM)\&. De la resta d\*(Aqelements nom\('es s\*(Aqimprimiran dades sobre que s\*(Aqhan trobat\&. El nivell 3 tamb\('e afegeix meta informaci\('o per tal de facilitar la depuraci\('o (llegiu: est\(`a indicat per a desenvolupadors)\&. Totes les l\('inies escrites per al nivell 3 estan tancades entre claud\(`ators per a facilitar\-ne el filtratge\&.
.SH "CONVERSI\('O PER A FITXERS DE TEXT I JOCS DE CAR\(`ACTERS"
.PP
Per a un debat en profunditat sobre com manipula la suite MKVToolNix les conversions entre els jocs de car\(`acters, codifica l\*(Aqentrada/sortida, codifica la l\('inia d\*(Aqordres i codifica a la consola, si us plau, vegeu la secci\('o anomenada de la mateixa manera a la p\(`agina man del
\fBmkvmerge\fR(1)\&.
.SH "CODIS DE SORTIDA"
.PP
El
\fBmkvinfo\fR(1)
sortir\(`a amb un d\*(Aqaquests tres codis de sortida:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- Aquest codi de sortida significa que l\*(Aqexecuci\('o s\*(Aqha realitzat correctament\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- En aquest cas, el
\fBmkvinfo\fR(1)
ha generat una sortida amb almenys un av\('is, per\(`o continua executant\-se\&. Un av\('is \('es prefixat amb el text \(FoAv\('is:\(Fc\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- Aquest codi de sortida s\*(Aqempra despr\('es de produir\-se un error\&. El
\fBmkvinfo\fR(1)
interrompr\(`a el proc\('es just despr\('es de mostrar el missatge d\*(Aqerror\&. L\*(Aqinterval dels missatges d\*(Aqerror va des d\*(Aqarguments incorrectes a la l\('inia d\*(Aqordres fins a errors de lectura/escriptura en fitxers malmesos\&.
.RE
.SH "ESCAPAR CAR\(`ACTERS ESPECIALS EN EL TEXT"
.PP
Hi ha pocs llocs en els quals els car\(`acters especials en el text puguin o s\*(Aqhagin d\*(Aqescapar\&. Les regles per a l\*(Aqescapament s\('on simples: cada car\(`acter que necessiti ser escapat ser\(`a substitu\(:it amb una barra invertida seguida d\*(Aqun altre car\(`acter\&.
.PP
Les regles s\('on: \(Fo \(Fc (un espai) ser\(`a \(Fo\es\(Fc, \(Fo"\(Fc (cometes dobles) ser\(`a \(Fo\e2\(Fc, \(Fo:\(Fc ser\(`a \(Fo\ec\(Fc, \(Fo#\(Fc ser\(`a \(Fo\eh\(Fc i \(Fo\e\(Fc (una \('unica barra invertida) ser\(`a \(Fo\e\e\(Fc\&.
.SH "VARIABLES D\*(AQENTORN"
.PP
El
\fBmkvinfo\fR(1)
empra les variables per omissi\('o que es determinen a la configuraci\('o regional del sistema (p\&. ex\&.,
\fILANG\fR
i la fam\('ilia
\fILC_*\fR)\&. Variables addicionals:
.PP
\fIMKVINFO_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR i la seva forma abreujada \fIMTX_DEBUG\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-debug\fR\&.
.RE
.PP
\fIMKVINFO_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR i la seva forma abreujada \fIMTX_ENGAGE\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-engage\fR\&.
.RE
.PP
\fIMKVINFO_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR i la seva forma abreujada \fIMTX_OPTIONS\fR
.RS 4
El contingut ser\(`a dividit en espais en blanc\&. Les cadenes parcials resultants seran tractades com si haguessin estat passades com a opcions a la l\('inia d\*(Aqordres\&. Si necessiteu passar car\(`acters especials (p\&. ex\&., espais) llavors els haureu d\*(Aqescapar (vegeu
la secci\('o sobre escapar car\(`acters especials en el text)\&.
.RE
.SH "VEGEU TAMB\('E"
.PP
\fBmkvmerge\fR(1),
\fBmkvextract\fR(1),
\fBmkvpropedit\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
Sempre trobareu l\*(Aq\('ultima versi\('o a
\m[blue]\fBla p\(`agina de les MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBBunkus, Moritz\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desenvolupador
.RE
.SH "NOTES"
.IP " 1." 4
la p\(`agina de les MKVToolNix
.RS 4
\%https://mkvtoolnix.download/
.RE
