'\" t
.\"     Title: mkvpropedit
.\"    Author: Bunkus, Moritz <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2015-11-29
.\"    Manual: Ordres d\*(Aqusuari
.\"    Source: MKVToolNix 8.6.1
.\"  Language: Catalan
.\"
.TH "MKVPROPEDIT" "1" "2015\-11\-29" "MKVToolNix 8\&.6\&.1" "Ordres d\*(Aqusuari"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
mkvpropedit \- Modifica les propietats dels fitxers Matroska(TM) existents que no han completat el multiplexat
.SH "SINOPSIS"
.HP \w'\fBmkvpropedit\fR\ 'u
\fBmkvpropedit\fR [opcions] {nom_fitxer_origen} {accions}
.SH "DESCRIPCI\('O"
.PP
This program analyses an existing
Matroska(TM)
file and modifies some of its properties\&. Then it writes those modifications to the existing file\&. Among the properties that can be changed are the segment information elements (e\&.g\&. the title) and the track headers (e\&.g\&. the language code, \*(Aqdefault track\*(Aq flag or the name)\&.
.PP
Opcions:
.PP
\fB\-l\fR, \fB\-\-list\-property\-names\fR
.RS 4
Lists all known and editable property names, their type (string, integer, boolean etc) and a short description\&. The program exits afterwards\&. Therefore the
\fIsource\-filename\fR
parameter does not have to be supplied\&.
.RE
.PP
\fB\-p\fR, \fB\-\-parse\-mode\fR \fImode\fR
.RS 4
Sets the parse mode\&. The parameter \*(Aq\fImode\fR\*(Aq can either be \*(Aqfast\*(Aq (which is also the default) or \*(Aqfull\*(Aq\&. The \*(Aqfast\*(Aq mode does not parse the whole file but uses the meta seek elements for locating the required elements of a source file\&. In 99% of all cases this is enough\&. But for files that do not contain meta seek elements or which are damaged the user might have to set the \*(Aqfull\*(Aq parse mode\&. A full scan of a file can take a couple of minutes while a fast scan only takes seconds\&.
.RE
.PP
Actions that deal with track and segment info properties:
.PP
\fB\-e\fR, \fB\-\-edit\fR \fIselector\fR
.RS 4
Sets the
Matroska(TM)
file section (segment information or a certain track\*(Aqs headers) that all following
add,
set
and
delete
actions operate on\&. This option can be used multiple times in order to make modifications to more than one element\&.
.sp
By default
\fBmkvpropedit\fR(1)
will edit the segment information section\&.
.sp
See the section about
edit selectors
for a full description of the syntax\&.
.RE
.PP
\fB\-a\fR, \fB\-\-add\fR \fInom\fR=\fIvalor\fR
.RS 4
Adds a property
\fIname\fR
with the value
\fIvalue\fR\&. The property will be added even if such a property exists already\&. Note that most properties are unique and cannot occur more than once\&.
.RE
.PP
\fB\-s\fR, \fB\-\-set\fR \fInom\fR=\fIvalor\fR
.RS 4
Sets all occurrences of the property
\fIname\fR
to the value
\fIvalue\fR\&. If no such property exists then it will be added\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR \fInom\fR
.RS 4
Deletes all occurrences of the property
\fIname\fR\&. Note that some properties are required and cannot be deleted\&.
.RE
.PP
Actions that deal with tags and chapters:
.PP
\fB\-t\fR, \fB\-\-tags\fR \fIselector\fR:\fInom_fitxer\fR
.RS 4
Afegeix o substitueix les etiquetes al fitxer amb el
nom_fitxer
o l\*(Aqelimina si el
nom_fitxer
est\(`a buit\&. El
\fBmkvpropedit\fR(1)
llegir\(`a els mateixos formats d\*(Aqetiquetes en XML que pugui llegir el
\fBmkvmerge\fR(1)\&.
.sp
The
\fIselector\fR
must be one of the words
\fBall\fR,
\fBglobal\fR
or
\fBtrack\fR\&. For
\fBall\fR\fBmkvpropedit\fR(1)
will replace or remove all tags in a file\&. With
\fBglobal\fR
only global tags will be replaced or removed\&.
.sp
With
\fBtrack\fR\fBmkvpropedit\fR(1)
will replace tags for a specific track\&. Additionally the tags read from
filename
will be assigned to the same track\&. The track is specified in the same way
edit selectors
are specified (see below), e\&.g\&.
\-\-tags track:a1:new\-audio\-tags\&.xml\&.
.RE
.PP
\fB\-\-delete\-track\-statistics\-tags\fR
.RS 4
Deletes all existing track statistics tags from a file\&. If the file doesn\*(Aqt contain track statistics tags then it won\*(Aqt be modified\&.
.RE
.PP
\fB\-c\fR, \fB\-\-chapters\fR \fInom_fitxer\fR
.RS 4
Afegeix o substitueix els cap\('itols al fitxer amb el
nom_fitxer
o elimina\*(Aql si el
nom_fitxer
est\(`a buit\&. El
\fBmkvpropedit\fR(1)
llegir\(`a els mateixos formats de cap\('itols simple i en XML que pugui llegir el
\fBmkvmerge\fR(1)\&.
.RE
.PP
Accions per a manejar els adjunts:
.PP
\fB\-\-add\-attachment\fR \fInom_fitxer\fR
.RS 4
Adds a new attachment from
\fIfilename\fR\&.
.sp
If the option
\fB\-\-attachment\-name\fR
has been used prior to this option then its value is used as the new attachment\*(Aqs name\&. Otherwise it is derived from
\fIfilename\fR\&.
.sp
If the option
\fB\-\-attachment\-mime\-type\fR
has been used prior to this option then its value is used as the new attachment\*(Aqs MIME type\&. Otherwise it is auto\-detected from the content of
\fIfilename\fR\&.
.sp
If the option
\fB\-\-attachment\-description\fR
has been used prior to this option then its value is used as the new attachment\*(Aqs description\&. Otherwise no description will be set\&.
.sp
If the option
\fB\-\-attachment\-uid\fR
has been used prior to this option then its value is used as the new attachment\*(Aqs UID\&. Otherwise a random UID will be generated automatically\&.
.RE
.PP
\fB\-\-replace\-attachment\fR \fIselector\fR:\fInom_fitxer\fR
.RS 4
Replaces one or more attachments that match
\fIselector\fR
with the file
\fIfilename\fR\&. If more than one existing attachment matches
\fIselector\fR
then all of their contents will be replaced by the content of
\fIfilename\fR\&.
.sp
The
\fIselector\fR
can have one of four forms\&. They\*(Aqre exlained below in the section
attachment selectors\&.
.sp
If the option
\fB\-\-attachment\-name\fR
has been used prior to this option then its value is set as the new name for each modified attachment\&. Otherwise the names aren\*(Aqt changed\&.
.sp
If the option
\fB\-\-attachment\-mime\-type\fR
has been used prior to this option then its value is set as the new MIME type for each modified attachment\&. Otherwise the MIME types aren\*(Aqt changed\&.
.sp
If the option
\fB\-\-attachment\-description\fR
has been used prior to this option then its value is set as the new description for each modified attachment\&. Otherwise the descriptions aren\*(Aqt changed\&.
.sp
If the option
\fB\-\-attachment\-uid\fR
has been used prior to this option then its value is set as the new UID for each modified attachment\&. Otherwise the UIDs aren\*(Aqt changed\&.
.RE
.PP
\fB\-\-update\-attachment\fR \fIselector\fR
.RS 4
Sets the properties of one or more attachments that match
\fIselector\fR\&. If more than one existing attachment matches
\fIselector\fR
then all of their properties will be updated\&.
.sp
The
\fIselector\fR
can have one of four forms\&. They\*(Aqre exlained below in the section
attachment selectors\&.
.sp
If the option
\fB\-\-attachment\-name\fR
has been used prior to this option then its value is set as the new name for each modified attachment\&. Otherwise the names aren\*(Aqt changed\&.
.sp
If the option
\fB\-\-attachment\-mime\-type\fR
has been used prior to this option then its value is set as the new MIME type for each modified attachment\&. Otherwise the MIME types aren\*(Aqt changed\&.
.sp
If the option
\fB\-\-attachment\-description\fR
has been used prior to this option then its value is set as the new description for each modified attachment\&. Otherwise the descriptions aren\*(Aqt changed\&.
.sp
If the option
\fB\-\-attachment\-uid\fR
has been used prior to this option then its value is set as the new UID for each modified attachment\&. Otherwise the UIDs aren\*(Aqt changed\&.
.RE
.PP
\fB\-\-delete\-attachment\fR \fIselector\fR
.RS 4
Deletes one or more attachments that match
\fIselector\fR\&.
.sp
The
\fIselector\fR
can have one of four forms\&. They\*(Aqre exlained below in the section
attachment selectors\&.
.RE
.PP
Options for attachment actions:
.PP
\fB\-\-attachment\-name\fR \fInom\fR
.RS 4
Estableix el nom a usar per a les opcions
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
\fB\-\-attachment\-mime\-type\fR \fItipus_MIME\fR
.RS 4
Estableix el tipus MIME a usar per a les opcions
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
\fB\-\-attachment\-description\fR \fIdescripci\('o\fR
.RS 4
Estableix la descripci\('o a usar per a les opcions
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
Altres opcions:
.PP
\fB\-\-command\-line\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Estableix el joc de car\(`acters al qual convertir les cadenes donades des de la l\('inia d\*(Aqordres\&. Per omissi\('o ser\(`a el joc de car\(`acters donat per la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Estableix el joc de car\(`acters al qual convertir les cadenes donades per la sortida\&. Per omissi\('o ser\(`a el joc de car\(`acters establert a la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fInom_fitxer\fR
.RS 4
Escriu tots els missatges al fitxer
\fInom_fitxer\fR
en lloc de a la consola\&. Si b\('e aix\(`o es pot fer f\(`acilment amb la redirecci\('o de la sortida, hi ha casos en qu\(`e cal aquesta opci\('o: quan el terminal reinterpreta la sortida abans d\*(Aqescriure\-la a un fitxer\&. Es respecta el joc de car\(`acters establert amb
\fB\-\-output\-charset\fR\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIcodi\fR
.RS 4
For\(,ca l\*(Aq\('us de les traduccions pel
\fIcodi\fR
d\*(Aqidioma (p\&. ex\&., \(Fode_DE\(Fc per a les traduccions en alemany)\&. Tot i que \('es preferible usar les variables d\*(Aqentorn
\fILANG\fR,
\fILC_MESSAGES\fR
i
\fILC_ALL\fR\&. Introduint \(Folist\(Fc com a
\fIcodi\fR
far\(`a que el
\fBmkvextract\fR(1)
ofereixi a la sortida, una llista de les traduccions disponibles\&.
.RE
.PP
\fB\-\-debug\fR \fItema\fR
.RS 4
Activa la depuraci\('o per a una caracter\('istica espec\('ifica\&. Aquesta opci\('o nom\('es \('es \('util per als desenvolupadors\&.
.RE
.PP
\fB\-\-engage\fR \fIcaracter\('istica\fR
.RS 4
Activa les caracter\('istiques experimentals\&. Es pot sol\(mdlicitar una llista de les caracter\('istiques disponibles amb
\fBmkvpropedit \-\-engage list\fR\&. Aquestes caracter\('istiques no estan destinades a ser emprades en situacions normals\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
Activa el mode IGU\&. En aquest mode, les l\('inies surten amb un format especial que pot explicar\-vos el que est\(`a succeint per tal de controlar la IGU\&. Aquests missatges segueixen el format \(Fo#GUI#message\(Fc\&. El missatge pot estar seguit per parells clau/valor com a \(Fo#GUI#message#key1=value1#key2=value2\&...\(Fc\&. Ni els missatges ni les claus seran tradu\(:its, sempre sortiran en angl\(`es\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Ser\(`a detallat i mostrar\(`a tots els elements importants del
Matroska(TM)
a mesura que es llegeixin\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra la informaci\('o d\*(Aq\('us i surt\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Mostra la informaci\('o sobre la versi\('o i surt\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Comprova en l\('inia si hi ha nous llan\(,caments per baixar\-los des de l\*(AqURL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Es generaran quatre l\('inies amb l\*(Aqestil
key=valor: l\*(AqURL des d\*(Aqon s\*(Aqha obtingut la informaci\('o (clau
version_check_url), la versi\('o actualment en execuci\('o (clau
running_version), la versi\('o de l\*(Aq\('ultim llan\(,cament (clau
available_version) i l\*(AqURL per a la baixada (clau
download_url)\&.
.sp
Despr\('es el programa sortir\(`a amb un codi de sortida de 0 si no hi ha cap llan\(,cament m\('es recent disponible, amb 1 si hi ha disponible una nova versi\('o i amb 2 si s\*(Aqha produ\(:it un error (p\&. ex\&., si no s\*(Aqha pogut recuperar la informaci\('o sobre l\*(Aqactualitzaci\('o)\&.
.sp
Aquesta opci\('o nom\('es estar\(`a disponible si el programa va ser constru\(:it amb la implementaci\('o per a \(Folibcurl\(Fc\&.
.RE
.PP
\fB@\fR\fIfitxer_opcions\fR
.RS 4
Llegeix arguments addicionals per a la l\('inia d\*(Aqordres des del fitxer
\fIfitxer_opcions\fR\&. Les l\('inies que tinguin com a primer car\(`acter un coixinet (#) seran tractades com a comentaris i ignorades\&. Els espais en blanc al comen\(,cament i final de la l\('inia seran descartats\&. Cada l\('inia haur\(`a de contenir exactament una opci\('o\&.
.sp
Es poden interpretar diversos car\(`acters com d\*(Aqescapament, p\&. ex\&., si necessiteu que una l\('inia que comen\(,ca amb un coixinet \(Fo#\(Fc, no sigui interpretada com un comentari\&. Les regles es descriuen a
la secci\('o sobre escapar en el text\&.
.sp
La l\('inia d\*(Aqordres \(Fo\fBmkvpropedit origen\&.mkv \-\-edit track:a2 \-\-set name=Comentaris\fR\(Fc es pot convertir en el seg\(:uent fitxer d\*(Aqopcions:
.sp
.if n \{\
.RS 4
.\}
.nf
# Modifica origen\&.mkv
origen\&.mkv
# Edita la segona pista d\*(Aq\(`audio
\-\-edit
track:a2
# i estableix el t\('itol a \(FoComentaris\(Fc
\-\-set
name=Comentaris
.fi
.if n \{\
.RE
.\}
.RE
.SH "EDITAR ELS SELECTORS"
.PP
The
\fB\-\-edit\fR
option sets the
Matroska(TM)
file section (segment information or a certain track\*(Aqs headers) that all following
add,
set
and
delete
actions operate on\&. This stays valid until the next
\fB\-\-edit\fR
option is found\&. The argument to this option is called the edit selector\&.
.PP
By default
\fBmkvpropedit\fR(1)
will edit the segment information section\&.
.SS "Informaci\('o del segment"
.PP
The segment information can be selected with one of these three words: \*(Aqinfo\*(Aq, \*(Aqsegment_info\*(Aq or \*(Aqsegmentinfo\*(Aq\&. It contains properties like the segment title or the segment
UID\&.
.SS "Cap\(,caleres de la pista"
.PP
Track headers can be selected with a slightly more complex selector\&. All variations start with \*(Aqtrack:\*(Aq\&. The track header properties include elements like the language code, \*(Aqdefault track\*(Aq flag or the track\*(Aqs name\&.
.PP
\fBtrack:\fR\fIn\fR
.RS 4
If the parameter
\fIn\fR
is a number then the
\fIn\fRth track will be selected\&. The track order is the same that
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
option outputs\&.
.sp
La numeraci\('o comen\(,ca per l\*(Aq1\&.
.RE
.PP
\fBtrack:\fR\fIt\fR\fIn\fR
.RS 4
If the parameter starts with a single character
\fIt\fR
followed by a
\fIn\fR
then the
\fIn\fRth track of a specific track type will be selected\&. The track type parameter
\fIt\fR
must be one of these four characters: \*(Aqa\*(Aq for an audio track, \*(Aqb\*(Aq for a button track, \*(Aqs\*(Aq for a subtitle track and \*(Aqv\*(Aq for a video track\&. The track order is the same that
\fBmkvmerge\fR(1)\*(Aqs
\fB\-\-identify\fR
option outputs\&.
.sp
La numeraci\('o comen\(,ca per l\*(Aq1\&.
.RE
.PP
\fBtrack:\fR=\fIUID\fR
.RS 4
If the parameter starts with a \*(Aq=\*(Aq followed by a number
\fIuid\fR
then the track whose track
UID
element equals this
\fIuid\fR\&. Track
UIDs
can be obtained with
\fBmkvinfo\fR(1)\&.
.RE
.PP
\fBtrack:\fR@\fIn\('umero\fR
.RS 4
If the parameter starts with a \*(Aq@\*(Aq followed by a number
\fInumber\fR
then the track whose track number element equals this
\fInumber\fR\&. Track number can be obtained with
\fBmkvinfo\fR(1)\&.
.RE
.SS "Notes"
.PP
Due to the nature of the track edit selectors it is possible that several selectors actually match the same track headers\&. In such cases all actions for those edit selectors will be combined and executed in the order in which they\*(Aqre given on the command line\&.
.SH "SELECTORS DE L'ADJUNT"
.PP
An attachment selector is used with the two actions
\fB\-\-replace\-attachment\fR
and
\fB\-\-delete\-attachment\fR\&. It can have one of the following four forms:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Selection by attachment ID\&. In this form the selector is simply a number, the attachment\*(Aqs ID as output by
\fBmkvmerge\fR(1)\*(Aqs identification command\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Selection by attachment UID (unique ID)\&. In this form the selector is the equal sign
=
followed by a number, the attachment\*(Aqs unique ID as output by
\fBmkvmerge\fR(1)\*(Aqs verbose identification command\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Selection by attachment name\&. In this form the selector is the literal word
name:
followed by the existing attachment\*(Aqs name\&. If this selector is used with
\fB\-\-replace\-attachment\fR
then colons within the name to match must be escaped as
\ec\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Selection by MIME type\&. In this form the selector is the literal word
mime\-type:
followed by the existing attachment\*(Aqs MIME type\&. If this selector is used with
\fB\-\-replace\-attachment\fR
then colons within the MIME type to match must be escaped as
\ec\&.
.RE
.SH "EXEMPLES"
.PP
The following example edits a file called \*(Aqmovie\&.mkv\*(Aq\&. It sets the segment title and modifies the language code of an audio and a subtitle track\&. Note that this example can be shortened by leaving out the first
\fB\-\-edit\fR
option because editing the segment information element is the default for all options found before the first
\fB\-\-edit\fR
option anyway\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-edit info \-\-set "title=La pel\(mdl\('icula" \-\-edit track:a1 \-\-set language=cat \-\-edit track:a2 \-\-set language=ita
.fi
.if n \{\
.RE
.\}
.PP
The second example removes the \*(Aqdefault track flag\*(Aq from the first subtitle track and sets it for the second one\&. Note that
\fBmkvpropedit\fR(1), unlike
\fBmkvmerge\fR(1), does not set the \*(Aqdefault track flag\*(Aq of other tracks to \*(Aq0\*(Aq if it is set to \*(Aq1\*(Aq for a different track automatically\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-edit track:s1 \-\-set flag\-default=0 \-\-edit track:s2 \-\-set flag\-default=1
.fi
.if n \{\
.RE
.\}
.PP
Substituir les etiquetes per a la segona pista de subt\('itols en un arxiu es veu aix\('i:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-tags track:s2:etiquetes_subt\('itols_noves\&.xml
.fi
.if n \{\
.RE
.\}
.PP
Eliminar totes les etiquetes requereix ometre el nom del fitxer:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-tags all:
.fi
.if n \{\
.RE
.\}
.PP
Substituir els cap\('itols en un fitxer es veu aix\('i:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-chapters cap\('itols_nous\&.xml
.fi
.if n \{\
.RE
.\}
.PP
Eliminar tots els cap\('itols requereix ometre el nom del fitxer:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-chapters \*(Aq\*(Aq
.fi
.if n \{\
.RE
.\}
.PP
Afegir un fitxer de tipus de lletra (Arial\&.ttf) com un adjunt:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-add\-attachment Arial\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Afegir un fitxer de tipus de lletra (89719823\&.ttf) com un adjunt i proporcionar alguna informaci\('o de com \('es el tipus de lletra Arial:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-attachment\-name Arial\&.ttf \-\-attachment\-description \*(AqEl tipus de lletra Arial com a tipus de lletra TrueType\*(Aq \-\-attachment\-mime\-type application/x\-truetype\-font \-\-add\-attachment 89719823\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Substituir un fitxer adjunt de tipus de lletra (Comic\&.ttf) per un altre (Arial\&.ttf):
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-attachment\-name Arial\&.ttf \-\-attachment\-description \*(AqEl tipus de lletra Arial com a tipus de lletra TrueType\*(Aq \-\-replace\-attachment name:Comic\&.ttf:Arial\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Eliminar el segon fitxer adjunt, sigui el que sigui:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-delete\-attachment 2
.fi
.if n \{\
.RE
.\}
.PP
Eliminar tots els tipus de lletra adjuntats segons el tipus MIME:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-delete\-attachment mime\-type:application/x\-truetype\-font
.fi
.if n \{\
.RE
.\}
.SH "CODIS DE SORTIDA"
.PP
El
\fBmkvpropedit\fR(1)
sortir\(`a amb un d\*(Aqaquests tres codis de sortida:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- Aquest codi de sortida significa que la modificaci\('o s\*(Aqha realitzat correctament\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- En aquest cas, el
\fBmkvpropedit\fR(1)
ha generat una sortida amb almenys un av\('is, per\(`o la modificaci\('o ha continuat\&. Un av\('is \('es prefixat amb el text \(FoAv\('is:\(Fc\&. Depenent de les q\(:uestions involucrades, els fitxers resultants seran o no correctes\&. L\*(Aqusuari ser\(`a instat a revisar tant els avisos com els fitxers\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- Aquest codi de sortida s\*(Aqempra despr\('es de produir\-se un error\&. El
\fBmkvpropedit\fR(1)
interrompr\(`a el proc\('es just despr\('es de mostrar el missatge d\*(Aqerror\&. L\*(Aqinterval dels missatges d\*(Aqerror va des d\*(Aqarguments incorrectes a la l\('inia d\*(Aqordres fins a errors de lectura/escriptura als fitxers malmesos\&.
.RE
.SH "CONVERSI\('O PER A FITXERS DE TEXT I JOCS DE CAR\(`ACTERS"
.PP
Per a un debat en profunditat sobre com manipula la suite MKVToolNix les conversions dels jocs de car\(`acters, codifica l\*(Aqentrada/sortida i codifica la l\('inia d\*(Aqordres i codifica a la consola, si us plau, vegeu la secci\('o anomenada de la mateixa manera a la p\(`agina man del
\fBmkvmerge\fR(1)\&.
.SH "CAR\(`ACTERS ESPECIALS D'ESCAPAMENT EN EL TEXT"
.PP
Hi ha pocs llocs en els quals els car\(`acters especials en el text puguin o s\*(Aqhagin d\*(Aqescapar\&. Les regles de l\*(Aqescapament s\('on simples: cada car\(`acter que necessiti ser escapat ser\(`a substitu\(:it amb una barra invertida seguida d\*(Aqun altre car\(`acter\&.
.PP
Les regles s\('on: \(Fo \(Fc (un espai) ser\(`a \(Fo\es\(Fc, \(Fo"\(Fc (cometes) ser\(`a \(Fo\e2\(Fc, \(Fo:\(Fc ser\(`a \(Fo\ec\(Fc, \(Fo#\(Fc ser\(`a \(Fo\eh\(Fc i \(Fo\e\(Fc (una \('unica barra invertida) ser\(`a \(Fo\e\e\(Fc\&.
.SH "VARIABLES D'ENTORN"
.PP
El
\fBmkvpropedit\fR(1)
usa les variables per omissi\('o que es determinen a la configuraci\('o regional del sistema (p\&. ex\&.,
\fILANG\fR
i la fam\('ilia
\fILC_*\fR)\&. Variables addicionals:
.PP
\fIMKVPROPEDIT_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR i la seva forma abreujada \fIMTX_DEBUG\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-debug\fR\&.
.RE
.PP
\fIMKVPROPEDIT_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR i la seva forma abreujada \fIMTX_ENGAGE\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-engage\fR\&.
.RE
.PP
\fIMKVPROPEDIT_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR i la seva forma abreujada \fIMTX_OPTIONS\fR
.RS 4
El contingut ser\(`a dividit en espais en blanc\&. Les cadenes parcials resultants seran tractades com si haguessin estat passades com a opcions a la l\('inia d\*(Aqordres\&. Si necessiteu passar car\(`acters especials (p\&. ex\&., espais) llavors els haureu d\*(Aqescapar (vegeu
la secci\('o car\(`acters especials d'escapament en el text)\&.
.RE
.SH "VEGEU TAMB\('E"
.PP
\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvextract\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
The latest version can always be found at
\m[blue]\fBthe MKVToolNix homepage\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBBunkus, Moritz\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desenvolupador
.RE
.SH "NOTES"
.IP " 1." 4
the MKVToolNix homepage
.RS 4
\%https://mkvtoolnix.download/
.RE
