'\" t
.\"     Title: mkvpropedit
.\"    Author: Bunkus, Moritz <moritz@bunkus.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2016-12-27
.\"    Manual: Ordres d\*(Aqusuari
.\"    Source: MKVToolNix 9.7.1
.\"  Language: Catalan
.\"
.TH "MKVPROPEDIT" "1" "2016\-12\-27" "MKVToolNix 9\&.7\&.1" "Ordres d\*(Aqusuari"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
mkvpropedit \- Modifica les propietats dels fitxers Matroska(TM) existents sense un multiplexat complet
.SH "SINOPSIS"
.HP \w'\fBmkvpropedit\fR\ 'u
\fBmkvpropedit\fR [opcions] {nom_fitxer_origen} {accions}
.SH "DESCRIPCI\('O"
.PP
Aquest programa analitza un fitxer
Matroska(TM)
i modifica algunes de les seves propietats\&. Despr\('es escriu aquestes modificacions en el fitxer existent\&. Entre les propietats que es poden modificar es troben els elements sobre la informaci\('o del segment (p\&. ex\&., el t\('itol), les cap\(,caleres de les pistes (p\&. ex\&., el codi de l\*(Aqidioma, l\*(Aqetiqueta \(Fopista per omissi\('o\(Fc o el nom)\&.
.PP
Opcions:
.PP
\fB\-l\fR, \fB\-\-list\-property\-names\fR
.RS 4
Llista tots els noms de propietat coneguts i editables, el seu tipus (cadena, enter, boole\(`a, etc\&.) i una petita descripci\('o\&. El programa despr\('es sortir\(`a\&. Per tant, el par\(`ametre
\fInom_fitxer_origen\fR
no t\('e perqu\(`e subministrar\-se\&.
.RE
.PP
\fB\-p\fR, \fB\-\-parse\-mode\fR \fImode\fR
.RS 4
Defineix el mode d\*(Aqan\(`alisi\&. El par\(`ametre \(Fo\fImode\fR\(Fc pot ser \(Fofast\(Fc (R\(`apida) (el qual \('es el predeterminat) o \(Fofull\(Fc (Completa)\&. El mode \(Fofast\(Fc no analitzar\(`a tot el fitxer per\(`o emprar\(`a els elements meta de cerca per a localitzar els elements requerits d\*(Aqun fitxer d\*(Aqorigen\&. En el 99% dels casos n\*(Aqhi haur\(`a prou\&. No obstant aix\(`o, pels fitxers que no contenen elements meta de cerca o que estan malmesos, l\*(Aqusuari hauria d\*(Aqemprar el mode d\*(Aqan\(`alisi \(Fofull\(Fc\&. L\*(Aqan\(`alisi completa d\*(Aqun fitxer pot trigar alguns minuts, mentre que una an\(`alisi r\(`apida nom\('es portar\(`a alguns segons\&.
.RE
.PP
Accions que tenen a veure amb les propietats d\*(Aqinformaci\('o de la pista i del segment:
.PP
\fB\-e\fR, \fB\-\-edit\fR \fIselector\fR
.RS 4
Defineix la secci\('o del fitxer
Matroska(TM)
(informaci\('o del segment o una certa cap\(,calera d\*(Aquna pista) sobre la qual se centraran les seg\(:uents accions:
add
(afegir),
set
(establir) i
delete
(suprimir)\&. Aquesta opci\('o es pot emprar m\('ultiples vegades de manera que es pot modificar m\('es d\*(Aqun element alhora\&.
.sp
Per omissi\('o, el
\fBmkvpropedit\fR(1)
editar\(`a la secci\('o d\*(Aqinformaci\('o del segment\&.
.sp
Vegeu la secci\('o sobre
els selectors per a l\*(Aqedici\('o, per a una completa descripci\('o de la sintaxi\&.
.RE
.PP
\fB\-a\fR, \fB\-\-add\fR \fInom\fR=\fIvalor\fR
.RS 4
Afegeix una propietat
\fInom\fR
amb el contingut de
\fIvalor\fR\&. Aquesta propietat ser\(`a afegida fins i tot si ja existeix\&. Tingueu en compte que la majoria de les propietats s\('on \('uniques i nom\('es es troben una vegada\&.
.RE
.PP
\fB\-s\fR, \fB\-\-set\fR \fInom\fR=\fIvalor\fR
.RS 4
Defineix totes les ocurr\(`encies de la propietat
\fInom\fR
amb el contingut de
\fIvalor\fR\&. Si no existeix dita propietat, llavors ser\(`a afegida\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR \fInom\fR
.RS 4
Suprimeix totes les ocurr\(`encies de la propietat
\fInom\fR\&. Tingueu en compte que algunes propietats s\('on requerides i no es poden suprimir\&.
.RE
.PP
Accions que tenen a veure amb etiquetes i cap\('itols:
.PP
\fB\-t\fR, \fB\-\-tags\fR \fIselector\fR:\fInom_fitxer\fR
.RS 4
Afegeix o substitueix les etiquetes al
nom_fitxer
o l\*(Aqelimina si est\(`a buit\&. El
\fBmkvpropedit\fR(1)
llegir\(`a els mateixos formats d\*(Aqetiquetes en XML que pugui llegir el
\fBmkvmerge\fR(1)\&.
.sp
El
\fIselector\fR
ser\(`a una de les paraules
\fBall\fR,
\fBglobal\fR
o
\fBtrack\fR\&. Per a
\fBall\fR, el
\fBmkvpropedit\fR(1)
substituir\(`a o eliminar\(`a totes les etiquetes en un fitxer\&. Amb
\fBglobal\fR
nom\('es se substituiran o eliminaran les etiquetes globals\&.
.sp
Amb
\fBtrack\fR, el
\fBmkvpropedit\fR(1)
substituir\(`a les etiquetes d\*(Aquna pista espec\('ifica\&. A m\('es, les etiquetes llegides des de
nom_fitxer
seran assignades a la mateixa pista\&. La pista s\*(Aqespecifica de la mateixa manera que amb els
selectors per a l\*(Aqedici\('o
(vegeu a continuaci\('o), p\&. ex\&.,
\-\-tags track:a1:etiquetes_d_\(`audio_noves\&.xml\&.
.RE
.PP
\fB\-\-add\-track\-statistics\-tags\fR
.RS 4
Calcula les estad\('istiques per a totes les pistes en un fitxer i hi afegeix etiquetes d\*(Aqestad\('istiques noves\&. Si el fitxer ja cont\('e dites etiquetes, llavors seran actualitzades\&.
.RE
.PP
\fB\-\-delete\-track\-statistics\-tags\fR
.RS 4
Suprimeix totes les etiquetes d\*(Aqestad\('istiques existents a la pista d\*(Aqun fitxer\&. Si el fitxer no cont\('e etiquetes d\*(Aqestad\('istiques de la pista, llavors no ser\(`a modificat\&.
.RE
.PP
\fB\-c\fR, \fB\-\-chapters\fR \fInom_fitxer\fR
.RS 4
Afegeix o substitueix els cap\('itols al
nom_fitxer
o els elimina si est\(`a buit\&. El
\fBmkvpropedit\fR(1)
llegir\(`a els mateixos formats de cap\('itols simple i en XML que pugui llegir el
\fBmkvmerge\fR(1)\&.
.RE
.PP
Accions per a manejar els adjunts:
.PP
\fB\-\-add\-attachment\fR \fInom_fitxer\fR
.RS 4
Afegeix un adjunt nou des de
\fInom_fitxer\fR\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-name\fR, llavors s\*(Aqemprar\(`a el seu valor com a nom del nou adjunt\&. D\*(Aqaltra manera, derivar\(`a del
\fInom_fitxer\fR\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-mime\-type\fR, llavors s\*(Aqemprar\(`a el seu valor com a tipus MIME del nou adjunt\&. D\*(Aqaltra manera, es detectar\(`a autom\(`aticament del contingut de
\fInom_fitxer\fR\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-description\fR, llavors s\*(Aqemprar\(`a el seu valor com a descripci\('o del nou adjunt\&. D\*(Aqaltra manera, no s\*(Aqestablir\(`a cap descripci\('o\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-uid\fR, llavors s\*(Aqemprar\(`a el seu valor com a UID del nou adjunt\&. D\*(Aqaltra manera, es generar\(`a autom\(`aticament un UID aleatori\&.
.RE
.PP
\fB\-\-replace\-attachment\fR \fIselector\fR:\fInom_fitxer\fR
.RS 4
Substitueix un o m\('es adjunts que coincideixin amb el
\fIselector\fR
del
\fInom_fitxer\fR\&. Si coincideix m\('es d\*(Aqun adjunt, llavors tot el seu contingut ser\(`a substitu\(:it pel contingut del
\fInom_fitxer\fR\&.
.sp
El
\fIselector\fR
pot tenir una d\*(Aqentre quatre formes\&. Estan explicades a continuaci\('o, a la secci\('o
els selectors per a l\*(Aqadjunt\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-name\fR, llavors s\*(Aqemprar\(`a el seu valor com a nom per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap nom\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-mime\-type\fR, llavors s\*(Aqemprar\(`a el seu valor com a tipus MIME per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap tipus MIME\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-description\fR, llavors s\*(Aqemprar\(`a el seu valor com a descripci\('o per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap descripci\('o\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-uid\fR, llavors s\*(Aqemprar\(`a el seu valor com a UID per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap UID\&.
.RE
.PP
\fB\-\-update\-attachment\fR \fIselector\fR
.RS 4
Defineix les propietats d\*(Aqun o m\('es adjunts que coincideixen amb el
\fIselector\fR\&. Si coincideix m\('es d\*(Aqun adjunt, llavors s\*(Aqactualitzaran totes les seves propietats\&.
.sp
El
\fIselector\fR
pot tenir una d\*(Aqentre quatre formes\&. Estan explicades a continuaci\('o, a la secci\('o
els selectors per a l\*(Aqadjunt\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-name\fR, llavors s\*(Aqemprar\(`a el seu valor com a nom per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap nom\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-mime\-type\fR, llavors s\*(Aqemprar\(`a el seu valor com a tipus MIME per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap tipus MIME\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-description\fR, llavors s\*(Aqemprar\(`a el seu valor com a descripci\('o per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap descripci\('o\&.
.sp
Si s\*(Aqha emprat abans l\*(Aqopci\('o
\fB\-\-attachment\-uid\fR, llavors s\*(Aqemprar\(`a el seu valor com a UID per a cada adjunt modificat\&. D\*(Aqaltra manera, no es canviar\(`a cap UID\&.
.RE
.PP
\fB\-\-delete\-attachment\fR \fIselector\fR
.RS 4
Suprimeix un o m\('es adjunts que coincideixin amb el
\fIselector\fR\&.
.sp
El
\fIselector\fR
pot tenir una d\*(Aqentre quatre formes\&. Estan explicades a continuaci\('o, a la secci\('o
els selectors per a l\*(Aqadjunt\&.
.RE
.PP
Opcions per a les accions en els adjunts:
.PP
\fB\-\-attachment\-name\fR \fInom\fR
.RS 4
Defineix el nom a emprar per a les opcions
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
\fB\-\-attachment\-mime\-type\fR \fItipus_MIME\fR
.RS 4
Defineix el tipus MIME a emprar per a les opcions
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
\fB\-\-attachment\-description\fR \fIdescripci\('o\fR
.RS 4
Defineix la descripci\('o a emprar per a les opcions
\fB\-\-add\-attachment\fR
o
\fB\-\-replace\-attachment\fR\&.
.RE
.PP
Altres opcions:
.PP
\fB\-\-command\-line\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Defineix el joc de car\(`acters al qual convertir les cadenes indicades des de la l\('inia d\*(Aqordres\&. Per omissi\('o ser\(`a el joc de car\(`acters donat per la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-\-output\-charset\fR \fIjoc_de_car\(`acters\fR
.RS 4
Defineix el joc de car\(`acters al qual convertir les cadenes de la sortida\&. Per omissi\('o ser\(`a el joc de car\(`acters donat per la configuraci\('o regional actual del sistema\&.
.RE
.PP
\fB\-r\fR, \fB\-\-redirect\-output\fR \fInom_fitxer\fR
.RS 4
Escriu tots els missatges al
\fInom_fitxer\fR
en lloc de a la consola\&. Si b\('e aix\(`o es pot fer f\(`acilment amb la redirecci\('o de la sortida, hi ha casos en qu\(`e cal aquesta opci\('o: quan el terminal torna a interpretar la sortida abans d\*(Aqescriure\-la a un fitxer\&. Es respectar\(`a el joc de car\(`acters establert amb
\fB\-\-output\-charset\fR\&.
.RE
.PP
\fB\-\-ui\-language\fR \fIcodi\fR
.RS 4
For\(,ca l\*(Aq\('us de les traduccions pel
\fIcodi\fR
d\*(Aqidioma (p\&. ex\&., \(Fode_DE\(Fc per a les traduccions en alemany)\&. Introduint \(Folist\(Fc com a
\fIcodi\fR, es far\(`a que el programa ofereixi a la sortida una llista de les traduccions disponibles\&.
.RE
.PP
\fB\-\-debug\fR \fItema\fR
.RS 4
Activa la depuraci\('o per a una caracter\('istica espec\('ifica\&. Aquesta opci\('o nom\('es \('es \('util pels desenvolupadors\&.
.RE
.PP
\fB\-\-engage\fR \fIcaracter\('istica\fR
.RS 4
Activa les caracter\('istiques experimentals\&. Es pot sol\(mdlicitar una llista de les caracter\('istiques disponibles amb
\fBmkvpropedit \-\-engage list\fR\&. Aquestes caracter\('istiques no estan destinades a ser emprades en situacions normals\&.
.RE
.PP
\fB\-\-gui\-mode\fR
.RS 4
Activa el mode IGU\&. En aquest mode, les l\('inies surten amb un format especial que pot explicar\-vos el que est\(`a succeint per tal de controlar la IGU\&. Aquests missatges segueixen el format \(Fo#IGU#missatge\(Fc\&. El missatge pot estar seguit per parells clau/valor com \(Fo#IGU#missatge#clau1=valor1#clau2=valor2\&...\(Fc\&. Ni els missatges ni les claus seran tradu\(:ides, sempre sortiran en angl\(`es\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Ser\(`a detallat i mostrar\(`a tots els elements importants del
Matroska(TM)
a mesura que es llegeixin\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra la informaci\('o d\*(Aq\('us i surt\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Mostra la informaci\('o sobre la versi\('o i surt\&.
.RE
.PP
\fB\-\-check\-for\-updates\fR
.RS 4
Comprova en l\('inia si hi ha nous llan\(,caments per baixar\-los des de l\*(AqURL
\m[blue]\fBhttp://mkvtoolnix\-releases\&.bunkus\&.org/latest\-release\&.xml\fR\m[]\&. Es generaran quatre l\('inies amb l\*(Aqestil
clau=valor: l\*(AqURL des d\*(Aqon s\*(Aqha obtingut la informaci\('o (clau
version_check_url), la versi\('o actualment en execuci\('o (clau
running_version), la versi\('o de l\*(Aq\('ultim llan\(,cament (clau
available_version) i l\*(AqURL per a la baixada (clau
download_url)\&.
.sp
Despr\('es el programa sortir\(`a amb un codi de sortida de 0 si no hi ha cap llan\(,cament m\('es recent disponible, amb 1 si hi ha disponible una nova versi\('o i amb 2 si s\*(Aqha produ\(:it algun error (p\&. ex\&., si no s\*(Aqha pogut recuperar la informaci\('o sobre l\*(Aqactualitzaci\('o)\&.
.sp
Aquesta opci\('o nom\('es estar\(`a disponible si el programa va ser constru\(:it amb la implementaci\('o per a \(Folibcurl\(Fc\&.
.RE
.PP
\fB@\fR\fIfitxer_d_opcions\&.json\fR
.RS 4
Llegeix els arguments addicionals per a la l\('inia d\*(Aqordres des del fitxer
\fIfitxer_d_opcions\fR\&. Per a m\('es informaci\('o sobre els formats admesos, vegeu la secci\('o anomenada \(FoFitxers d\*(Aqopcions\(Fc a la p\(`agina man del
\fBmkvmerge\fR(1)\&.
.RE
.SH "SELECTORS PER A L\*(AQEDICI\('O"
.PP
L\*(Aqopci\('o
\fB\-\-edit\fR
defineix la secci\('o del fitxer
Matroska(TM)
(informaci\('o del segment o certes cap\(,caleres d\*(Aquna pista) sobre la qual se centraran les seg\(:uents accions:
add,
set
i
delete\&. Aquestes seran v\(`alides fins que es trobi la seg\(:uent opci\('o
\fB\-\-edit\fR\&. L\*(Aqargument per a aquesta opci\('o s\*(Aqanomena selector per a l\*(Aqedici\('o\&.
.PP
Per omissi\('o, el
\fBmkvpropedit\fR(1)
editar\(`a la secci\('o d\*(Aqinformaci\('o del segment\&.
.SS "Informaci\('o del segment"
.PP
La informaci\('o del segment es pot seleccionar amb una d\*(Aqaquestes tres paraules: \(Foinfo\(Fc, \(Fosegment_info\(Fc o \(Fosegmentinfo\(Fc\&. Aquestes contenen propietats com el t\('itol o l\*(AqUID
del segment\&.
.SS "Cap\(,caleres de la pista"
.PP
Les cap\(,caleres de la pista es poden seleccionar amb un selector lleugerament m\('es complex\&. Totes les variants comencen amb \(Fotrack:\(Fc\&. Les propietats de la cap\(,calera de la pista inclouen elements com el codi d\*(Aqidioma, l\*(Aqetiqueta de \(Fopista per omissi\('o\(Fc o el nom de la pista\&.
.PP
\fBtrack:\fR\fIn\fR
.RS 4
Si el par\(`ametre
\fIn\fR
\('es un n\('umero, llavors se seleccionar\(`a la pista amb el n\('umero
\fIn\fR\&. L\*(Aqordre de les pistes \('es el mateix que surt amb l\*(Aqopci\('o
\fB\-\-identify\fR
del
\fBmkvmerge\fR(1)\&.
.sp
La numeraci\('o comen\(,ca per l\*(Aq1\&.
.RE
.PP
\fBtrack:\fR\fIt\fR\fIn\fR
.RS 4
Si el par\(`ametre comen\(,ca amb un \('unic car\(`acter
\fIt\fR
seguit per
\fIn\fR, llavors se seleccionar\(`a la pista n\('umero
\fIn\fR
d\*(Aqun tipus de pista espec\('ific\&. El par\(`ametre del tipus de pista
\fIt\fR, haur\(`a de ser un d\*(Aqaquests quatre car\(`acters: \(Foa\(Fc per a una pista d\*(Aq\(`audio, \(Fob\(Fc per a una pista de bot\('o, \(Fos\(Fc per a una pista de subt\('itols i \(Fov\(Fc per a una pista de v\('ideo\&. L\*(Aqordre de les pistes \('es el mateix que surt amb l\*(Aqopci\('o
\fB\-\-identify\fR
del
\fBmkvmerge\fR(1)\&.
.sp
La numeraci\('o comen\(,ca per l\*(Aq1\&.
.RE
.PP
\fBtrack:\fR=\fIUID\fR
.RS 4
Si el par\(`ametre comen\(,ca amb un signe \(Fo=\(Fc seguit per un n\('umero
\fIUID\fR, llavors se seleccionar\(`a la pista on l\*(Aqelement
UID
de la pista sigui igual que aquest
\fIUID\fR\&. L\*(AqUID
de la pista es pot obtenir amb el
\fBmkvinfo\fR(1)\&.
.RE
.PP
\fBtrack:\fR@\fIn\('umero\fR
.RS 4
Si el par\(`ametre comen\(,ca amb un signe \(Fo@\(Fc seguit per un
\fIn\('umero\fR, llavors se seleccionar\(`a la pista on l\*(Aqelement n\('umero de la pista sigui igual que aquest
\fIn\('umero\fR\&. El n\('umero de la pista es pot obtenir amb el
\fBmkvinfo\fR(1)\&.
.RE
.SS "Notes"
.PP
A causa de la naturalesa dels selectors per a l\*(Aqedici\('o de la pista, \('es possible que realment alguns selectors coincideixin amb les mateixes cap\(,caleres de les pistes\&. En molts casos, totes les accions d\*(Aqaquests selectors per a l\*(Aqedici\('o seran combinades i executades en l\*(Aqordre en el qual es van indicar a la l\('inia d\*(Aqordres\&.
.SH "SELECTORS PER A L\*(AQADJUNT"
.PP
Un selector per a l\*(Aqadjunt s\*(Aqempra amb les dues accions
\fB\-\-replace\-attachment\fR
i
\fB\-\-delete\-attachment\fR\&. Aquest pot tenir una de les quatre formes seg\(:uents:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Selecci\('o mitjan\(,cant l\*(AqID de l\*(Aqadjunt\&. D\*(Aqaquesta forma, el selector \('es un simple n\('umero, l\*(AqID de l\*(Aqadjunt tal com surt amb l\*(Aqordre d\*(Aqidentificaci\('o del
\fBmkvmerge\fR(1)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Selecci\('o mitjan\(,cant l\*(AqUID de l\*(Aqadjunt (ID \('unic)\&. D\*(Aqaquesta forma, el selector \('es el signe
=
seguit per un n\('umero, l\*(AqID \('unic de l\*(Aqadjunt tal com surt amb l\*(Aqordre d\*(Aqidentificaci\('o del
\fBmkvmerge\fR(1)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Selecci\('o mitjan\(,cant el nom de l\*(Aqadjunt\&. D\*(Aqaquesta forma el selector \('es la paraula literal
name:
seguida pel nom de l\*(Aqadjunt existent\&. Si aquest selector \('es emprat amb
\fB\-\-replace\-attachment\fR, llavors per a que pugui coincidir s\*(Aqhaur\(`a d\*(Aqescapar el signe dels dos punts amb
\ec\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Selecci\('o mitjan\(,cant el tipus MIME de l\*(Aqadjunt\&. D\*(Aqaquesta forma el selector \('es la paraula literal
mime\-type:
seguida pel tipus MIME de l\*(Aqadjunt existent\&. Si aquest selector \('es emprat amb
\fB\-\-replace\-attachment\fR, llavors per a que pugui coincidir s\*(Aqhaur\(`a d\*(Aqescapar el signe dels dos punts amb
\ec\&.
.RE
.SH "EXEMPLES"
.PP
El seg\(:uent exemple edita un fitxer anomenat \(Fopeli\&.mkv\(Fc\&. Defineix el t\('itol del segment i modifica el codi d\*(Aqidioma d\*(Aquna pista d\*(Aq\(`audio i d\*(Aquna pista de subt\('itols\&. Tingueu en compte que aquest exemple es pot escur\(,car llevant la primera opci\('o
\fB\-\-edit\fR, ja que editar l\*(Aqelement d\*(Aqinformaci\('o del segment est\(`a incl\(`os per omissi\('o per a totes les opcions trobades abans de la primera opci\('o
\fB\-\-edit\fR\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-edit info \-\-set "title=La pel\(mdl\('icula" \-\-edit track:a1 \-\-set language=cat \-\-edit track:a2 \-\-set language=ita
.fi
.if n \{\
.RE
.\}
.PP
El segon exemple elimina l\*(Aq\(Foetiqueta de pista per omissi\('o\(Fc de la primera pista de subt\('itols i la defineix per a la segona\&. Tingueu present que el
\fBmkvpropedit\fR(1), a difer\(`encia del
\fBmkvmerge\fR(1), no defineix autom\(`aticament a \(Fo0\(Fc el valor de l\*(Aq\(Foetiqueta de pista per omissi\('o\(Fc quan un pista diferent s\*(Aqha establert a \(Fo1\(Fc\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-edit track:s1 \-\-set flag\-default=0 \-\-edit track:s2 \-\-set flag\-default=1
.fi
.if n \{\
.RE
.\}
.PP
Substituir les etiquetes per a la segona pista de subt\('itols en un fitxer es veu aix\('i:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-tags track:s2:etiquetes_subt\('itols_noves\&.xml
.fi
.if n \{\
.RE
.\}
.PP
Eliminar totes les etiquetes requereix ometre el nom del fitxer d\*(Aqetiquetes:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-tags all:
.fi
.if n \{\
.RE
.\}
.PP
Substituir els cap\('itols en un fitxer es veu aix\('i:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-chapters cap\('itols_nous\&.xml
.fi
.if n \{\
.RE
.\}
.PP
Eliminar tots els cap\('itols requereix ometre el nom del fitxer:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-chapters \*(Aq\*(Aq
.fi
.if n \{\
.RE
.\}
.PP
Afegir un fitxer de tipus de lletra (Arial\&.ttf) com un adjunt:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-add\-attachment Arial\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Afegir un fitxer de tipus de lletra (89719823\&.ttf) com un adjunt i proporcionar alguna informaci\('o de com \('es aquest tipus de lletra:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-attachment\-name Arial\&.ttf \-\-attachment\-description \*(AqEl tipus de lletra Arial com a tipus de lletra TrueType\*(Aq \-\-attachment\-mime\-type application/x\-truetype\-font \-\-add\-attachment 89719823\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Substituir un fitxer de tipus de lletra adjuntat (Comic\&.ttf) per un altre (Arial\&.ttf):
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-attachment\-name Arial\&.ttf \-\-attachment\-description \*(AqEl tipus de lletra Arial com a tipus de lletra TrueType\*(Aq \-\-replace\-attachment name:Comic\&.ttf:Arial\&.ttf
.fi
.if n \{\
.RE
.\}
.PP
Suprimir el segon fitxer adjuntat, sigui el que sigui:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-delete\-attachment 2
.fi
.if n \{\
.RE
.\}
.PP
Suprimir tots els tipus de lletra adjuntats segons el tipus MIME:
.sp
.if n \{\
.RS 4
.\}
.nf
$ mkvpropedit peli\&.mkv \-\-delete\-attachment mime\-type:application/x\-truetype\-font
.fi
.if n \{\
.RE
.\}
.SH "CODIS DE SORTIDA"
.PP
El
\fBmkvpropedit\fR(1)
sortir\(`a amb un d\*(Aqaquests tres codis de sortida:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB0\fR
\-\- Aquest codi de sortida significa que la modificaci\('o s\*(Aqha realitzat correctament\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB1\fR
\-\- En aquest cas, el
\fBmkvpropedit\fR(1)
ha generat una sortida amb almenys un av\('is, per\(`o la modificaci\('o ha continuat\&. Un av\('is \('es prefixat amb el text \(FoAv\('is:\(Fc\&. Depenent de les q\(:uestions involucrades, els fitxers resultants seran o no correctes\&. L\*(Aqusuari ser\(`a instat a revisar tant els avisos com els fitxers\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fB2\fR
\-\- Aquest codi de sortida s\*(Aqempra despr\('es de produir\-se un error\&. El
\fBmkvpropedit\fR(1)
interrompr\(`a el proc\('es just despr\('es de mostrar el missatge d\*(Aqerror\&. L\*(Aqinterval dels missatges d\*(Aqerror va des d\*(Aqarguments incorrectes a la l\('inia d\*(Aqordres fins a errors de lectura/escriptura en fitxers malmesos\&.
.RE
.SH "CONVERSI\('O PER A FITXERS DE TEXT I JOCS DE CAR\(`ACTERS"
.PP
Per a un debat en profunditat sobre com manipula la suite MKVToolNix les conversions entre els jocs de car\(`acters, codifica l\*(Aqentrada/sortida, codifica la l\('inia d\*(Aqordres i codifica a la consola, si us plau, vegeu la secci\('o anomenada de la mateixa manera a la p\(`agina man del
\fBmkvmerge\fR(1)\&.
.SH "ESCAPAR CAR\(`ACTERS ESPECIALS EN EL TEXT"
.PP
Hi ha pocs llocs en els quals els car\(`acters especials en el text puguin o s\*(Aqhagin d\*(Aqescapar\&. Les regles per a l\*(Aqescapament s\('on simples: cada car\(`acter que necessiti ser escapat ser\(`a substitu\(:it amb una barra invertida seguida d\*(Aqun altre car\(`acter\&.
.PP
Les regles s\('on: \(Fo \(Fc (un espai) ser\(`a \(Fo\es\(Fc, \(Fo"\(Fc (cometes dobles) ser\(`a \(Fo\e2\(Fc, \(Fo:\(Fc ser\(`a \(Fo\ec\(Fc, \(Fo#\(Fc ser\(`a \(Fo\eh\(Fc i \(Fo\e\(Fc (una \('unica barra invertida) ser\(`a \(Fo\e\e\(Fc\&.
.SH "VARIABLES D\*(AQENTORN"
.PP
El
\fBmkvpropedit\fR(1)
empra les variables per omissi\('o que es determinen a la configuraci\('o regional del sistema (p\&. ex\&.,
\fILANG\fR
i la fam\('ilia
\fILC_*\fR)\&. Variables addicionals:
.PP
\fIMKVPROPEDIT_DEBUG\fR, \fIMKVTOOLNIX_DEBUG\fR i la seva forma abreujada \fIMTX_DEBUG\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-debug\fR\&.
.RE
.PP
\fIMKVPROPEDIT_ENGAGE\fR, \fIMKVTOOLNIX_ENGAGE\fR i la seva forma abreujada \fIMTX_ENGAGE\fR
.RS 4
El contingut es tractar\(`a com si s\*(Aqhagu\('es passat l\*(Aqopci\('o
\fB\-\-engage\fR\&.
.RE
.PP
\fIMKVPROPEDIT_OPTIONS\fR, \fIMKVTOOLNIX_OPTIONS\fR i la seva forma abreujada \fIMTX_OPTIONS\fR
.RS 4
El contingut ser\(`a dividit en espais en blanc\&. Les cadenes parcials resultants seran tractades com si haguessin estat passades com a opcions a la l\('inia d\*(Aqordres\&. Si necessiteu passar car\(`acters especials (p\&. ex\&., espais) llavors els haureu d\*(Aqescapar (vegeu
la secci\('o sobre escapar car\(`acters especials en el text)\&.
.RE
.SH "VEGEU TAMB\('E"
.PP
\fBmkvmerge\fR(1),
\fBmkvinfo\fR(1),
\fBmkvextract\fR(1),
\fBmkvtoolnix-gui\fR(1)
.SH "WWW"
.PP
Sempre trobareu l\*(Aq\('ultima versi\('o a
\m[blue]\fBla p\(`agina de les MKVToolNix\fR\m[]\&\s-2\u[1]\d\s+2\&.
.SH "AUTOR"
.PP
\fBBunkus, Moritz\fR <\&moritz@bunkus\&.org\&>
.RS 4
Desenvolupador
.RE
.SH "NOTES"
.IP " 1." 4
la p\(`agina de les MKVToolNix
.RS 4
\%https://mkvtoolnix.download/
.RE
