/*
   mkvmerge -- utility for splicing together matroska files
   from component media subtypes

   Distributed under the GPL v2
   see the file COPYING for details
   or visit http://www.gnu.org/copyleft/gpl.html

   IANA language subtag registry

   Written by Moritz Bunkus <moritz@bunkus.org>.
*/

// ----------------------------------------------------------------------------------------------
// NOTE: this file is auto-generated by the "dev:iana_language_subtag_registry_list" rake target.
// ----------------------------------------------------------------------------------------------

#include "common/common_pch.h"

#include "common/iana_language_subtag_registry.h"

namespace mtx::iana::language_subtag_registry {

std::vector<variant_t> const g_variants{
  { "1606nict"s, u8"Late Middle French (to 1606)"s,                               { "frm"s }                                                                                   },
  { "1694acad"s, u8"Early Modern French"s,                                        { "fr"s }                                                                                    },
  { "1901"s,     u8"Traditional German orthography"s,                             { "de"s }                                                                                    },
  { "1959acad"s, u8"\"Academic\" (\"governmental\") variant of Belarusian as"s,   { "be"s }                                                                                    },
  { "1994"s,     u8"Standardized Resian orthography"s,                            { "sl-rozaj"s, "sl-rozaj-biske"s, "sl-rozaj-njiva"s, "sl-rozaj-osojs"s, "sl-rozaj-solba"s }  },
  { "1996"s,     u8"German orthography of 1996"s,                                 { "de"s }                                                                                    },
  { "abl1943"s,  u8"Orthographic formulation of 1943 - Official in Brazil"s,      { "pt-BR"s }                                                                                 },
  { "akuapem"s,  u8"Akuapem Twi"s,                                                { "tw"s }                                                                                    },
  { "alalc97"s,  u8"ALA-LC Romanization, 1997 edition"s,                          {}                                                                                           },
  { "aluku"s,    u8"Boni dialect"s,                                               { "djk"s }                                                                                   },
  { "ao1990"s,   u8"Portuguese Language Orthographic Agreement of 1990 (Acordo"s, { "gl"s, "pt"s }                                                                             },
  { "aranes"s,   u8"Aranese"s,                                                    { "oc"s }                                                                                    },
  { "arevela"s,  u8"Eastern Armenian"s,                                           { "hy"s }                                                                                    },
  { "arevmda"s,  u8"Western Armenian"s,                                           { "hy"s }                                                                                    },
  { "asante"s,   u8"Ashanti Twi"s,                                                { "tw"s }                                                                                    },
  { "auvern"s,   u8"Auvergnat"s,                                                  { "oc"s }                                                                                    },
  { "baku1926"s, u8"Unified Turkic Latin Alphabet (Historical)"s,                 { "az"s, "ba"s, "crh"s, "kk"s, "krc"s, "ky"s, "sah"s, "tk"s, "tt"s, "uz"s }                  },
  { "balanka"s,  u8"The Balanka dialect of Anii"s,                                { "blo"s }                                                                                   },
  { "barla"s,    u8"The Barlavento dialect group of Kabuverdianu"s,               { "kea"s }                                                                                   },
  { "basiceng"s, u8"Basic English"s,                                              { "en"s }                                                                                    },
  { "bauddha"s,  u8"Buddhist Hybrid Sanskrit"s,                                   { "sa"s }                                                                                    },
  { "biscayan"s, u8"Biscayan dialect of Basque"s,                                 { "eu"s }                                                                                    },
  { "biske"s,    u8"The Bila dialect of Resian"s,                                 { "sl-rozaj"s }                                                                              },
  { "bohoric"s,  u8"Slovene in Bohorič alphabet"s,                                { "sl"s }                                                                                    },
  { "boont"s,    u8"Boontling"s,                                                  { "en"s }                                                                                    },
  { "bornholm"s, u8"Bornholmsk"s,                                                 { "da"s }                                                                                    },
  { "cisaup"s,   u8"Cisalpine"s,                                                  { "oc"s }                                                                                    },
  { "colb1945"s, u8"Portuguese-Brazilian Orthographic Convention of 1945"s,       { "pt"s }                                                                                    },
  { "cornu"s,    u8"Anglo-Cornish"s,                                              { "en"s }                                                                                    },
  { "creiss"s,   u8"Occitan variants of the Croissant area"s,                     { "oc"s }                                                                                    },
  { "dajnko"s,   u8"Slovene in Dajnko alphabet"s,                                 { "sl"s }                                                                                    },
  { "ekavsk"s,   u8"Serbian with Ekavian pronunciation"s,                         { "sr"s, "sr-Cyrl"s, "sr-Latn"s }                                                            },
  { "emodeng"s,  u8"Early Modern English (1500-1700)"s,                           { "en"s }                                                                                    },
  { "fonipa"s,   u8"International Phonetic Alphabet"s,                            {}                                                                                           },
  { "fonkirsh"s, u8"Kirshenbaum Phonetic Alphabet"s,                              {}                                                                                           },
  { "fonnapa"s,  u8"Americanist Phonetic Notation"s,                              {}                                                                                           },
  { "fonupa"s,   u8"Uralic Phonetic Alphabet"s,                                   {}                                                                                           },
  { "fonxsamp"s, u8"X-SAMPA transcription"s,                                      {}                                                                                           },
  { "gascon"s,   u8"Gascon"s,                                                     { "oc"s }                                                                                    },
  { "grclass"s,  u8"Classical Occitan orthography"s,                              { "oc"s }                                                                                    },
  { "grital"s,   u8"Italian-inspired Occitan orthography"s,                       { "oc"s }                                                                                    },
  { "grmistr"s,  u8"Mistralian or Mistralian-inspired Occitan orthography"s,      { "oc"s }                                                                                    },
  { "hepburn"s,  u8"Hepburn romanization"s,                                       { "ja-Latn"s }                                                                               },
  { "heploc"s,   u8"Hepburn romanization, Library of Congress method"s,           { "ja-Latn-hepburn"s }                                                                       },
  { "hognorsk"s, u8"Norwegian in Høgnorsk (High Norwegian) orthography"s,         { "nn"s }                                                                                    },
  { "hsistemo"s, u8"Standard H-system orthographic fallback for spelling"s,       { "eo"s }                                                                                    },
  { "ijekavsk"s, u8"Serbian with Ijekavian pronunciation"s,                       { "sr"s, "sr-Cyrl"s, "sr-Latn"s }                                                            },
  { "itihasa"s,  u8"Epic Sanskrit"s,                                              { "sa"s }                                                                                    },
  { "ivanchov"s, u8"Bulgarian in 1899 orthography"s,                              { "bg"s }                                                                                    },
  { "jauer"s,    u8"Jauer dialect of Romansh"s,                                   { "rm"s }                                                                                    },
  { "jyutping"s, u8"Jyutping Cantonese Romanization"s,                            { "yue"s }                                                                                   },
  { "kkcor"s,    u8"Common Cornish orthography of Revived Cornish"s,              { "kw"s }                                                                                    },
  { "kociewie"s, u8"The Kociewie dialect of Polish"s,                             { "pl"s }                                                                                    },
  { "kscor"s,    u8"Kernowek Standard"s,                                          { "kw"s }                                                                                    },
  { "laukika"s,  u8"Classical Sanskrit"s,                                         { "sa"s }                                                                                    },
  { "lemosin"s,  u8"Limousin"s,                                                   { "oc"s }                                                                                    },
  { "lengadoc"s, u8"Languedocien"s,                                               { "oc"s }                                                                                    },
  { "lipaw"s,    u8"The Lipovec dialect of Resian"s,                              { "sl-rozaj"s }                                                                              },
  { "luna1918"s, u8"Post-1917 Russian orthography"s,                              { "ru"s }                                                                                    },
  { "metelko"s,  u8"Slovene in Metelko alphabet"s,                                { "sl"s }                                                                                    },
  { "monoton"s,  u8"Monotonic Greek"s,                                            { "el"s }                                                                                    },
  { "ndyuka"s,   u8"Aukan dialect"s,                                              { "djk"s }                                                                                   },
  { "nedis"s,    u8"Nadiza dialect"s,                                             { "sl"s }                                                                                    },
  { "newfound"s, u8"Newfoundland English"s,                                       { "en-CA"s }                                                                                 },
  { "nicard"s,   u8"Niçard"s,                                                     { "oc"s }                                                                                    },
  { "njiva"s,    u8"The Njiva dialect of Resian"s,                                { "sl-rozaj"s }                                                                              },
  { "nulik"s,    u8"Modern Volapük"s,                                             { "vo"s }                                                                                    },
  { "osojs"s,    u8"The Osojane dialect of Resian"s,                              { "sl-rozaj"s }                                                                              },
  { "oxendict"s, u8"Oxford English Dictionary spelling"s,                         { "en"s }                                                                                    },
  { "pahawh2"s,  u8"Pahawh Hmong Second Stage Reduced orthography"s,              { "hnj"s, "mww"s }                                                                           },
  { "pahawh3"s,  u8"Pahawh Hmong Third Stage Reduced orthography"s,               { "hnj"s, "mww"s }                                                                           },
  { "pahawh4"s,  u8"Pahawh Hmong Final Version orthography"s,                     { "hnj"s, "mww"s }                                                                           },
  { "pamaka"s,   u8"Pamaka dialect"s,                                             { "djk"s }                                                                                   },
  { "peano"s,    u8"Interlingua de Peano"s,                                       { "la"s }                                                                                    },
  { "petr1708"s, u8"Petrine orthography"s,                                        { "ru"s }                                                                                    },
  { "pinyin"s,   u8"Pinyin romanization"s,                                        { "bo-Latn"s, "zh-Latn"s }                                                                   },
  { "polyton"s,  u8"Polytonic Greek"s,                                            { "el"s }                                                                                    },
  { "provenc"s,  u8"Provençal"s,                                                  { "oc"s }                                                                                    },
  { "puter"s,    u8"Puter idiom of Romansh"s,                                     { "rm"s }                                                                                    },
  { "rigik"s,    u8"Classic Volapük"s,                                            { "vo"s }                                                                                    },
  { "rozaj"s,    u8"Rezijan"s,                                                    { "sl"s }                                                                                    },
  { "rumgr"s,    u8"Rumantsch Grischun"s,                                         { "rm"s }                                                                                    },
  { "scotland"s, u8"Scottish Standard English"s,                                  { "en"s }                                                                                    },
  { "scouse"s,   u8"Scouse"s,                                                     { "en"s }                                                                                    },
  { "simple"s,   u8"Simplified form"s,                                            {}                                                                                           },
  { "solba"s,    u8"The Solbica dialect of Resian"s,                              { "sl-rozaj"s }                                                                              },
  { "sotav"s,    u8"The Sotavento dialect group of Kabuverdianu"s,                { "kea"s }                                                                                   },
  { "spanglis"s, u8"Spanglish"s,                                                  { "en"s, "es"s }                                                                             },
  { "surmiran"s, u8"Surmiran idiom of Romansh"s,                                  { "rm"s }                                                                                    },
  { "sursilv"s,  u8"Sursilvan idiom of Romansh"s,                                 { "rm"s }                                                                                    },
  { "sutsilv"s,  u8"Sutsilvan idiom of Romansh"s,                                 { "rm"s }                                                                                    },
  { "tarask"s,   u8"Belarusian in Taraskievica orthography"s,                     { "be"s }                                                                                    },
  { "tongyong"s, u8"Tongyong Pinyin romanization"s,                               { "zh-Latn"s }                                                                               },
  { "uccor"s,    u8"Unified Cornish orthography of Revived Cornish"s,             { "kw"s }                                                                                    },
  { "ucrcor"s,   u8"Unified Cornish Revised orthography of Revived Cornish"s,     { "kw"s }                                                                                    },
  { "ulster"s,   u8"Ulster dialect of Scots"s,                                    { "sco"s }                                                                                   },
  { "unifon"s,   u8"Unifon phonetic alphabet"s,                                   { "en"s, "hup"s, "kyh"s, "tol"s, "yur"s }                                                    },
  { "vaidika"s,  u8"Vedic Sanskrit"s,                                             { "sa"s }                                                                                    },
  { "valencia"s, u8"Valencian"s,                                                  { "ca"s }                                                                                    },
  { "vallader"s, u8"Vallader idiom of Romansh"s,                                  { "rm"s }                                                                                    },
  { "vivaraup"s, u8"Vivaro-Alpine"s,                                              { "oc"s }                                                                                    },
  { "wadegile"s, u8"Wade-Giles romanization"s,                                    { "zh-Latn"s }                                                                               },
  { "xsistemo"s, u8"Standard X-system orthographic fallback for spelling"s,       { "eo"s }                                                                                    },
};

} // namespace mtx::iana::language_subtag_registry
